### ISSUE TITLE
editrealtime with accumulator

### ISSUE THREAD

**Issue by threldor** [emoncms/emoncms#100]
After editing a value which is not the latest the accumulator begins counting from whatever the recently edited value was. 

Example, say i have a series
1,2,7,4,5,6,7,8,9...
I want to edit the 3rd value to 3 as 7 is wrong
After doing this it should continue
1,2,3,4,5,6,7,8,9, 10,11,12.....
however continues
1,2,3,4,5,6,7,8,9, 4,5,6.....

I think this is because the feeds table is updated with the recently changed value rather than staying as the latest ( in the example it changed to 3 instead of staying at 9) This is the correct action to take if the latest value is edited however is not correct for any other value.

**Comment by Paul-Reed** [comment]
Is this still an issue in the current version - v9?

**Comment by Paul-Reed** [comment]
Unable to confirm issue due to being superseded by v9.
Closed pending update from original author.
