### ISSUE TITLE
Beta features - feed unit displaying 'undefined'

### ISSUE THREAD

**Issue by Paul-Reed** [emoncms/emoncms#1000]
I’m assuming that the ‘feed unit’ is not mandatory, and is at the discretion of the user if they wish to assign a ‘unit’ to their feed or not.
That being the case, could you consider removing the ‘undefined’ text please.

![undefined](https://user-images.githubusercontent.com/973580/44539665-af6e2200-a6fc-11e8-94d6-9dbdb850cb8b.PNG)

So that users just see;
23.2°C
33.7
2.9

**Comment by TrystanLea** [comment]
Thanks @Paul-Reed That's strange I thought this was only an issue affecting emoncms.org, I've copied the fix across, now in master: https://github.com/emoncms/emoncms/commit/a1a427971eb737cb0a02155495f4daf5fa1f861e

**Comment by Paul-Reed** [comment]
Yes, that's now sorted.

Thanks
