### ISSUE TITLE
user defined process quick links

### ISSUE THREAD

**Issue by pb66** [emoncms/emoncms#1004]
Extending #926 (already a great improvement, especially if users use the log to feed, power to kWh and +input processes a lot)

![image](https://user-images.githubusercontent.com/5606042/44618701-072e9980-a873-11e8-8af0-29f6ee42fb2b.png)

What might be nice is to add a "quick link" checkbox on the far right of any selected process so that users can select and deselect their own favorite quick links

![image](https://user-images.githubusercontent.com/5606042/44618738-9cca2900-a873-11e8-818e-bd70a1f35fd6.png)

so the quick link bar can auto populate depending on the processes selected by the user as the most used, they only need to manually select the process once and then tick the box for it to become a quick link.

**Comment by TrystanLea** [comment]
Thanks @pb66 this will likely add a lot of additional complexity, the preference will need to be stored stored and retrieved. I would prefer to keep this behaviour simplified for now, but can leave this one up for the future.

**Comment by pb66** [comment]
> but can leave this one up for the future.

That's fine, I had anticipated developing some additional process modules so the dropdown might get a bit busy, but although. I do have additional process modules they are not ready for general release yet.

**Comment by TrystanLea** [comment]
I don’t think we are going to get a chance to work on this due to limited time resources. Happy to receive a pull request if anyone else wants to try implementing it?
