### ISSUE TITLE
Language/locale not working

### ISSUE THREAD

**Issue by tleegaard** [emoncms/emoncms#101]
Am I the only one having problems with changing the language of emoncms?
When changing the Language setting at the Account page (user/view) nothing happens and emoncms stays english.

Does the setting for preferred language in Firefox override the setting at the Account page?

**Comment by Paul-Reed** [comment]
Many changes to locale has taken place over the past 14 months, can you confirm that this is still an issue in v9 please.

**Comment by Paul-Reed** [comment]
Unable to confirm issue due to being superseded by v9.
Closed pending update from original author.

**Comment by miguelalonso** [comment]
emoncms 9.9.7 change language is not working.
