### ISSUE TITLE
MySQL database setup for user registration.

### ISSUE THREAD

**Issue by danbates2** [emoncms/emoncms#1016]
I recently went through an install and the problem still exists.
https://github.com/emoncms/emoncms/issues/791

I also had to do the following:
ALTER TABLE users CHANGE preferences preferences TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;

**Comment by danbates2** [comment]
I believe if we drop in :

`ALTER TABLE users CHANGE tags tags TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;`

`ALTER TABLE users CHANGE preferences preferences TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;`

here:
https://github.com/emoncms/emoncms/blob/master/Lib/dbschemasetup.php

this would be a fix?

**Comment by takkaria** [comment]
If you just remove 'null'=>true from user_schema.php it should work.  I did submit a pull request that rewrote the database schema code in a more robust way in #930 but no-one's accepted it yet.

**Comment by danbates2** [comment]
Thanks. I've just tried that on a fresh install and it hasn't worked.
```
    'tags' => array('type' => 'text', 'default'=>NULL, 'Null'=>true),
    'startingpage' => array('type'=>'varchar(64)', 'default'=>'feed/list'),
    'email_verified' => array('type' => 'int(11)', 'default'=>0),
    'verification_key' => array('type' => 'varchar(64)', 'default'=>''),
    'preferences' => array('type' => 'varchar(255)', 'default'=>NULL, 'Null'=>true)
);
```
For a long shot I tried removing **, 'default'=>NULL,** also.

**Comment by danbates2** [comment]
I've also tried your changes, including both your dbschemasetup.php and user_schema.php, fresh install, new database. I get this error.
![image](https://user-images.githubusercontent.com/5250782/45531535-7fdca200-b7f0-11e8-9919-12fd2bc4def1.png)

**Comment by danbates2** [comment]
That worked Perfectly.
I didn't realise originally that I had to delete the original database. I'm new to this.

**Comment by danbates2** [comment]
@glynhudson @TrystanLea 
Hi Both, a very simple fix to the problem is to be found in takkaria's comment above.

**Comment by danbates2** [comment]
@glynhudson 
Thought to tag you in Glyn, Trys is still away on hols :) Check out this simple fix in the pull request.
