### ISSUE TITLE
TBD: Javascript expression builder 2

### ISSUE THREAD

**Issue by glynhudson** [emoncms/emoncms#1019]
I've just tried to use the Schedule module but get error "TBD: Javascript expression builder 2" when I try and edit a schedule

**Comment by chaveiro** [comment]
Hi Glyn, thas is not an error, its a missing feature (TBD = to be done). The idea was to have an easy graphical editor for building the schedule expression but i didnt had time to complete. Its better to hide the button in code commenting it.
