### ISSUE TITLE
Remove public "padlock" from feeds page

### ISSUE THREAD

**Issue by pb66** [emoncms/emoncms#1028]
The public "padlock" no longer serves as a button to toggle public/private but it still has a very prominant place on the feeds page, could this padlock be moved to the far right or included in the hover-over and removed from the centre of the feed table?

(See https://community.openenergymonitor.org/t/thoughts-on-the-new-input-and-feed-page-layouts/8583?u=pb66)

**Comment by TrystanLea** [comment]
Keen to keep the padlock in for now, alongside the feed type.
