### ISSUE TITLE
Feed page hover-over info not clear as to which feed it belongs to

### ISSUE THREAD

**Issue by pb66** [emoncms/emoncms#1029]
![image](https://user-images.githubusercontent.com/5606042/45904884-4efaff00-bde6-11e8-831d-d27ce1d7219c.png)

Could we include the feed tag:name at the top of the hover-over info box so it is more obvious which feed the info belongs to? Perhaps in bold so it works like a title eg

> **emontx : voltage**
> Feed ID: 77
> Feed Interval: 5s
> Feed Start Time: Monday, 5 Febuary 2018 08:12

(See https://community.openenergymonitor.org/t/thoughts-on-the-new-input-and-feed-page-layouts/8583?u=pb66)

**Comment by TrystanLea** [comment]
great idea!
