### ISSUE TITLE
Only phpfina feeds interval needs to be shown in feeds page hover-over info box

### ISSUE THREAD

**Issue by pb66** [emoncms/emoncms#1030]
![image](https://user-images.githubusercontent.com/5606042/45905122-35a68280-bde7-11e8-8778-3d6025ac23a0.png)

It's perhaps a little misleading, certainly not useful info to state a phptimeseries or virtual feed are 1s interval.

If feed type is moved to hover-over info box (see #1027) then perhaps the interval should only be revealed for PHPFINA feed types eg

> emontx : voltage
> Feed ID: 77
> Feed Type: PHPFINA (5s)
> Feed Start Time: Monday, 5 Febuary 2018 08:12

and 

> emontx : voltage
> Feed ID: 77
> Feed Type: PHPTIMESERIES
> Feed Start Time: Monday, 5 Febuary 2018 08:12

(See https://community.openenergymonitor.org/t/thoughts-on-the-new-input-and-feed-page-layouts/8583?u=pb66)

**Comment by TrystanLea** [comment]
Great! happy for this change, certainly would reduce confusion
