### ISSUE TITLE
Current time shown in some feed page hover over info boxes

### ISSUE THREAD

**Issue by pb66** [emoncms/emoncms#1031]
![image](https://user-images.githubusercontent.com/5606042/45905333-e9a80d80-bde7-11e8-9575-06d3189a36fa.png)

Not sure if this is because that feed has not yet been used (no data) or because it's not a PHPFINA therefore doesn't have a proper start time meta field, either way the start time of the selected feed is not now so the current time is not the right thing to display.

(See https://community.openenergymonitor.org/t/thoughts-on-the-new-input-and-feed-page-layouts/8583?u=pb66)

**Comment by TrystanLea** [comment]
thanks for spotting
