### ISSUE TITLE
PHPFINA start time meta is displayed as a time/date string rather than a timestamp

### ISSUE THREAD

**Issue by pb66** [emoncms/emoncms#1032]
On the feeds page hover-over info box, the PHPFINA feed start time is displayed as a time/date string, which is easy to read, but when using the feed start time it is more likely you need to unix timestamp rather than a string, Can we please display the unix timestamp start time, either in place of or as well as the string. 

(See https://community.openenergymonitor.org/t/thoughts-on-the-new-input-and-feed-page-layouts/8583?u=pb66)

**Comment by TrystanLea** [comment]
Yes sure, I vote for showing both
