### ISSUE TITLE
Input page : sort order

### ISSUE THREAD

**Issue by danbates2** [emoncms/emoncms#1034]
I noticed that the input page, by default, sorts data by name.

Makes sense perhaps if the inputs page reflected the order of the data string, for example:

curl -d "node=testnode&data={respect:123,for:456,women:789}&apikey=" "http://emoncms.localhost/input/post"

Input page view:
|||testnode|||
respect          123
for                  456
women           789

**Comment by TrystanLea** [comment]
Thanks Dan, I think the discussion and developments on indexedinputs may solve this one https://community.openenergymonitor.org/t/development-indexed-inputs/8354/35

**Comment by danbates2** [comment]
I think it will :)
