### ISSUE TITLE
Feed type or authentication not valid on dashboard after some time

### ISSUE THREAD

**Issue by doddz3h** [emoncms/emoncms#105]
It seems that after some time the dashboard graphs eventually start displaying
"Feed type or authentication not valid"

It is possible to get it back to life by going into edit mode of the dashboard and for every problem graph clicking configure then save changes.

**Comment by chaveiro** [comment]
This is related to session timeout.
I believe i was fixed already. Are you still seeing it?
If not, the issue can be closed.

**Comment by mehulgupta** [comment]
local install same issue
