### ISSUE TITLE
Virtual feed updated times are distorting the truth on the feeds page

### ISSUE THREAD

**Issue by pb66** [emoncms/emoncms#1056]
This probably isn't unique to virtual feeds but that is what I have at present.

This creenshot shows all is well on the feeds page

![image](https://user-images.githubusercontent.com/5606042/46257826-863d7000-c4b8-11e8-92f5-d0f44c566154.png)

The truth is that's not the case, seen here when the feed group is opened

![image](https://user-images.githubusercontent.com/5606042/46257842-f3510580-c4b8-11e8-84ba-131b2547b6b9.png)

I am aware from experience that feeds may be grouped from different devices and get updated at different times so I understand the "group updated" value must be either the last updated, the first updated or less likely, the average updated, We would possibly like to see a nice green small number there to show one or more of the feeds has updated very recently (latest last updated), but there is an equal argument for only really **needing** to know if there are feeds not updating (earliest last updated). Perhaps we need to have a "Updated 10s to 20s" and display both the earliest and latest update times?

Regardless of which time (or both) is displayed, there is no point in displaying the update time for a virtual feed. The truth is, if the virtual feed has never been displayed, it will never have been "updated" as they only generate/collate data when called in a feed api. 

The fact they virtual feeds always display as updated very recently (most often "now") it hides any delays in a group of feeds unless the group is uncollapsed. 

I guess the quick fix here is to just exclude any virtual feeds from the group total.

**Comment by TrystanLea** [comment]
I agree, removing the influence of virtual feeds would be a good idea
