### ISSUE TITLE
Difficulties renaming feeds.

### ISSUE THREAD

**Issue by pb66** [emoncms/emoncms#1066]
Using latest emoncms 9.8.31, indexedinputs branch "device-module integration beta" off.

I had created a feed with a slight typo, instaed of "GrossActiveEnergy" I had typed "grossActiveEnergy", when I tried to correct via the edit button on the feeds page, I kept getting a message telling me feed name and tag combinations must be unique. It seems emoncms is comparing the revised feed name with the existing list of feed names  including it's pre-edit version of itself, and that comparison is case insensitive so  "G" == "g".

I managed to get around this by editing the name to "XrossActiveEnergy" and then edit again to "GrossActiveEnergy".

Easy to recreate, here is the result of attempting to change back to "grossActiveEnergy" from "GrossActiveEnergy"

![image](https://user-images.githubusercontent.com/5606042/46965074-bb91b280-d0a1-11e8-9de0-4911f4bf8f58.png)

**Comment by glynhudson** [comment]
>Using latest emoncms 9.8.31, indexedinputs branch "device-module integration beta" off.

I'm assuming you mean 9.9.3?
