### ISSUE TITLE
Conversion to timestore faild 

### ISSUE THREAD

**Issue by jhagberg** [emoncms/emoncms#109]
Hej

Tried a conversion. The conversion ran fine but created no data in /var/lib/timestore
I did not run with sudo I guess that is the problem. 

I managed to change back to mysql by edinting the database. But how can I re run this conversion again to have it work in a proper way?

**Comment by Paul-Reed** [comment]
Timestore has now been retired and replaced by phpfina. Hopefully you got your issue sorted though.
