### ISSUE TITLE
MQTT input does not handle certain characters in topic names

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#1105]
A topic of `emon/xiaomi/4c:65:a8:d9:59:1a/battery` results in a new input being created with every data item via MQTT.

ref https://community.openenergymonitor.org/t/delete-multiple-input-nodes-100s/9034

**Comment by borpin** [comment]
Merge of #1156 solves the specific case of colons, but a check is required to see if there are other characters that could cause issues.

**Comment by TrystanLea** [comment]
Here's the result with your example above and the latest topic mapping: 

![image](https://user-images.githubusercontent.com/503186/77153342-7f7e3080-6a91-11ea-8d66-33b8185f05a3.png)

Then with: 

    emon/xiaomi/4c,65*a8/d9^59;1a/battery

![image](https://user-images.githubusercontent.com/503186/77153696-22cf4580-6a92-11ea-8187-da8ad09a2e1e.png)

**Comment by borpin** [comment]
Ah Ok great. Cheers.
