### ISSUE TITLE
MQTT topics accepted when invalid

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#1107]
I presume this code was intended to check to see if the MQTT topic was too deep.

It does not work ☹️ (as I discovered accidentally).

Instead, could you simply do a split and count the size of the 2 arrays ($topic and $basetopic) and if difference is greater than 2 reject the message? **Actually can you not just do a string substitution to remove the basetopic string from the topic string?  Then check any array from a split is either 1 or 2 elements long.**

https://github.com/emoncms/emoncms/blob/4e9f8d8c01852962e29d1ccfcde24278e21fa996/scripts/phpmqtt_input.php#L272-L287

[Edit]
And this condition is (I think) redundant as the base topic has been used to subscribe, so it must always exist else there would be no message to process.

https://github.com/emoncms/emoncms/blob/4e9f8d8c01852962e29d1ccfcde24278e21fa996/scripts/phpmqtt_input.php#L289

[Edit3]
https://github.com/emoncms/emoncms/blob/4e9f8d8c01852962e29d1ccfcde24278e21fa996/scripts/phpmqtt_input.php#L291

This line is pointless as there is no message if there is not a topic of $basetopic/$topic

Also need a check that if the input is `$jsoninput` then if a second level is set this is not allowed (need a note in the documentation).

**Comment by TrystanLea** [comment]
Thanks @borpin, will look into it

**Comment by borpin** [comment]
I did a quick and dirty fix in #1106

**Comment by TrystanLea** [comment]
I recently found myself affected by this issue when trying to subscribe to data posted by the OVMS vehicle monitor. It includes topics such as:

    emon/ovms/metric/v/b/soc
    emon/ovms/metric/v/b/c/voltage/dev/max

This would of course not work with the current topic mapping implementation. I think a good mapping approach would be to map:

    emon/ovms/metric/v/b/soc:

to be:

    nodeid: ovms
    input name: metric_v_b_soc

and:

    emon/ovms/metric/v/b/c/voltage/dev/max

to be:

    nodeid: ovms
    input name: metric_v_b_c_voltage_dev_max

I've got an implementation that provides this mapping here:
https://github.com/emoncms/emoncms/compare/emoncms_mqtt_topic_filter

its backwards compatible with the standard topic format e.g emon/emontx/power1

What do you think @borpin @chaveiro

**Comment by TrystanLea** [comment]
I've merged this in, closing for now.
