### ISSUE TITLE
What is the latest version number

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#1114]
I am confused as to what the latest version number is.

![image](https://user-images.githubusercontent.com/1322749/48504480-cffdd200-e83c-11e8-8e9f-cdfb02c52f32.png)

It appears v9.9.1 came after V9.9.2 (note one has a capital V and the other a lowercase v).

The number in `version.txt` is 9.9.4 in the stable branch which is the same as the master branch....

I think this relates to #1104

**Comment by glynhudson** [comment]
It's 9.9.4 https://github.com/emoncms/emoncms/releases
