### ISSUE TITLE
Corrupt Metadata in timestore after import_full.php and restart

### ISSUE THREAD

**Issue by threldor** [emoncms/emoncms#112]
I created a development server (ubuntu 12.04) and followed the guide here to import the data
http://emoncms.org/site/docs/backup

All worked well running both import_inputs.php and also import_full.php
I was able to view my data and all was good.

The problem was after a restart anything timestore related would not work.
In the timestore logs I kept getting
```
20131202-21:58:56:ERROR:tsdb.c(140): Corrupt metadata
20131202-21:58:56:ERROR:http_tsdb.c(306): Invalid node
```
Trying to get the node info using the timestore http api also returned nothing
http://192.168.11.122:8080/nodes/0000000000000047

I stopped the timestore and started in verbose with debugging on and got this log
```
emon@emon-VirtualBox:~/timestore/src$ sudo ./timestore -a -d -v 5
20131202-21:58:53:INFO:logging.c(47): Log level set to 5
20131202-21:58:53:INFO:main.c(195): Changing working directory to: /var/lib/timestore
20131202-21:58:53:TRACE:http_tsdb.c(927): http_tsdb_gen_admin_key()
20131202-21:58:53:INFO:http_tsdb.c(942): Read persistent admin key: BhfVQ2}R/IuF{uj27A+p;i1+LKCJ5tLP
20131202-21:58:53:INFO:main.c(213): Starting web server on port 8080
20131202-21:58:53:TRACE:http.c(394): http_init()
20131202-21:58:53:INFO:http.c(408): HTTP interface started on port 8080
20131202-21:58:56:TRACE:http.c(229): http_handler()
20131202-21:58:56:TRACE:http.c(229): http_handler()
20131202-21:58:56:DEBUG:http.c(265): GET /nodes/0000000000000047
20131202-21:58:56:TRACE:http.c(186): http_find_entity()
20131202-21:58:56:TRACE:http_tsdb.c(294): http_tsdb_get_node()
20131202-21:58:56:TRACE:tsdb.c(122): tsdb_open()
20131202-21:58:56:DEBUG:tsdb.c(132): Node 0000000000000047 metadata path: 0000000000000047.tsdb
20131202-21:58:56:ERROR:tsdb.c(140): Corrupt metadata
20131202-21:58:56:TRACE:tsdb.c(225): tsdb_close()
20131202-21:58:56:ERROR:http_tsdb.c(306): Invalid node
20131202-21:58:56:DEBUG:http.c(305): status = 404
```

Still not much help for me. Any ideas? I also tried deleting all files from /var/lib/timestore and running import_full.php again but this didn't work.

**Comment by Paul-Reed** [comment]
Timestore has now been officially retired and is not supported. I hope Jonathan that you have managed success with the newer feed engines.
