### ISSUE TITLE
error message when updating database

### ISSUE THREAD

**Issue by daniu-de** [emoncms/emoncms#1127]
I am in 9.9.5 (but beta 9.9.6 was the same). When I go to administration - check & update I get an errore message:

ALTER TABLE `device` MODIFY `name` text DEFAULT '';
ALTER TABLE `device` MODIFY `description` text DEFAULT '';

Error: The following error has occured:

BLOB, TEXT, GEOMETRY or JSON column 'name' can't have a default value

(ran the rest of the changes directly on phpmyadmin which worked)

**Comment by Paul-Reed** [comment]
Are all of your other modules up to date, for example - dashboard?

**Comment by borpin** [comment]
There is an update script in https://github.com/emoncms/usefulscripts

That reminds me....

**Comment by daniu-de** [comment]
> 
> 
> Are all of your other modules up to date, for example - dashboard?

that was it ... thanks a lot ...
