### ISSUE TITLE
min max values for a certain time frame?

### ISSUE THREAD

**Issue by daniu-de** [emoncms/emoncms#1128]
Hi

not sure this is the right place for a feature request but I think it would be cool to have some way to get min/max values for a certain timeframe (not sure what would be best: last 24h or a certain date or defineable or whatever

regards

**Comment by borpin** [comment]
Assuming you have installed the 'graph' module, if you click on a feed name (from the feeds page), under the graph that is displayed, is **Show Statistics** - it not very clear (@TrystanLea - it's not just me 😄)

![image](https://user-images.githubusercontent.com/1322749/48843167-37140d00-ed8e-11e8-97ab-5af47cddc04a.png)

Click on that and you get...

![image](https://user-images.githubusercontent.com/1322749/48843125-1ba90200-ed8e-11e8-87ab-b5bb3fa34bc7.png)

**Comment by daniu-de** [comment]
well ... that is not exactly what I want. What I miss is an ability to add the min/max value to a dashboard.

I got a dashboard with a table with all current values of certain sensors. It would be cool to be able to add a min/max value for - let's say the last 24h or the like (a bit like the weather foarcast)

**Comment by borpin** [comment]
Ah OK, you did not mention a dashboard 😄 

The Max/Min values are calculated by the javascript on the page from the data returned from an API call, so I am sure it is possible to generate a custom widget to do what you want, but that is way outside my skill set I am afraid!  You might get more response on the community site.

**Comment by Paul-Reed** [comment]
If you look at your input processes, you'll see that there is an option to select `Max daily value` and `Min daily value` and save that to a feed.
That gets reset at midnight, and you can use that feed to either display on a dashboard 'feedvalue' widget, or use it as an additional setting in one of the widgets - such as the thermometer widget (screenshot below).

Is this the sort of thing you wanted?

![emon](https://user-images.githubusercontent.com/973580/48859707-be757680-edb6-11e8-8546-0c052f1dd28b.png)

![thermo](https://user-images.githubusercontent.com/973580/48859969-74d95b80-edb7-11e8-8948-ab632743535a.PNG)
