### ISSUE TITLE
text on the administration tab that says “Set root file-system temporarily to read-write, (default read-only)”.

### ISSUE THREAD

**Issue by TrystanLea** [emoncms/emoncms#1129]
https://community.openenergymonitor.org/t/bug-read-write-set-root-file-system-temporarily-to-read-write-default-read-only/9235

**Comment by TrystanLea** [comment]
Did we discuss a solution for this one @glynhudson @emrysr, what is the best way to detect the image version and change this entry as applicable?

**Comment by emrysr** [comment]
i'd assume that the command `rpi-rw` and `rpi-ro` commands are now not available on the new image?

we could test for that?

**Comment by pb66** [comment]
I thought that was the best way too. Only show the button if the command or calls exists.
https://community.openenergymonitor.org/t/bug-read-write-set-root-file-system-temporarily-to-read-write-default-read-only/9235/5?u=pb66
