### ISSUE TITLE
Graph bug - fill rescales

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#1131]
If I select fill, it rescales the graph. Only happens for left scale.

Before
![image](https://user-images.githubusercontent.com/1322749/48951529-c9571500-ef36-11e8-92d0-7987a5892e8e.png)

After

![image](https://user-images.githubusercontent.com/1322749/48951547-e1c72f80-ef36-11e8-80dc-2bcbcae9efac.png)

**Comment by TrystanLea** [comment]
Thanks @borpin this is a feature of the flot library, selecting fill always sets the minimum to zero.

**Comment by borpin** [comment]
Hi @TrystanLea, so no way to force it back to the right scale?

**Comment by TrystanLea** [comment]
Not that I'm aware unfortunately.
