### ISSUE TITLE
Feature request - Graph module - Scale both Y Axis

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#1132]
Offer the ability to scale both Y Axis independently when 2 or more sources, using L & R axis are selected.

![image](https://user-images.githubusercontent.com/1322749/48951774-b7c23d00-ef37-11e8-97f8-48bf63ab4562.png)

Also offer a 'reset' option back to auto (what does reload actually do?).

**Comment by LeaseOnLife** [comment]
yes please, is there a way to up-vote this?

**Comment by djh42** [comment]
I would like to see this enhancement too.
> Also offer a 'reset' option back to auto
That would be useful - it seems strange to actually have to type 'auto' in the correct case as well :)
> (what does reload actually do?).
Is that not self-evident? Surely, it reloads the data and displays it according to the current settings?
It's not clear to me why some changes display immediately, whilst others require a reload to see the effect.
