### ISSUE TITLE
incorrect data recorded in feeds

### ISSUE THREAD

**Issue by djh42** [emoncms/emoncms#1137]
In my system I see incorrect data values recorded for power_to_kwh and wh_accumulator type feeds. Specifically they both include retrograde data, which ought to be impossible for those feed types.

See https://community.openenergymonitor.org/t/getting-started-with-emoncms/9356/20 onwards for details. I can attach copies of images here if it's worth while.

**Comment by djh42** [comment]
FWIW, there's even an example of a negative spike shown in the documentation!

See the graph under the text 'Raw data wh accumulator view:' in the page https://guide.openenergymonitor.org/setup/daily-kwh/

Oh, and I now realize that power_to_kwh can have retrograde data, if the underlying power is negative (e.g. when solar is exporting), but (a) that isn't the case for the data sets in my example, and (b) it isn't the case for wh_accumulator on a revenue meter at all.

**Comment by TrystanLea** [comment]
Fix as discussed in testing here: https://github.com/emoncms/emoncms/tree/fix_padding_spikes

**Comment by TrystanLea** [comment]
merged into master
