### ISSUE TITLE
Delta on Virtual Feed

### ISSUE THREAD

**Issue by nicholh** [emoncms/emoncms#1161]
Hi,

I am having a problem whereby when I use a a virtual feed to represent a daily or interval power use the accuracy of the feed is off. I can live with a bit of inaccuracy from rounding etc however when this is is translated into a delta this can sometimes be up to 20% off the source data values. The data also tends to drop off at the list few intervals.

To demonstrate I have created a virtual feed with a single sourve and have show a comparison using intervals and a raw comparison

I am not sure if I have something configured wrong or if this is an issue.

Thanks in advance 

![comparison](https://user-images.githubusercontent.com/17281628/51293123-7e064200-1a61-11e9-86b1-ca19c238e615.PNG)
![interval - delta](https://user-images.githubusercontent.com/17281628/51293125-7e9ed880-1a61-11e9-8041-a470507ddc4d.PNG)
![interval](https://user-images.githubusercontent.com/17281628/51293126-7e9ed880-1a61-11e9-912c-4cf0a64c170d.PNG)
![virtual setup](https://user-images.githubusercontent.com/17281628/51293128-7e9ed880-1a61-11e9-9741-1616f10ea331.PNG)

**Comment by chaveiro** [comment]
What engine is used on that source feed?

**Comment by nicholh** [comment]
Thanks for the reply.

Then engince is PHPFINA and is a Power to kWh type.

The setup is just the standard docker so has redis.

Thanks,
Nichol

**Comment by chaveiro** [comment]
I cant really test this as i only use mysql engine, i suspescy it's related to rounding within the phpfina engine.
Anyway if you can help debug a little more, try this two scenarios:
1 - See if the problem exists with mysql feed.
2 - Deactivate redis and see if the problem still happens on PHPFina and mysql.
