### ISSUE TITLE
Modules list in Admin

### ISSUE THREAD

**Issue by chaveiro** [emoncms/emoncms#1162]
It's difficult to maintain EmonCms and its modules updated.
A nice feature to add is a list on the admin page with:
 - list of available modules available for installation
 - current installed module version
 - newer available versions 
 - button to update / remove / install from git automatically

To whom is familiar with Arduino IDE plugins manager, it's the same feature.

**Comment by borpin** [comment]
Agreed, but I suspect the starting point is to make all modules the same in terms of structure (master and stable) and version file.

There was some discussion around this when the version numbers were introduced into the admin page as some 'Modules' are core and some are optional.

**Comment by chaveiro** [comment]
Or maintain a file with links to the 'stable' releases of the available official modules on the core repo and give the option for the user to enter the module url manually (similar to arduino IDE).
@TrystanLea what do you think?

**Comment by TrystanLea** [comment]
I think this would be a nice feature, it would make sense to use an adaptation of the update scripts somehow to instigate install/update actions. Its not something we will get a chance to work on in the short term given other priorities but Im open to the idea and happy to receive a pull request if anyone wants to give it a go.

**Comment by borpin** [comment]
The starting point is for the difference between core and non-core modules to be made clear and then for the modules with their own repos to consistently follow the master/stable model with a version number and a release tag.

Maintaining the release info could be done in the EmonScripts repo (which also needs a master/stable/version.txt structure.

**Comment by chaveiro** [comment]
Solution here https://github.com/emoncms/emoncms/pull/1732
