### ISSUE TITLE
Should `input/list` be allowed with only read key?

### ISSUE THREAD

**Issue by mattjgalloway** [emoncms/emoncms#1171]
All of the `input/*` endpoints require a write key. I was thinking that reading inputs should only require a read key. Would that make sense?

Reason I'd like this is I'd quite like to be able to put inputs into the iOS app so that it becomes a more full-featured emoncms app. But right now I'd have to ask people to use the write key if they want to be able to see inputs. Worst case is I allow people to add their write key if they want to see the inputs. But I don't see why we can't support reading inputs with a read key.

**Comment by TrystanLea** [comment]
Hello @mattjgalloway, you are right, I cant quite remember now why it was all set to write. I've fixed it to allow read access to read api end points: https://github.com/emoncms/emoncms/commit/fc4a4d11ca77e3efc7f7df9ee857cc01f07ebb2a
