### ISSUE TITLE
Remove hardcoded 8928 datapoint limit

### ISSUE THREAD

**Issue by pb66** [emoncms/emoncms#1184]
see https://community.openenergymonitor.org/t/feature-request-setting-for-data-point-limit/9922?u=pb66
https://community.openenergymonitor.org/t/request-datapoint-limit-until-8928-points/633/4?u=pb66
and  https://openenergymonitor.org/forum-archive/node/12133.html)

Can we break this setting out into the settings.php?

**Comment by TrystanLea** [comment]
good idea, happy for this to be a setting, a user can assess the performance implication on their system
