### ISSUE TITLE
Confusing Cancel button on delete feed

### ISSUE THREAD

**Issue by ghost** [emoncms/emoncms#1190]
May i suggest that line 117 in /feed/Views/feedlist_view.php be changed from 

?php echo _('Cancel'); ?>

to 

?php echo _('Close'); ?>

The reason being that the button does not in fact cancel anything you may have done. It just closes the dialog box.

Thanks
Dafydd

**Comment by TrystanLea** [comment]
I think this has been changed and is now showing as close
