### ISSUE TITLE
Sidebar menu concept

### ISSUE THREAD

**Issue by TrystanLea** [emoncms/emoncms#1194]
Several modules now use a dark sidebar for navigation within module features. E.g:

![heatpump](https://user-images.githubusercontent.com/503186/52274644-329ad180-2945-11e9-8d11-5dc1e27a9611.png)

The sidebar makes good use of available screen space on large screen devices whilst also working well on mobile - overlaying the page content.

The sidemenu could be extended to include the full emoncms menu system, for easier mobile navigation and improved appearance, it might look something like this: 

![20190205_125124](https://user-images.githubusercontent.com/503186/52274606-1ac34d80-2945-11e9-9167-0de8140241ec.jpg)

I like the idea of having a "Quick Links" section that includes a series of user bookmarked locations. I would have the my heatpump and my electric app, followed by the openevse and heatpump demandshaper control pages. 

The settings section would include: inputs, feeds, emonhub, device setup, admin and my account. 

Apps & Dashboard menu's could be accessible via the top icons

**Comment by glynhudson** [comment]
Implemented in https://github.com/emoncms/emoncms/pull/1240
