### ISSUE TITLE
PHP

### ISSUE THREAD

**Issue by glynhudson** [emoncms/emoncms#1208]
PHPTIMESERIES data Feeds do not have a regular update time (unlike PHPFINA) therefore the last updated color should be removed since the color cannot be determined since they could be updated at any random interval. 

![selection_087](https://user-images.githubusercontent.com/758844/52969452-58de5980-33a8-11e9-9532-8567596a2fe1.jpg)

**Comment by djh42** [comment]
Is this really an issue? I'd say the arbitrary assignment of colours to times is perhaps more of an issue. I have one node that has two PHPFINA feeds that are refreshed every ten minutes. So the node and feeds spend most of their life with an 'orange' status despite working correctly. Surely it would make more sense if the time base of the feeds were used when determining the status?
