### ISSUE TITLE
error chaging the graph color

### ISSUE THREAD

**Issue by danpadure** [emoncms/emoncms#1228]
I'm getting an error trying to change colors:
emoncms error:
message: uncaught typeerror: cannot read property 'lines' of undefined
url:ip/emoncms/Modules/graph/graph.js?v=1
line: 756
column: 25

9.9.8-4-gd0db7a57

![image](https://user-images.githubusercontent.com/48951409/55281200-a059ed00-5339-11e9-815d-9f0879c69844.png)

**Comment by danpadure** [comment]
oh, this happens when I click on the color in the top left part of the graph

**Comment by njfaria** [comment]
with some debug info
![error](https://user-images.githubusercontent.com/21275682/55683646-e6b2db80-5939-11e9-9961-991fb89f753b.png)

**Comment by glynhudson** [comment]
Thanks, we're able to replicate. Will get this fixed very soon

**Comment by emrysr** [comment]
You should change the feed's colour from the list below the chart no in the chart legend. I will fix the js error when the colour is clicked.

This could be added as a feature. Please open an issue in the graph module repo to discuss this.
https://github.com/emoncms/graph
