### ISSUE TITLE
Sidebar dev: menu organising 

### ISSUE THREAD

**Issue by glynhudson** [emoncms/emoncms#1231]
1. The title of the sidebar menu `Setup` should be changed to `Emoncms`

2. To avoid cluttering the sidebar with system config menu items a new `System` menu item should be created with a cog icon. This `system` menu should contain: 
  - Admin
  - WiFi
  - Backup 
  - Find local devices 

3. Remove `Account` menu item from the sidebar and remove the popup tray at the bottom of the sidebar since the `Account` and `logout` functions can be accessed via the user profile icon.  
 
These changes have been discussed with @TrystanLea and first proposed by @borpin 

See forum discussion: https://community.openenergymonitor.org/t/beta-new-emoncms-sidebar-navigation-layout-feedback-request/10435/33?u=glyn.hudson

**Comment by emrysr** [comment]
I like all the above. good thinking. i'll work on them tomorrow

**Comment by borpin** [comment]
To `system` I'd add
* emonhub
* Device setup

**Comment by emrysr** [comment]
![delwedd](https://user-images.githubusercontent.com/1466013/56962092-9e0fcc00-6b4d-11e9-93e6-7f1640c95714.png)

This is the current menu layout I've set to match the above. Each menu item's position can be controlled by the module's `*_menu.php` file

**Comment by emrysr** [comment]
these are the items in the user dropdown:
![delwedd](https://user-images.githubusercontent.com/1466013/56962241-f941be80-6b4d-11e9-8a17-4cea5a9417a9.png)

**Comment by borpin** [comment]
What is groups on the Sidebar?  Is this user management?

If I click on 'Administration', what happens to the sidebar?

**Comment by borpin** [comment]
Personally, I think the settings should be part of the sidebar so that all those items listed, simply appear in the sidebar when the cog icon is clicked.

You could then have a sub menu under admin for 'Users', 'Update', 'Logger', 'Server Info' & 'Client Infor` which just move you to that part of the page.

I am presuming clicking on Backup takes me into a backup sidebar still? A very confused UI if it does.

**Comment by glynhudson** [comment]
>What is groups on the Sidebar? Is this user management?

It's the groups module https://github.com/emoncms/group

>If I click on 'Administration', what happens to the sidebar?
 
It stays there

![](https://community.openenergymonitor.org/uploads/default/original/2X/6/66b708076dc6b561c99ee26b0f79028918bd8f1f.png)

>I am presuming clicking on Backup takes me into a backup sidebar still? A very confused UI if it does.

No, backup has tabs to switch between import/export. Notice the 'cog' is highlighted to indicate that backup is a system/admin module 

![Screenshot 2019-04-30 at 17 35 27](https://user-images.githubusercontent.com/758844/56977980-606f6b00-6b6e-11e9-8fe7-1fc9d686ed20.png)

There are lots of ways to structure the menu. Having been testing and using the new sidebar extensively for the past few months I think it's a big improvement. It can always be tweaked over time. Personally I like the segregation of having the system menu on the cog and main menu on the left hand side. It's very similar to the Discourse forum layout

![Screenshot 2019-04-30 at 17 38 46](https://user-images.githubusercontent.com/758844/56978177-dbd11c80-6b6e-11e9-83b7-6c755713b2a6.png)
![Screenshot 2019-04-30 at 17 38 40](https://user-images.githubusercontent.com/758844/56978179-dc69b300-6b6e-11e9-842e-6363234257e4.png)
