### ISSUE TITLE
Error when trying to access Multigraph Advance options 

### ISSUE THREAD

**Issue by glynhudson** [emoncms/emoncms#1234]
Step to re-produce: Visulisation > Multigraph > New Multigraph > Advanced

I'm currently running side-bar branch, I'm unable to easily switch back to master to test if this issue was previously present

![Screenshot 2019-04-08 at 01 15 19](https://user-images.githubusercontent.com/758844/55692030-ecd9a400-599b-11e9-9301-fd39d3a4168d.png)

![Emoncms - vis list](https://user-images.githubusercontent.com/758844/55692691-3e852d00-59a2-11e9-94f8-f988ca811002.png)

**Comment by borpin** [comment]
I get the same on a vanilla EmonPi.

**Comment by glynhudson** [comment]
fixed
