### ISSUE TITLE
Sidebar tab navigation shotcuts 

### ISSUE THREAD

**Issue by glynhudson** [emoncms/emoncms#1245]
It would be useful to be able to navigate the new sidebar using tab navigation. 

In my option tabs should first traverse the left side bar, bookmarks, bookmark star, then the system cog menu 

In Emoncms V9 it was possible to tab though the top bar then the side bar. I found this quite useful

**Comment by glynhudson** [comment]
That's great, the tabbed nav works exactly works perfectly. This is exactly what I had in mind. 

However, after checking out this version the System cog menu now overflows the side of the screen, see:

![Screenshot 2019-05-15 at 15 26 38](https://user-images.githubusercontent.com/758844/57783422-fdf99b80-7725-11e9-86d3-6b2afa7dd3be.png)
![Screenshot 2019-05-15 at 15 26 23](https://user-images.githubusercontent.com/758844/57783423-fe923200-7725-11e9-957b-6b5c955fcebc.png)

**Comment by glynhudson** [comment]
Same issue with the Profile menu

**Comment by emrysr** [comment]
ah! well spotted.

**Comment by emrysr** [comment]
fixed in the pull request - https://github.com/emoncms/emoncms/pull/1266

![delwedd](https://user-images.githubusercontent.com/1466013/57804383-77a77e80-7752-11e9-9e5f-36a9a8f4c1b6.png)
