### ISSUE TITLE
Readme Module installation- should use stable branch

### ISSUE THREAD

**Issue by whatsupskip** [emoncms/emoncms#1256]
Currently the documentation says

> To install Apps, cd to the Modules folder, and git clone 'apps':
> 
> cd /var/www/emoncms/Modules && git clone https://github.com/emoncms/app.git

However this has caused problems with the version 9.9.9 and for [others previously](https://community.openenergymonitor.org/t/problem-with-the-basic-dashboard-data/8503/5).

The documentation should be changed to 
> To install Apps, cd to the Modules folder, and git clone 'apps':
> 
> cd /var/www/emoncms/Modules && git clone -b stable --single-branch https://github.com/emoncms/dashboard.git

**Comment by glynhudson** [comment]
Thanks, good idea, docs have been amended.

**Comment by whatsupskip** [comment]
Great.
