### ISSUE TITLE
Time offsets in API insufficiently documented 

### ISSUE THREAD

**Issue by nmgeek** [emoncms/emoncms#126]
Three things missing from the API doc relative to time offsets:

1. Units are seconds? Must be ints or are floats allowed?
2. What are they relative to? Can you supply absolute times in unix epoch?
3.  Are negative offsets allowed or is the minus sign implied?

I could write this documentation but it might be better if the designer of the API writes it in case the implementation has bugs.
-Glenn

**Comment by chaveiro** [comment]
should be ok as per #118
