### ISSUE TITLE
feed timed out session template

### ISSUE THREAD

**Issue by emrysr** [emoncms/emoncms#1262]
currently if the session times out on the feed list this error is shown:

![delwedd](https://user-images.githubusercontent.com/1466013/57514687-ecb92500-7308-11e9-9905-47411747e67f.png)

would be good to redirect or notify user with a link to the login page.

**Comment by glynhudson** [comment]
Good idea

**Comment by emrysr** [comment]
The issue here is that the requested route didn't return a value so the above error is shown.

I'll alter the feed controller to redirect correctly.
