### ISSUE TITLE
using exit() fails travis tests

### ISSUE THREAD

**Issue by emrysr** [emoncms/emoncms#1270]
while testing another issue i'd come across endopoints that redirect but dont end the application so the output is different to what is expected
https://github.com/emoncms/emoncms/blob/85ec9cecc8ec266688916221131ccd5cafd5b993/Modules/admin/admin_controller.php#L393

there might be others...

you *should* run the `exit()` function to exit the script before the browser is redirected. however when this function is used I get this error in the CI test. there must be a better way to do it that still passes the tests
 
> An exit-expression within regular code is untestable and therefore it should be avoided. Consider to move the exit-expression into some kind of startup script where an error/exception code is returned to the calling environment.

stackoverflow discussion:
https://stackoverflow.com/questions/3553698/php-should-i-call-exit-after-calling-location-header

**Comment by TrystanLea** [comment]
Is this issue resolved @emrysr ?
