### ISSUE TITLE
Make creation of MQTT client more robust

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#1290]
The creation of the mqtt client is not robust.

https://github.com/emoncms/emoncms/blob/9bdad523a2a2a2944520f198a9aebca7763334a4/scripts/services/emoncms_mqtt/emoncms_mqtt.php#L113

Something like this code should be used here to create the mqtt client to make it more robust
https://github.com/emoncms/emoncms/blob/90955023fd1fbfc9f03eed24cbcd2fd78a3138af/Modules/process/process_processlist.php#L48-L58

Probably needs a try catch as well.

**Comment by TrystanLea** [comment]
Noted, See: https://github.com/emoncms/emoncms/issues/1295
