### ISSUE TITLE
Powered by bar scrolls with page

### ISSUE THREAD

**Issue by MrHappy** [emoncms/emoncms#1292]
The 'Powered by bar' scrolls with the page, thus hovering over my graphs instead of staying on the bottom of the screen.
This happens as well in Firefox as in Edge.
I'm using EmonCMS 10.0.2.

**Comment by glynhudson** [comment]
Thanks for reporting. Does this happen after clearing browser cache or using private browsing window? Do you see the same effect on Chrome. Please post a screenshot if possible. I cannot yet replicate the issue. We will try and investigate

**Comment by MrHappy** [comment]
![Screenshot_20190525-205729__01](https://user-images.githubusercontent.com/686360/58378682-22603e00-7f98-11e9-8b29-03fbe1624b0a.jpg)
A screemshot from the page on my phone (Chrome), also tried it in private-tab with same result...

**Comment by glynhudson** [comment]
@MrHappy fix has been merged into Master branch. Please could you test and confirm the issue has been fixed for you by checking out the Master branch and pulling in the latest changes

**Comment by MrHappy** [comment]
Added the master-branch to a subdirectory under my stable-installation and it works fine.
