### ISSUE TITLE
406 Not Acceptable. Route not found

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#1298]
admin -> users -> click on id

Gives “406 Not Acceptable. Route not found”

<details><summary>Server Information</summary>

# Server Information
## Services
 
- **emonhub** :- **Active** Running
- **emoncms_mqtt** :- **Active** Running
- **feedwriter** :- **Active** Running - sleep 60s 10 feed points pending write
- **service-runner** :- **Active** Running
- **emonPiLCD** :- **Active** Running
- **redis-server** :- **Active** Running
- **mosquitto** :- **Active** Running

## Emoncms
 
- **Version** :- low-write 10.0.2
- **Modules** :- Administration | App v2.0.1 | Backup v2.0.0 | EmonHub Config v2.0.2 | Dashboard v2.0.1 | Device v2.0.0 | EventProcesses | Feed | Graph v2.0.1 | Input | Postprocess v2.0.0 | CoreProcess | Schedule | Network Setup v1.0.0 | sync | Time | User | Visualisation | WiFi v2.0.0
- **Git** :- 
     - **URL** :- https://github.com/emoncms/emoncms.git
     - **Branch** :- * stable
     - **Describe** :- 10.0.2-4-g9e7c6804

## Server
 
- **OS** :- Linux 4.14.71-v7+
- **Host** :- emonpi | emonpi | (192.168.7.243)
- **Date** :- 2019-06-01 10:30:45 BST
- **Uptime** :- 10:30:45 up 4 days, 20:05,  1 user,  load average: 0.14, 0.10, 0.09

## Memory
 
- **RAM** :- Used: 17.77%
    - **Total** :- 976.74 MB
     - **Used** :- 173.61 MB
     - **Free** :- 803.13 MB
- **Swap** :- Used: 0.00%
    - **Total** :- 100 MB
     - **Used** :- 0 B
     - **Free** :- 100 MB

## Disk
 
- **/** :- Used: 40.34%
    - **Total** :- 3.81 GB
     - **Used** :- 1.54 GB
     - **Free** :- 2.1 GB
- **/boot** :- Used: 51.69%
    - **Total** :- 42.52 MB
     - **Used** :- 21.98 MB
     - **Free** :- 20.54 MB
- **/home/pi/data** :- Used: 5.50%
    - **Total** :- 3.21 GB
     - **Used** :- 180.78 MB
     - **Free** :- 2.87 GB

## HTTP
 
- **Server** :- Apache/2.4.25 (Raspbian) HTTP/1.1 CGI/1.1 80

## MySQL
 
- **Version** :- 5.5.5-10.1.23-MariaDB-9+deb9u1
- **Host** :- localhost:6379 (127.0.0.1)
- **Date** :- 2019-06-01 10:30:45 (UTC 01:00‌​)
- **Stats** :- Uptime: 417935  Threads: 2  Questions: 32382  Slow queries: 0  Opens: 24  Flush tables: 1  Open tables: 18  Queries per second avg: 0.077

## Redis
 
- **Version** :- 3.2.6
- **Host** :- localhost:6379
- **Size** :- 106 keys (782.26K)
- **Uptime** :- 4 days

## MQTT Server
 
- **Version** :- Mosquitto 1.4.10
- **Host** :- localhost:1883 (127.0.0.1)

## PHP
 
- **Version** :- 7.0.30-0+deb9u1 (Zend Version 3.0.0)
- **Modules** :- apache2handler | calendar v7.0.30-0+deb9u1 | Core v7.0.30-0+deb9u1 | ctype v7.0.30-0+deb9u1 | curl v7.0.30-0+deb9u1 | date v7.0.30-0+deb9u1 | dom v20031129 | exif v7.0.30-0+deb9u1 | fileinfo v1.0.5 | filter v7.0.30-0+deb9u1 | ftp v7.0.30-0+deb9u1 | gd v7.0.30-0+deb9u1 | gettext v7.0.30-0+deb9u1 | hash v1.0 | iconv v7.0.30-0+deb9u1 | igbinary v2.0.1 | json v1.4.0 | libxml v7.0.30-0+deb9u1 | mbstring v7.0.30-0+deb9u1 | mcrypt v7.0.30-0+deb9u1 | mosquitto v0.4.0 | mysqli v7.0.30-0+deb9u1 | mysqlnd vmysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $ | openssl v7.0.30-0+deb9u1 | pcre v7.0.30-0+deb9u1 | PDO v7.0.30-0+deb9u1 | pdo_mysql v7.0.30-0+deb9u1 | Phar v2.0.2 | posix v7.0.30-0+deb9u1 | readline v7.0.30-0+deb9u1 | redis v4.1.1 | Reflection v7.0.30-0+deb9u1 | session v7.0.30-0+deb9u1 | shmop v7.0.30-0+deb9u1 | SimpleXML v7.0.30-0+deb9u1 | sockets v7.0.30-0+deb9u1 | SPL v7.0.30-0+deb9u1 | standard v7.0.30-0+deb9u1 | sysvmsg v7.0.30-0+deb9u1 | sysvsem v7.0.30-0+deb9u1 | sysvshm v7.0.30-0+deb9u1 | tokenizer v7.0.30-0+deb9u1 | wddx v7.0.30-0+deb9u1 | xml v7.0.30-0+deb9u1 | xmlreader v7.0.30-0+deb9u1 | xmlwriter v7.0.30-0+deb9u1 | xsl v7.0.30-0+deb9u1 | Zend OPcache v7.0.30-0+deb9u1 | zlib v7.0.30-0+deb9u1

## Pi
 
- **Model** :- Raspberry Pi 3 Model B+ Rev 1.3 - 1 GB (Sony UK)
- **SoC** :- Broadcom BCM2835
- **Serial num.** :- 71604C19
- **Temperature** :- 49.39°C - 49.4°C
- **emonpiRelease** :- emonSD-30Oct18
- **File-system** :- read-write
</details>

<details><summary>Client Information</summary>

# Client Information
## HTTP
 
- **Browser** :- Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.88 Safari/537.36 Vivaldi/2.4.1488.36
- **Language** :- en-US,en;q=0.9

## Window
 
- **Size** :- 1414 x 833

## Screen
 
- **Resolution** :- 1920 x 1080
</details>

**Comment by emrysr** [comment]
first look.. points to fix:

User forwarded from `admin/setuser.json` to `user/view` when user in the list is clicked..

https://github.com/emoncms/emoncms/blob/e492984b6f3ba33f948da428e83872822591a4b1/Modules/user/user_controller.php#L48

The user controller must not be responding with a template for some reason... That is the reason for the 406 error message.

Will take a look tomorrow to fix the issue
