### ISSUE TITLE
Battery widget failed to excecute addColorStop

### ISSUE THREAD

**Issue by njfaria** [emoncms/emoncms#1306]
make new dashboard-> insert battery Widget -> choose feed ( change to one of your feeds )
gives the error.
![error](https://user-images.githubusercontent.com/21275682/59159957-a7834100-8ac8-11e9-9321-2bcb9d087f9f.png)

<details><summary>Server Information</summary>

# Server Information
## Services
 
- **emoncms_mqtt** :- **Active** Running
- **feedwriter** :- **Active** Running - sleep 60s 0 feed points pending write
- **service-runner** :- **Active** Running
- **redis-server** :- **Active** Running
- **mosquitto** :- **Active** Running

## Emoncms
 
- **Version** :- low-write 10.0.2
- **Modules** :- Administration | App v2.0.1 | Backup v2.0.0 | Dashboard v2.0.1 | Device v2.0.0 | EventProcesses | Feed | Graph v2.0.1 | Input | EmonHub Config v2.0.2 | DemandShaper v1.0.0 | notusedsync | WiFi v2.0.0 | Postprocess v2.0.0 | CoreProcess | Schedule | Time | User | Visualisation
- **Git** :- 
     - **URL** :- https://github.com/emoncms/emoncms.git
     - **Branch** :- * master
     - **Describe** :- 10.0.2-21-g4013c27a

## Server
 
- **OS** :- Linux 4.19.42-v7+
- **Host** :- solpiplog | solpiplog | (192.168.42.112)
- **Date** :- 2019-06-09 15:07:09 BST
- **Uptime** :- 15:07:09 up  1:32,  1 user,  load average: 0.01, 0.04, 0.04

## Memory
 
- **RAM** :- Used: 26.80%
    - **Total** :- 926.08 MB
     - **Used** :- 248.16 MB
     - **Free** :- 677.91 MB
- **Swap** :- Used: 0.00%
    - **Total** :- 100 MB
     - **Used** :- 0 B
     - **Free** :- 100 MB

## Disk
 
- **/** :- Used: 21.89%
    - **Total** :- 14.15 GB
     - **Used** :- 3.1 GB
     - **Free** :- 10.43 GB
- **/boot** :- Used: 52.47%
    - **Total** :- 42.22 MB
     - **Used** :- 22.15 MB
     - **Free** :- 20.07 MB
- **/var/log** :- Used: 3.75%
    - **Total** :- 50 MB
     - **Used** :- 1.88 MB
     - **Free** :- 48.13 MB

## HTTP
 
- **Server** :- Apache/2.4.25 (Raspbian) HTTP/1.1 CGI/1.1 80

## MySQL
 
- **Version** :- 5.5.5-10.1.38-MariaDB-0+deb9u1
- **Host** :- localhost:6379 (127.0.0.1)
- **Date** :- 2019-06-09 15:07:09 (UTC 01:00‌​)
- **Stats** :- Uptime: 5518  Threads: 4  Questions: 4761  Slow queries: 0  Opens: 35  Flush tables: 1  Open tables: 23  Queries per second avg: 0.862

## Redis
 
- **Version** :- 3.2.6
- **Host** :- localhost:6379
- **Size** :- 59 keys (734.45K)
- **Uptime** :- 0 days

## MQTT Server
 
- **Version** :- Mosquitto 1.4.10
- **Host** :- localhost:1883 (127.0.0.1)

## PHP
 
- **Version** :- 7.0.33-0+deb9u3 (Zend Version 3.0.0)
- **Modules** :- apache2handler | calendar v7.0.33-0+deb9u3 | Core v7.0.33-0+deb9u3 | ctype v7.0.33-0+deb9u3 | curl v7.0.33-0+deb9u3 | date v7.0.33-0+deb9u3 | dom v20031129 | exif v7.0.33-0+deb9u3 | fileinfo v1.0.5 | filter v7.0.33-0+deb9u3 | ftp v7.0.33-0+deb9u3 | gd v7.0.33-0+deb9u3 | gettext v7.0.33-0+deb9u3 | hash v1.0 | iconv v7.0.33-0+deb9u3 | json v1.4.0 | libxml v7.0.33-0+deb9u3 | mbstring v7.0.33-0+deb9u3 | mcrypt v7.0.33-0+deb9u3 | mosquitto v0.4.0 | mysqli v7.0.33-0+deb9u3 | mysqlnd vmysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $ | openssl v7.0.33-0+deb9u3 | pcre v7.0.33-0+deb9u3 | PDO v7.0.33-0+deb9u3 | pdo_mysql v7.0.33-0+deb9u3 | Phar v2.0.2 | posix v7.0.33-0+deb9u3 | readline v7.0.33-0+deb9u3 | redis v4.3.0 | Reflection v7.0.33-0+deb9u3 | session v7.0.33-0+deb9u3 | shmop v7.0.33-0+deb9u3 | SimpleXML v7.0.33-0+deb9u3 | sockets v7.0.33-0+deb9u3 | SPL v7.0.33-0+deb9u3 | standard v7.0.33-0+deb9u3 | sysvmsg v7.0.33-0+deb9u3 | sysvsem v7.0.33-0+deb9u3 | sysvshm v7.0.33-0+deb9u3 | tokenizer v7.0.33-0+deb9u3 | wddx v7.0.33-0+deb9u3 | xml v7.0.33-0+deb9u3 | xmlreader v7.0.33-0+deb9u3 | xmlwriter v7.0.33-0+deb9u3 | xsl v7.0.33-0+deb9u3 | Zend OPcache v7.0.33-0+deb9u3 | zlib v7.0.33-0+deb9u3

## Pi
 
- **Model** :- Raspberry Pi 3 Model B+ Rev 1.3 - 1 GB (Sony UK)
- **SoC** :- Broadcom BCM2835
- **Serial num.** :- E8705863
- **Temperature** :- 41.86°C - 42.4°C
- **emonpiRelease** :- emonSD-30Oct18
- **File-system** :- read-write
</details>

<details><summary>Client Information</summary>

# Client Information
## HTTP
 
- **Browser** :- Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36
- **Language** :- pt-PT,pt;q=0.9,de-DE;q=0.8,de;q=0.7,en-GB;q=0.6,en;q=0.5,en-US;q=0.4

## Window
 
- **Size** :- 1838 x 950

## Screen
 
- **Resolution** :- 1920 x 1080
</details>

**Comment by emrysr** [comment]
issue is in dashboard repo (`Views/js/render.js`) . creating new issue there to track the changes.

`curve_value()` not returning expected value.
