### ISSUE TITLE
New user login url is incorrect /user/feed/list, gives blank page

### ISSUE THREAD

**Issue by TrystanLea** [emoncms/emoncms#1327]
![image](https://user-images.githubusercontent.com/503186/60023478-c91a2600-968d-11e9-92e8-b7c5ba0a40d0.png)

**Comment by emrysr** [comment]
can't replicate this issue. 

- registered new user
- arrived at emoncms/feed/list

@TrystanLea  can you still re-produce this issue?

**Comment by TrystanLea** [comment]
Seems to be working now, thanks
