### ISSUE TITLE
graph module legend placement

### ISSUE THREAD

**Issue by danbates2** [emoncms/emoncms#1332]
hi guys,

an easy one i hope.

the legend doesn't respond to the width of the y-axis text, and ends up in a funny location.

![Screen Shot 2019-06-26 at 20 22 08](https://user-images.githubusercontent.com/5250782/60290780-6afd7500-9911-11e9-84a5-1fc0ee8c5d12.png)

**Comment by glynhudson** [comment]
This issue should be on the graph module repo: https://github.com/emoncms/graph

I can't replicate using the latest graph module V2.0.1
