### ISSUE TITLE
changing window width brings left-side menu out

### ISSUE THREAD

**Issue by danbates2** [emoncms/emoncms#1341]
when changing window width the left hand side menu slides out.

**Comment by TrystanLea** [comment]
Hey Dan, this is intended behaviour, when do you find it an issue?

**Comment by chaveiro** [comment]
Generating an action (windows resize) that is not related in anything to a menu appearing seemed to me like  a bug.
If it's be design than it's a nuisance. 
You know what i mean if you use a 50" 4k monitor where you adjust window sizes regulary.

**Comment by danbates2** [comment]
@TrystanLea bump :)

**Comment by TrystanLea** [comment]
I dont agree that its a bug but one option could be to make a distinction that when the user clicks on the sidebar top level icon, which hides the sidebar that it then does not reopen when the window is expanded?

**Comment by danbates2** [comment]
That'd be great!

**Comment by TrystanLea** [comment]
Linking this issue to https://github.com/emoncms/emoncms/issues/1348 as very similar

**Comment by TrystanLea** [comment]
This is now fixed in latest version
