### ISSUE TITLE
Side menu should overlay (dont resize background)

### ISSUE THREAD

**Issue by chaveiro** [emoncms/emoncms#1348]
I think it would be better for the side menu to be overlayed on top of the bakground so you dont get tables/dashboards resized when you open a menu. 
Or at least add an option on the menu itself to pin it if the user wants, but by defalult make it overlay on top.

**Comment by TrystanLea** [comment]
The intended design is to show both when the screen size is wide enough. When the screen size is small it automatically overlays rather than fitting both.

**Comment by TrystanLea** [comment]
Similar to #1341, linking to keep discussion in one place.

**Comment by danbates2** [comment]
I agree on the overlay idea actually.
To be able to pin the side bar with a little pin icon at the top would be possible.
