### ISSUE TITLE
Feeds table lost information

### ISSUE THREAD

**Issue by chaveiro** [emoncms/emoncms#1349]
Important details used for adminitration of feeds disapeared on V10.
If the less usefull elements disapeared only when the screen size is small i would understand but that does not seem the case.

See the image bellow. 
Left side is v10, right side  v9.

The problems are signaled by the arrows.
1 - Yellow: Here did the virtual feeds processlist  preview went ?
2 - Red: How the check datatype?
3 - Orange: How to bulk export an entire feed TAG ?

![image](https://user-images.githubusercontent.com/4527135/60742432-43d42280-9f65-11e9-99c1-8977de53a7a7.png)

**Comment by TrystanLea** [comment]
Noted, the virtual feed processlist and bulk export was accidentally missed out, I don’t think the datatype is that useful, but we could add it into the hover over tooltip.

**Comment by borpin** [comment]
How about the trim function that I think was accessed via the cog?

**Comment by TrystanLea** [comment]
Sorry, the bulk export is present, you need to click on the tick box selectors on the left hand side to select the feeds that you wish to export. This also works for deleting and timing multiple feeds.

The process list is not shown, but creating and adding processes to virtual feeds does work.

**Comment by chaveiro** [comment]
Still on the topic of bulk export, how difficult is to add a quick way to select/deselect a full tag of feeds?
Remember it was a request by my time of developing emoncms.
Say you want to export manually some devices and each device have 15 feeds. 
On v9 it's a 2 clicks step, on v10 it is a 16 clicks step.
And to export another device, a 31 clicks step to deselect previous and select the next device...

**Comment by TrystanLea** [comment]
Hello @chaveiro, @emrysr has been working on a feature that allows for this 2 click approach for the inputs interface, currently not merged, we will work towards implementing the same in the feeds list https://github.com/emoncms/emoncms/pull/1360
