### ISSUE TITLE
Is it possible to move svg icons out of theme.php?

### ISSUE THREAD

**Issue by TrystanLea** [emoncms/emoncms#1357]
It would be nice to keep these separate so that the code is a bit cleaner, what would the best way be to do this @emrysr?

**Comment by emrysr** [comment]
Yes, you can add icons per module... The demand shaper does it here:
https://github.com/emoncms/demandshaper/blob/master/demandshaper-module/demandshaper_menu.php#L41

**Comment by TrystanLea** [comment]
Would it be possible to move the existing code into some kind of include? Some of the icons may be useful to be reused by several modules?

**Comment by TrystanLea** [comment]
sorted:

https://github.com/emoncms/emoncms/commit/f965ce48d36403bf8ce106953e59b736302f6f7f
https://github.com/emoncms/emoncms/commit/bc06fc0433fb59b5470d5377d79de3547523f7e9
