### ISSUE TITLE
Incorrect RPi SoC displayed on the admin p[age

### ISSUE THREAD

**Issue by pb66** [emoncms/emoncms#1364]
From the Pi docs

> Note: As of the 4.9 kernel, all Pis report BCM2835, even those with BCM2836 and BCM2837 processors. You should not use this string to detect the processor.

From a Pi 4 which has a Broadcom BCM2711B0

```
pi@raspberrypi:~ $ cat /proc/cpuinfo | egrep 'Revision|Hardware'
Hardware        : BCM2835
Revision        : c03111
```

Perhaps as a temp measure the [SoC line in admin_main_view.php](https://github.com/emoncms/emoncms/blob/10.1.2/Modules/admin/admin_main_view.php#L379) should be commented out? It's better to not offer info than to provide incorrect info.

In the longer term perhaps the processor model should be in the models.json file since the earliest Pi models cannot return the SoC via the basic "incremental" version code and computing the SoC from the later "smart" version code isn't really needed as the current "lookup" method works well for the "Model" string. 

[recent example from the OEM forum
](https://community.openenergymonitor.org/t/multigraphs-stopped-updating-at-3am-feeds-still-updating-now-working-again/11415/3?u=pb66)

![image](https://user-images.githubusercontent.com/5606042/61321949-87038080-a804-11e9-86ea-6020283af107.png)

RPi 3B+'s have BCM2837B0 processors not BCM2835.

besides (IMO) the SoC isn't that useful since the SoC doesn't change unless the model changes so the model indicates the SoC, what might be useful is to have the RAM on a separate line, that changes eg Pi B 256/512MB and/or Pi 4 1/2/4GB, whether you are running a 512MB Zero or a 1GB Pi2B might well effect decisions such as how much ram to allocate to log2ram and/or emonhub buffer sizes and/or feedwriter interval etc

**Comment by glynhudson** [comment]
>Perhaps as a temp measure the SoC line in admin_main_view.php should be commented out?

Agree, showing SoC info is not very important or useful. Let's remove it. Cc. @emrysr 

Showing the Pi model is useful e.g 3B+. This is working correctly on the Pi4 .
