### ISSUE TITLE
Fresh install 10.1.2, error when adding "new device"

### ISSUE THREAD

**Issue by teslabn** [emoncms/emoncms#1373]
Hi,
I installed emoncms on clean raspberry pi 3.
Now I have error message when I want to add new device.

EmonCMS Error
-----------------
Message: Uncaught ReferenceError: device_dialog is not defined
Route: Modules/input/Views/input_view.js?v=1
Line: 322
Column: 42

It will be good for you as solve bug, and for me to go step forward :)
Project is fantastic!
Best regards!

**Comment by teslabn** [comment]
![image](https://user-images.githubusercontent.com/53170544/61637277-856c0980-ac97-11e9-87ae-ceb1ccfef896.png)
If you need more info about my instance, feel free to ask me. :)

**Comment by MaffooClock** [comment]
I had the same problem.  After I installed the [Device module](https://github.com/emoncms/device), the error went away.

**Comment by TrystanLea** [comment]
This issue should be fixed in the latest version, do you know which version and branch you are running?

**Comment by teslabn** [comment]
@MaffooClock You are right.. When I installed Device module, I got full functionality. Thank you!
@TrystanLea Nice, my version is 10.1.2 (same on footer at web app, and admin view). Branch is master.

Thank you!
