### ISSUE TITLE
Non well formed numeric value encountered in emoncms/Lib/misc/nav_functions.php on line 366

### ISSUE THREAD

**Issue by tgmaxx** [emoncms/emoncms#1399]
Setup a new emoncms system on Pi3 wih Buster and PHP 7.3. Getting the following error when opening a dashboard:

Notice: A non well formed numeric value encountered in /var/www/html/emoncms/Lib/misc/nav_functions.php on line 366

**Comment by alexandrecuer** [comment]
I've got the same setup and I cannot reproduce the bug...I could create, saveand open a new dashboard with a graph inside with no problem
could yu give more details ?

**Comment by borpin** [comment]
I suspect the problem is when it is a new install and there are no dashboards present.

**Comment by alexandrecuer** [comment]
I tested with a new install without any dashboard....
