### ISSUE TITLE
Dockerfile for Emoncms pre-installed & optimised

### ISSUE THREAD

**Issue by josemotta** [emoncms/emoncms#1400]
It would be great to publish a Dockerfile as an alternative to the SD card for Raspberry Pi.  

https://github.com/emoncms/emoncms/blob/master/docs/RaspberryPi/readme.md

**Comment by alexandrecuer** [comment]
You van use the EmonScripts on a VPS with ubuntu18LTS

Se that link
https://github.com/openenergymonitor/EmonScripts
Maybe it could fit to yur needs...
I think there was a docker attempt some times ago but the Scripts are more complete
