### ISSUE TITLE
Add notice to banner of new stable version available

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#1402]
Could a notice be added to the top banner that informs a user when there is a new stable version of emoncms available.  This can be done via manipulating the strings returned from the local repo and
```
https://raw.githubusercontent.com/emoncms/emoncms/stable/version.txt
```
Consideration will need to be made to Emoncms versions in use prior to the `version.txt` being available and perhaps a 'last safe' version to update from. If earlier than that version perhaps a general text message should be displayed instead.

**Comment by TrystanLea** [comment]
This is under development here closing duplicate issue https://github.com/emoncms/emoncms/pull/1468
