### ISSUE TITLE
Hardcoded path to `emoncms`

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#1416]
https://github.com/emoncms/emoncms/blob/fa459ed5c01508c7494ab0684b1a58a0c9eac373/Lib/gridjs/grid-demo.php#L111-L116

While digging around for something else, I note this has hardcoded `emoncms` pathe and still points to `config/vue.js`.

Not sure it solves the problem as I'm not sure how this code is used.

@emrysr

**Comment by emrysr** [comment]
@borpin - this is not required. was used for testing - I'll add a pull request that deletes this file
