### ISSUE TITLE
Printing Dashboards

### ISSUE THREAD

**Issue by dafyddhirst** [emoncms/emoncms#1417]
I was working on creating some printable sumary dashboards.

on the dash the graph looks perfect but when you go to print it out it replaces the feed name with feed name + URL
Dash View
![image](https://user-images.githubusercontent.com/47338885/65216199-0a14b180-daa8-11e9-93cc-3e7009246a09.png)

Print Preview
![image](https://user-images.githubusercontent.com/47338885/65216305-5829b500-daa8-11e9-962c-9354130ba569.png)

<details><summary>Server Information</summary>

# Server Information
## Services
 
- **feedwriter** :- **Active** Running - sleep 60s loading...
- **redis-server** :- **Active** Running

## Emoncms
 
- **Version** :- 10.1.6
- **Modules** :- Administration | EmonHub Config v2.0.4 | Dashboard v2.0.4 | Device v2.0.1 | EventProcesses | Feed | Graph v2.0.4 | Graph v2.0.4 | Group v2.0.0 | Input | CoreProcess | Schedule | Time | User | Visualisation
- **Git** :- 
     - **URL** :- https://github.com/emoncms/emoncms.git
     - **Branch** :- * master
     - **Describe** :- 10.1.6-55-gdc2e870f

## Server
 
- **OS** :- Linux 4.9.0-8-amd64
- **Host** :- vps640695 | vps640695.ovh.net | (51.38.69.188)
- **Date** :- 2019-09-19 06:40:33 BST
- **Uptime** :- 06:40:33 up 231 days, 19:30,  2 users,  load average: 0.21, 0.31, 0.28

## Memory
 
- **RAM** :- Used: 11.29%
    - **Total** :- 7.62 GB
     - **Used** :- 880.02 MB
     - **Free** :- 6.76 GB

## Disk
 
- **/** :- Used: 12.77%
    - **Total** :- 78.74 GB
     - **Used** :- 10.06 GB
     - **Free** :- 65.46 GB

## HTTP
 
- **Server** :- Apache/2.4.25 (Debian) HTTP/1.1 CGI/1.1 80

## MySQL
 
- **Version** :- 5.5.5-10.1.37-MariaDB-0+deb9u1
- **Host** :- localhost:6379 (127.0.0.1)
- **Date** :- 2019-09-19 06:40:33 (UTC 01:00‌​)
- **Stats** :- Uptime: 20028620  Threads: 1  Questions: 239398244  Slow queries: 0  Opens: 420  Flush tables: 1  Open tables: 65  Queries per second avg: 11.952

## Redis
 
- **Version** :- 3.2.6
- **Host** :- localhost:6379
- **Size** :- 9030 keys (2.72M)
- **Uptime** :- 231 days

## PHP
 
- **Version** :- 7.0.33-0+deb9u1 (Zend Version 3.0.0)
- **Modules** :- apache2handler | calendar v7.0.33-0+deb9u1 | Core v7.0.33-0+deb9u1 | ctype v7.0.33-0+deb9u1 | curl v7.0.33-0+deb9u1 | date v7.0.33-0+deb9u1 | dom v20031129 | exif v7.0.33-0+deb9u1 | fileinfo v1.0.5 | filter v7.0.33-0+deb9u1 | ftp v7.0.33-0+deb9u1 | gettext v7.0.33-0+deb9u1 | hash v1.0 | iconv v7.0.33-0+deb9u1 | json v1.4.0 | libxml v7.0.33-0+deb9u1 | mbstring v7.0.33-0+deb9u1 | mcrypt v7.0.33-0+deb9u1 | mysqli v7.0.33-0+deb9u1 | mysqlnd vmysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $ | openssl v7.0.33-0+deb9u1 | pcre v7.0.33-0+deb9u1 | PDO v7.0.33-0+deb9u1 | pdo_mysql v7.0.33-0+deb9u1 | Phar v2.0.2 | posix v7.0.33-0+deb9u1 | readline v7.0.33-0+deb9u1 | redis v4.2.0 | Reflection v7.0.33-0+deb9u1 | session v7.0.33-0+deb9u1 | shmop v7.0.33-0+deb9u1 | SimpleXML v7.0.33-0+deb9u1 | sockets v7.0.33-0+deb9u1 | SPL v7.0.33-0+deb9u1 | standard v7.0.33-0+deb9u1 | sysvmsg v7.0.33-0+deb9u1 | sysvsem v7.0.33-0+deb9u1 | sysvshm v7.0.33-0+deb9u1 | tokenizer v7.0.33-0+deb9u1 | wddx v7.0.33-0+deb9u1 | xml v7.0.33-0+deb9u1 | xmlreader v7.0.33-0+deb9u1 | xmlwriter v7.0.33-0+deb9u1 | xsl v7.0.33-0+deb9u1 | Zend OPcache v7.0.33-0+deb9u1 | zlib v7.0.33-0+deb9u1
</details>

<details><summary>Client Information</summary>

# Client Information
## HTTP
 
- **Browser** :- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
- **Language** :- en-US,en;q=0.9

## Window
 
- **Size** :- 1903 x 969

## Screen
 
- **Resolution** :- 1920 x 1080
</details>

**Comment by TrystanLea** [comment]
Sorry to miss this @dafyddhirst Im not sure how we fix this as it seems to be related to how the browser prints page output rather than the emoncms application itself. The best way to get around it is probably to take a screenshot and print the result, it should give better results.
