### ISSUE TITLE
Cloning a dashboard - stops dashboards screen working

### ISSUE THREAD

**Issue by dafyddhirst** [emoncms/emoncms#1418]
If i clone a new or old dashboard i get the following when you reload the dashboard page.
![image](https://user-images.githubusercontent.com/47338885/65219152-e9505a00-daaf-11e9-9cf3-01a87a4315ab.png)

the dash clones apear on the side bar Thus
![image](https://user-images.githubusercontent.com/47338885/65219220-113fbd80-dab0-11e9-9d26-5445d2e0abe9.png)

Modules: Administration | EmonHub Config v2.0.4 | Dashboard v2.0.4 | Device v2.0.1 | EventProcesses | Feed | Graph v2.0.3 | Graph v2.0.4 | Group v2.0.0 | Input | CoreProcess | Schedule | Time | User | Visualisation

**Comment by emrysr** [comment]
this has been addressed in https://github.com/emoncms/dashboard/pull/234
