### ISSUE TITLE
mysql instructions for ubuntu install outdated

### ISSUE THREAD

**Issue by evilantishad0w** [emoncms/emoncms#1422]
Re: https://github.com/emoncms/emoncms/blob/master/docs/LinuxInstall.md

The instructions under "Create a MYSQL database" are outdated; instead of the command:

> mysql -u root -p

The following should be used:

>sudo mysql --user=root mysql

(Solution found at https://askubuntu.com/questions/763336/cannot-enter-phpmyadmin-as-root-mysql-5-7 )

**Comment by borpin** [comment]
Quite possibly so - these instructions are badly in need of update although the intention is to provide a script and probably retire the various instructions.  The Install process that will be used by the script is here 

https://github.com/openenergymonitor/EmonScripts/blob/master/install/mysql.sh

**Comment by borpin** [comment]
@evilantishad0w The new install script instructions look [like this](https://github.com/openenergymonitor/EmonScripts/blob/master/install/mysql.sh)
