### ISSUE TITLE
Error on Inputs page

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#1424]
This error just appeared in the browser window - the tab was in the background at the time.

![image](https://user-images.githubusercontent.com/1322749/65395267-72a5ac00-dd90-11e9-9c43-a7349a3628d8.png)

It might be this line of code `devices[nodeid].inputs.push(inputs[z]);`

In console

![image](https://user-images.githubusercontent.com/1322749/65395282-aa145880-dd90-11e9-8bca-0b7712fc7b3c.png)

**Comment by alexandrecuer** [comment]
I also noticed that the input/view route does not work with microsoft Edge (but who use Edge nowadays?)
![image](https://user-images.githubusercontent.com/24553739/65442206-0b3d3a00-de2c-11e9-82e2-4d31d08f4e10.png)

**Comment by emrysr** [comment]
@borpin - I can't reproduce the error you reported... any additional information might allow me to reproduce it.

I've created a pull request #1428 that simply checks the variable type before running the function, this is always good practice - however this exception shouldn't occur as the variable is always set to be the expected type (array)

**Comment by emrysr** [comment]
@alexandrecuer - thanks for reporting this issue, however I dont think this error is related to the original issue. I'll create a new github issue to track this problem

**Comment by borpin** [comment]
I am getting random errors like this ATM. On a different error, @TrystanLea suggested one of the reasons was REDIS getting out of sync. Could that be a factor here?

**Comment by borpin** [comment]
Errors seem to have gone so closing for now. Cheers.
