### ISSUE TITLE
Errors in Admin page on Shared Hosting environments

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#1425]
On a shared hosting environment, some of the info that the admin page trys to pull in is restricted or unavailable resulting in errors.

https://community.openenergymonitor.org/t/update-from-9-9-5-to-10-1-6-some-errors/11995

**Comment by TrystanLea** [comment]
Latest reply: https://community.openenergymonitor.org/t/update-from-9-9-5-to-10-1-6-some-errors/11995/23

**Comment by borpin** [comment]
On the basis of the comment, I think this can be closed.
