### ISSUE TITLE
I also noticed that the input/view route does not work with microsoft Edge (but who use Edge nowadays?)

### ISSUE THREAD

**Issue by emrysr** [emoncms/emoncms#1429]
I also noticed that the input/view route does not work with microsoft Edge (but who use Edge nowadays?)
![image](https://user-images.githubusercontent.com/24553739/65442206-0b3d3a00-de2c-11e9-82e2-4d31d08f4e10.png)

_Originally posted by @alexandrecuer in https://github.com/emoncms/emoncms/issues/1424#issuecomment-534166478_

**Comment by TrystanLea** [comment]
Marking this as an enhancement as microsoft edge is not a target browser for support. It would be useful to know however if microsoft edge is showing any console errors or anything else we can go by to understand what might be needed to provide support? Is it vue.js related perhaps ? @emrysr
