### ISSUE TITLE
openEVSE emoncms app Type Error

### ISSUE THREAD

**Issue by gr0mit1** [emoncms/emoncms#1453]
Hi
I've got this error when selecting the graph and zooming to a particular time period.  Any ideas on what is causing it?
![Screenshot 2019-10-16 at 10 16 11](https://user-images.githubusercontent.com/11898403/66906080-ea1cd300-effe-11e9-8261-364bc3b0ee8d.png)

**Comment by TrystanLea** [comment]
Thanks @gr0mit1 noted as a bug, we will look into it

**Comment by TrystanLea** [comment]
Hello @gr0mit1 we are removing this app for now as its a replica of My Electric 2, the intention was to add specific OpenEVSE features but until that point we've removed it to avoid confusion and focus on the My Electric 2 app. https://github.com/emoncms/app/commit/5d43ba90f6c2bfbae7eeace576305b7e77148eef
