### ISSUE TITLE
low write mode causing problems

### ISSUE THREAD

**Issue by Hecot** [emoncms/emoncms#1456]
I've followed [the guide](https://github.com/emoncms/emoncms/blob/master/docs/RaspberryPi/Low-write-mode.md) to activate the low write mode in emoncms step by step but now the webpage is not available anymore and I'm getting a http error 500

![low write_01](https://user-images.githubusercontent.com/11699283/67181710-b87c8100-f3dd-11e9-8613-0345bf24864a.JPG)

I've double checked the steps and found that the feedwriter service is not running ...

![low write_02](https://user-images.githubusercontent.com/11699283/67182353-43aa4680-f3df-11e9-871b-1aef0755ef33.JPG)

![low write_03](https://user-images.githubusercontent.com/11699283/67182797-3772b900-f3e0-11e9-935d-b819443c3601.JPG)

I don't know if this is causing the issue and how to solve this? Can someone please help ... I'm not the RPi pro ... sorry!

Hecot

**Comment by borpin** [comment]
Hi @Hecot, best place to ask is on the community https://community.openenergymonitor.org/

Cheers

**Comment by Hecot** [comment]
@borpin Thanks - did a post there too!

**Comment by borpin** [comment]
> did a post there too!

Ok, I'll have a look. Can you close this issue please?

**Comment by borpin** [comment]
Actually don't close - @TrystanLea another guide for the archive please.

**Comment by Hecot** [comment]
Please update instead of archive!!!
