### ISSUE TITLE
reference to forbidden directory in admin module

### ISSUE THREAD

**Issue by daniu-de** [emoncms/emoncms#1459]
https://github.com/emoncms/emoncms/blob/8a55954560135f4c095b537cb58a07a5aff599ca/default-settings.php#L6
no idea if it is only me but it does not work with the _ needs to be $settings [...] for me

**Comment by TrystanLea** [comment]
Thanks @daniu-de you need to use example.settings.php as the settings reference rather than default-settings.php. Example settings contains $settings as you describe.
