### ISSUE TITLE
per-user timezone support

### ISSUE THREAD

**Issue by Dave-McCraw** [emoncms/emoncms#146]
Hi,

I've written a simple time of day filter process: Dave-McCraw/emoncms@8f46d3cb1735678a57fba8a09e8de2643dfe1ee8 

It's a simple pass-through which takes a bitmask of the hours to allow as its argument. If the current hour is not in the bitmask, the value returned is zero.

As a quick first draft, I just used gmdate() to get the UTC hour of the day, but this will break for daylight savings and be a headache generally.

Any ideas? 

In an ideal world emoncms would record the user's current timezone (like Europe/London, not UTC offset as is currently on the account page). 

I could then do a simple conversion between the system timezone (see #145 ) and user's timezone to get the recording right for everyone.

**Comment by chaveiro** [comment]
Fixed on https://github.com/emoncms/emoncms/pull/303
