### ISSUE TITLE
index.php points to old location /home/pi

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#1463]
https://github.com/emoncms/emoncms/blob/1f3e991e48cc60416d19d698b4e80f0a9953de26/index.php#L155-L160

This condition may look in the wrong place now I suggest.

It could at least do with a comment re old data paths if not.

**Comment by TrystanLea** [comment]
Thanks @borpin

**Comment by TrystanLea** [comment]
Changed to use redis rather than a file
https://github.com/emoncms/emoncms/commit/fe0fc709074ac9f6442f411d0ef8bb15ffa034af

and related change to emonpiLCD
https://github.com/openenergymonitor/emonpi/commit/73a63d2b3ef861f1d3b91cb33654217e0e3d08e1
