### ISSUE TITLE
Check Redis is running before using rpush

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#1469]
https://github.com/emoncms/emoncms/blob/1f3e991e48cc60416d19d698b4e80f0a9953de26/Modules/admin/admin_controller.php#L240

re https://community.openenergymonitor.org/t/cant-update-10-1-6-fleeting-php-errors/12296

The call to redis should first check for the service running else an exception is raised. Ideally this should inform the user how to perform a manual update.

Other places where this is called should also check for the redis service.

**Comment by TrystanLea** [comment]
Thanks @borpin

**Comment by TrystanLea** [comment]
Fixed https://github.com/emoncms/emoncms/commit/9ebd472d113f7e94e8507be68c2b0b8ee5ffbacf
