### ISSUE TITLE
Consider URL parameter to load dashboards with sidebar collapsed

### ISSUE THREAD

**Issue by TrystanLea** [emoncms/emoncms#1478]
https://community.openenergymonitor.org/t/option-to-minimize-the-setup-sidebar/12583

**Comment by TrystanLea** [comment]
Noting as feature request to be kept open as a reference for future development, when time/resources allow.

**Comment by emrysr** [comment]
might be an idea to always show the close icon shown on mobile devices:
![delwedd](https://user-images.githubusercontent.com/1466013/70837626-66b01000-1dfc-11ea-8ba5-e0fc67fd9a9e.png)

and saving the selection as a cookie value that is remembered between page loads??  might be useful for desktop users... usability might need some testing on mobile devices/

**Comment by borpin** [comment]
@emrysr The user who raised this uses smart TV so no mouse function available.

His suggestion is for it to be an option for a dashboard, which seems like a good idea as that is where it is most likely to be used.

Perhaps an option to hide the top bar as well.

**Comment by emrysr** [comment]
here's a pull request with a dashboard "fullscreen" option...
https://github.com/emoncms/dashboard/pull/245
