### ISSUE TITLE
Strange input name behaviour

### ISSUE THREAD

**Issue by TrystanLea** [emoncms/emoncms#1480]
See: https://community.openenergymonitor.org/t/missing-input-name/12607

**Comment by emrysr** [comment]
also similar to issue with feeds page:
https://community.openenergymonitor.org/t/cannot-update-feeds-names-or-view-feed-values-and-seconds-since-update-in-mobile-version-10-1-13-on-android/12687/17

**Comment by emrysr** [comment]
this issue is caused by the text wrapping to 2 lines if a space character is used.
