### ISSUE TITLE
input value field a bit narrow?

### ISSUE THREAD

**Issue by danbates2** [emoncms/emoncms#1481]
can't see the numbers very clearly as seen here. it should show a unix time float such as 1575998150.0336099.
![Screen Shot 2019-12-10 at 17 15 43](https://user-images.githubusercontent.com/5250782/70552201-cdb99480-1b70-11ea-9190-724af9d84f5e.png)

**Comment by TrystanLea** [comment]
Thanks @danbates2  Noting as feature request to be kept open as a reference for future development
