### ISSUE TITLE
Power to kWh feed not resetting upon 'clear'.

### ISSUE THREAD

**Issue by danbates2** [emoncms/emoncms#1487]
At the delete feed dialog box, including clear and trim options, the clear option doesn't reset the power to kWh accumulator. Possibly this behaviour would apply to other accumulators.
It'll be a matter of preference as to whether the accumulator is reset, but I think if the aim is to 'clear' the feed, the the accumulated value should also be reset.
Trim may not reset the accumulator if deleting history is what one wants.
![Screen Shot 2019-12-18 at 19 40 04](https://user-images.githubusercontent.com/5250782/71117799-be6cc380-21ce-11ea-87f0-ffe4af92e4cb.png)
Shows freshly cleared feed with old, now incorrect, value. I needed to recreate the feed.

**Comment by emrysr** [comment]
The previous value must be cached for the accumulation to happen??... Thanks @danbates2 I'll look into this.

**Comment by danbates2** [comment]
Not sure. Just seems like common sense that if the desired action is to 'clear' the feed (the same as resetting!) then the value should be reset.
If clearing the feed is desired without the value reset, then the 'trim' can be used. Makes sense?

**Comment by TrystanLea** [comment]
This is now fixed https://github.com/emoncms/emoncms/commit/230bd485bc77f073ed3489119b8381b69dd9c6ae
