### ISSUE TITLE
User account UTC selection not applied to kwhd

### ISSUE THREAD

**Issue by SergioEscuder** [emoncms/emoncms#149]
UTC selected by user in the account settings is not used when displaying daily, monthly and yearly consumption totals. Graphs do not reset at 00:00 local user time, this only happens at server local time.
see this post for full details...
http://openenergymonitor.org/emon/node/3955

Also Sean has found the possible source of the problem in this code...

https://github.com/emoncms/emoncms/blob/master/Modules/vis/visualisation...

function draw()
  {
    data = [];
   
    var d = new Date()
    var n = d.getTimezoneOffset();  <---------------------
    var offset = n / -60;
   
    var datastart = (Math.round((view.start/1000.0)/interval) * interval)+3600*offset;
    data = feed.get_timestore_average(feedid,datastart*1000,view.end+(interval*1000),interval);

**Comment by chaveiro** [comment]
Fixed on https://github.com/emoncms/emoncms/pull/303
