### ISSUE TITLE
incorrect error message in index.php?

### ISSUE THREAD

**Issue by bgraabek** [emoncms/emoncms#1490]
If the mysql/mariadb username or password in /var/www/emoncms/settings.ini is incorrect, an error message is displayed stating that Emoncms “Can't connect to database, please verify credentials/configuration in **settings.php**”. That .php should surely be .ini?

**Comment by borpin** [comment]
There is still a process going on to migrate from the old php settings format to the new ini format.

But yes the message should probably reflect that.

**Comment by TrystanLea** [comment]
Thanks now fixed: https://github.com/emoncms/emoncms/commit/71c851a515f1225edb18a0b5cb86da127095b33e
