### ISSUE TITLE
Allow alphanumeric/64bit hex node name

### ISSUE THREAD

**Issue by pfranquesa** [emoncms/emoncms#15]
Would be useful to allow alphanumeric or 64bit hex string node names (node parameter in post URL) to simplify commissioning of remote nodes using IEEE802.15.4 radios with EUI64 MAC address as node Id. I have implemented this in a local copy with only some minor changes to master branch code and it seems to work ok.

**Comment by Paul-Reed** [comment]
Thanks for the suggestion. More recent developments by Chaveiro has introduced the 'device' module which uses a devicekey instead.
