### ISSUE TITLE
Virtual feed with same node name causes feed list error

### ISSUE THREAD

**Issue by TrystanLea** [emoncms/emoncms#1500]
See: https://community.openenergymonitor.org/t/dashboard-loggedin-vs-public/11626/19

I have not yet been able to replicate.

**Comment by fillycheezstake** [comment]
I've added to the post in the link above.  Let me know if there's any further testing you'd like me to do.

**Comment by borpin** [comment]
Note user feedback here

https://community.openenergymonitor.org/t/dashboard-loggedin-vs-public/11626/27

If user TZ is not found, then user browser TZ seems most logical.

**Comment by emrysr** [comment]
https://github.com/emoncms/emoncms/pull/1522

**Comment by TrystanLea** [comment]
fixed here: https://github.com/emoncms/emoncms/commit/ab04267ca1bcacdfc293db5e0647fa84a38ddb66

**Comment by chaveiro** [comment]
See my comment here:
https://github.com/emoncms/emoncms/commit/ab04267ca1bcacdfc293db5e0647fa84a38ddb66#r37643142
