### ISSUE TITLE
API inconsistent in the accuracy of unix time

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#1507]
The API appears to want time in Milliseconds as an input, but the returned data is sometimes seconds and other times milliseconds.

```
/feed/timevalue.json
```
return seconds
```
/feed/data.json
```
both wants, and returns data in milliseconds.

As a minimum this should be documented as changing it risks breaking all sorts of things.

**Comment by TrystanLea** [comment]
The feed/data/ api has been updated since to support a wider range of time formats, closing for now
