### ISSUE TITLE
Uncaught Error: Class 'Redis' not found

### ISSUE THREAD

**Issue by MarvinMichel** [emoncms/emoncms#1512]
I try to run emoncms on a shared hosting enivronment. It installed fine and within settings.ini/.php I Redis is disabled. Yet I still get this error when visiting the page.

**Comment by borpin** [comment]
Can you post a bit more detail, screen shots, exact URL etc please.

Which is it, INI or PHP (should be INI only).

**Comment by MarvinMichel** [comment]
Solved it! The settings.php was changed
