### ISSUE TITLE
submit timestamp on input

### ISSUE THREAD

**Issue by FlexyZ-xx** [emoncms/emoncms#1519]
Hi

Can I post my own custom  timestamp for a given input field?

My electrical usage is only available back-in-time by 1 or 2 days.

I need to compare with EV charge data pr. hour/day 

Thanks
Felix

**Comment by FlexyZ-xx** [comment]
ahh ok found it, so I have to post only one value if I want custom timestamp - or?

**Comment by borpin** [comment]
Better asked on the [Forum](https://community.openenergymonitor.org/). But yes using the JSON input format.
