### ISSUE TITLE
Locale issue with decimal separator

### ISSUE THREAD

**Issue by Jerome-github** [emoncms/emoncms#154]
Hi.

There seems to be trouble with decimal numbers if the decimal separator is not '.', depending on the locale.

With en_EN I can enter 0.01. With fr_FR, it seems to be read 0, and a second processing line is created with null null as arguments. If I enter 0,01, then I get an error message: a number is required.

My emoncms is not up to date (pre-Redis). Please close if this was fixed since.

See forum thread: http://openenergymonitor.org/emon/node/4063

**Comment by chaveiro** [comment]
Is this still an issue?

**Comment by Jerome-github** [comment]
On 9.2, both 0.01 and 0,01 end up as 0.01 which is fine for me.

One could argue that it would be nice to actually localize the decimal separator in the view using '.' or ',' depending on the locale (and this might be easy to achieve if some framework feature offers it out of the box), but sticking to '.' and making sure other characters are correctly understood or escaped is great already.
