### ISSUE TITLE
Log Window missing

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#1541]
The log window is missing on the Admin page

https://community.openenergymonitor.org/t/log-window-missing/13686/1

**Comment by borpin** [comment]
The problem is that this line has been commented out
https://github.com/emoncms/emoncms/blob/aa0c69b1038288a98b69a31b66b05d80e558ac0d/Modules/admin/admin_main_view.php#L228

but it needs some other formatting as well

**Comment by borpin** [comment]
@TrystanLea can you fix this please?

**Comment by TrystanLea** [comment]
Sorry, on its way:

fix in master:
https://github.com/emoncms/emoncms/commit/59edbc7561d4db4026a8114b1f46981235cadb5c

merge master to stable in progress:
https://github.com/emoncms/emoncms/pull/1555

**Comment by borpin** [comment]
Is the merge to stable coming soon?

**Comment by TrystanLea** [comment]
Merged: https://community.openenergymonitor.org/t/emoncms-v10-2-2-release-org-upgrade/13683 thanks
