### ISSUE TITLE
Cannot embed a Multigraph - Feed not seen as public

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#1556]
Trying to create a Multigraph to embed.

No matter what Feed I select, the Multigraph thinks the Feed is not public. Tried with other graphs and they are content the Feed is public.

**Comment by TrystanLea** [comment]
This seems to work ok for me. Both directly via multigraph url and in a dashboard..

E.g:

**Comment by borpin** [comment]
Same on my emonPi

![image](https://user-images.githubusercontent.com/1322749/79642226-27237700-8194-11ea-8bad-ccc2b7828850.png)


![image](https://user-images.githubusercontent.com/1322749/79642242-45897280-8194-11ea-8732-8c3cce5de43d.png)

**Comment by borpin** [comment]
@TrystanLea did you see my feedback?

**Comment by borpin** [comment]
bump @TrystanLea

**Comment by TrystanLea** [comment]
Could you include a screenshot of what you are seeing @borpin , if I access an embedded multigraph here whilst logged out I get:

![image](https://user-images.githubusercontent.com/503186/82891292-638d8400-9f45-11ea-9892-7f4094e90cf1.png)

**Comment by borpin** [comment]
Do you get the error when creating it as shown above?

**Comment by borpin** [comment]
Ok, yes I am able to view it. Honestly, I hadn't tried as I got the warning!

Why then the warning?
