### ISSUE TITLE
Use node/js package manager

### ISSUE THREAD

**Issue by reedy** [emoncms/emoncms#1572]
Rather than just manually bringing in JS libraries, using a package.json file would be a lot more maintainable

https://docs.npmjs.com/creating-a-package-json-file

**Comment by chaveiro** [comment]
Agree. Could you do that for the comunity?

**Comment by TrystanLea** [comment]
im not 100% on this one, adding the requirement to build using npm seems like an additional hurdle that could be difficult to support or migrate users too?
