### ISSUE TITLE
PHP Version Requirement

### ISSUE THREAD

**Issue by reedy** [emoncms/emoncms#1578]
https://github.com/emoncms/emoncms/blob/b934e97/readme.md#requirements says

>PHP (tested with 7.0.30)

But we don't define an actual PHP requirement anywhere (composer.json for example), nor do we enforce this anywhere...

https://github.com/emoncms/emoncms/blob/master/.travis.yml has 5.6, 7.2 and 7.3 which is an odd mix

5.6 is EOL since 31 Dec 2018
7.0 is EOL since 10 Jan 2019
7.1 is EOL since 1 Dec 2019

7.2 is out of active support since 30 Nov 2019, security support till 30 Nov 2020

7.3 goes out of active support in 6 Dec 2020 and security support goes away 6 Dec 2021

https://www.php.net/supported-versions.php
https://www.php.net/eol.php

**Comment by Twincarb** [comment]
A review of the code show the minimum php version is 7.1 setTime is used in several areas as listed below:
export_monthly_cron.php
process_processlist.php
schedule_model.php

**Comment by reedy** [comment]
> A review of the code show the minimum php version is 7.1 setTime is used in several areas as listed below:
> export_monthly_cron.php
> process_processlist.php
> schedule_model.php

That's a bug in PhpStorm. I filed a bug upstream a couple of days ago - https://youtrack.jetbrains.com/issue/WI-52664

The `@since` is for the `$microseconds` parameter, not the whole function

**Comment by reedy** [comment]
> > A review of the code show the minimum php version is 7.1 setTime is used in several areas as listed below:
> > export_monthly_cron.php
> > process_processlist.php
> > schedule_model.php
> 
> That's a bug in PhpStorm. I filed a bug upstream a couple of days ago - https://youtrack.jetbrains.com/issue/WI-52664
> 
> The `@since` is for the `$microseconds` parameter, not the whole function

https://youtrack.jetbrains.com/issue/WI-51054

To be fixed in 2020.1.1
