### ISSUE TITLE
passthru() returns void, but used as return value

### ISSUE THREAD

**Issue by reedy** [emoncms/emoncms#1580]
In admin_controller.php `return passthru()` is used twice, but `passthru()` returns void...

**Comment by TrystanLea** [comment]
removed https://github.com/emoncms/emoncms/commit/cab32def55fc70d987b09e452e73e193f26f6ea4 and fixed indentation https://github.com/emoncms/emoncms/commit/6301093e08196f60493a0d35ba345e4958c9c4af
