### ISSUE TITLE
kwh_to_kwhd not working on v8

### ISSUE THREAD

**Issue by gloorung** [emoncms/emoncms#159]
For my gas and water monitoring, which is pulse-counting based, I use the (new) kwh-to-kwh/d operator after the accumulator operator. With the upgrade to v8, the daily value no longer updates. I still use a combination of mysql to store daily stats and tilmestore for realtime data, so no redis yet. 

After inspecting the code, I see in line 245 of the file process_model.php "if (!redis) return $value", so I'm not expecting much to happen. Is this a bug or is the use of mysql for daily stats no longer supported (i see the default engine is now phpfina) ?

**Comment by Paul-Reed** [comment]
The process_model.php has been largely re-written over the past few months, is this still an issue in v9 ?
If so please let us know, and we can re-open this issue.
