### ISSUE TITLE
Virtual feeds treat nulls in inputs as zero

### ISSUE THREAD

**Issue by btownshend** [emoncms/emoncms#1609]
When setting up a virtual feed, for example as the sum of 2 feeds, if either of the feeds is null, the result is the sum with the null's assumed to be zero (i.e. the sum then equals the non-null input feed).   I believe the correct result should be a null result.

**Comment by chaveiro** [comment]
It shouldn't this bug was introduced between v9 to now.
What engine are you using?

**Comment by TrystanLea** [comment]
I notice this as well using two PHPFina feeds as the source feeds. I cant see changes 

![image](https://user-images.githubusercontent.com/503186/109537298-a2dd9800-7ab6-11eb-92a8-373ac6c8a536.png)

Is it this average section here that's causing it, sum=0 as a starting point? https://github.com/emoncms/emoncms/blame/master/Modules/process/process_processlist.php#L1619

**Comment by TrystanLea** [comment]
This seems to work:

```
    public function sub_source_feed($feedid, $time, $value, $options)
    {
        $last = $this->source_feed_data_time($feedid, $time, $value, $options);
        
        if ($value==null || $last==null) return null;
        $myvar = $last*1;
        return $value - $myvar;
    }
```

**Comment by TrystanLea** [comment]
I added the line 

        if ($value==null || $last==null) return null;
