### ISSUE TITLE
Use VictoriaMetrics as time series database

### ISSUE THREAD

**Issue by valyala** [emoncms/emoncms#1610]
It would be great to use [VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics) as a time series database for emoncms. This tsdb provides the following features, which could be useful for emoncms case:

* It [works on ARM](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#arm-build).
* It is easy to setup and operate - it is just a single small binary without any dependencies. See [this article](https://medium.com/@valyala/stripping-dependency-bloat-in-victoriametrics-docker-image-983fb5912b0d) for details.
* It is optimized for low IOPS storage such as HDD or flash cards on RaspberryPI.
* It provides the best on-disk compression rate for time series data. See [this article](https://medium.com/faun/victoriametrics-achieving-better-compression-for-time-series-data-than-gorilla-317bc1f95932) for more details. VictoriaMetrics users report 0.4-0.8 bytes per data point for production data - see [case studies](https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/CaseStudies) for more numbers.
* It is optimized for low resource usage (CPU, RAM, disk IO and disk space).
* It accepts data via many popular protocols such as Influx line protocol, Graphite plaintext protocol, OpenTSDB telnet protocol and arbitrary CSV. See [these docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-import-time-series-data) for more details.

Additionally to these features VictoriaMetrics provides [MetricsQL](https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/MetricsQL) query language optimized for typical queries over time series data. It is backwards compatible with PromQL from [Prometheus](https://prometheus.io/), so it is easy to query VictoriaMetrics from Grafana using standard datasource for Prometheus. See [these docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#grafana-setup) for details.

**Comment by TrystanLea** [comment]
Thanks @valyala it sounds awesome but realistically it's not something we are going to be able to do as part of this project, as you can imagine with the slow response :) but thanks for letting us know about this.
