### ISSUE TITLE
pymodbus not installed

### ISSUE THREAD

**Issue by relft** [emoncms/emoncms#1611]
Hi,

With latest default image (prebuilt SD) emonSD-17Oct19 (Stable) if you try to use pymodbus an error is show like pymodbus not installed

to solve you have to install pydmodbus, it will be great to preinstall all required packages and dependencies by default

command used to install manually
apt-get install python-pymodbus  python3-pymodbus

a second question after install and updates emoncms to latest version, can be updated to latest raspbian packages with apt-get update and apt-get upgrade, any known incompatibility?

Thanks

**Comment by alexandrecuer** [comment]
Pymodbus is only used in emonhub if you try to activate the emonmodbusTcpinterfacer and it is not used by all emoncms users so that's

**Comment by relft** [comment]
Correct, but where js the issue to preinstall if it is needed?
Alsomsearched information, and not found maybe preinstall and add
documentation will be great for futurenusers only to try to help

Thanks

El ds., 6 de juny 2020, 23:06, Alexandre CUER <notifications@github.com> va
escriure:

**Comment by TrystanLea** [comment]
pymodbus is now included in the installer https://github.com/openenergymonitor/emonhub/blob/master/install.sh#L21

**Comment by relft** [comment]
Perfect and Thanks

El dj., 30 de jul. 2020, 12:41, Trystan Lea <notifications@github.com> va
escriure:
