### ISSUE TITLE
Invalid Serial Port type on update

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#1630]
The code does not allow for not using a serial port.

Please fix urgently @TrystanLea.

https://github.com/emoncms/emoncms/blob/a7ddc3384417f1e2ebc07673f5b6928d2d77d04d/Modules/admin/admin_controller.php#L237

The port variable is `null` - note I am **only** doing an emoncms update.

![image](https://user-images.githubusercontent.com/1322749/93395788-728aa000-f86e-11ea-8177-a1e71f6a6e9b.png)

**Comment by TrystanLea** [comment]
Thanks @borpin 

Does this exit the update process? What are you seeing exactly?

**Comment by borpin** [comment]
> Does this exit the update process? What are you seeing exactly?

Yes it just bombs out with that message which is never actually written to the log file either.

Note I am trying to only update emoncms at this point, and the admin does say **none** next to firmware.

Anyone who hits this will have to manually update via git to clear this code going forward.

**Comment by TrystanLea** [comment]
Ok I can see the issue, thanks

**Comment by TrystanLea** [comment]
Clicked the wrong button there!
