### ISSUE TITLE
redis setTimeout deprecated

### ISSUE THREAD

**Issue by SimonWilkinson** [emoncms/emoncms#1636]
Emoncms reports the following warning when using the ifMuteSkip and ifNotMuteSkip functions in the eventp module:

    020-10-12 12:47:56.967|ERROR|emoncms_mqtt.php|ErrorException: Function Redis::setTimeout() is deprecated in /var/www/emoncms/Modules/eventp/eventp_processlist.php:154
    Stack trace:
    #0 /var/www/emoncms/Modules/eventp/eventp_processlist.php(154): exceptions_error_handler(8192, Function Redis:...', '/var/www/emoncm...', 154, Array)
    #1 /var/www/emoncms/Modules/process/process_model.php(71): Eventp_ProcessList->ifMuteSkip('30', 1602506876, 20.7888, NULL, Object(Process))
    #2 /var/www/emoncms/Modules/process/process_model.php(122): Process->__call('ifmuteskip', Array)
    #3 /var/www/emoncms/scripts/services/emoncms_mqtt/emoncms_mqtt.php(390): Process->input(1602506876, 20.7888, '1:9,20:12,2:0.0...')
    #4 [internal function]: message(Object(Mosquitto\Message))
    #5 /var/www/emoncms/scripts/services/emoncms_mqtt/emoncms_mqtt.php(142): Mosquitto\Client->loop()
    #6 {main}`

setTimeout appears to have been deprecated in phpredis 5.32, by this commit - https://github.com/phpredis/phpredis/commit/95c8aab9dfc60890d713f48d78f4e43c373843bf

It looks like 'expire' is the recommended name to now use, and like that's been present (albeit as an alias) since version 2.1.0 in 2010.

Happy to create a pull request to fix this, if that's the easiest way to go.

Simon

**Comment by TrystanLea** [comment]
Thanks @SimonWilkinson and sorry for the delay.

I've fixed this now to use expire https://github.com/emoncms/emoncms/commit/813a02a46bbb16c8d7f326687db97add01743f23
