### ISSUE TITLE
Localhost/emoncms error. 

### ISSUE THREAD

**Issue by Hassanwahab41** [emoncms/emoncms#1642]
Hi,

I did the initial steps and have got all the files in the database. now i have changed the example.setting.ini file as mentioned in the installation manual and wants to create the user account but i have got the attached error.  Please help and thank you
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/74196614/98558108-f3797d00-229c-11eb-88d5-77598ccdfcfe.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/74196614/98558113-f4aaaa00-229c-11eb-9b95-d33fcbc4750a.png)

**Comment by borpin** [comment]
You need to ask questions like this on the Forum https://community.openenergymonitor.org/

**Comment by Hassanwahab41** [comment]
Thanks. I will post it there :)
