### ISSUE TITLE
Timezone error Create new user 

### ISSUE THREAD

**Issue by karan369** [emoncms/emoncms#1645]
Create the new user register it shows
Error: Timezone is not valid

Also i tried to 
```
sudo nano /etc/php/7.0/cli/php.ini
```
date.timezone = Asia/Kolkata
```
sudo nano  etc/php/7.0/apache2/php.ini
date.timezone = Asia/Kolkata
```
This error shows again. How to solve this issue.

**Comment by TrystanLea** [comment]
Thanks @karan369 and sorry for the delay.

I've now updated the code to default to UTC if the timezone is not valid
https://github.com/emoncms/emoncms/commit/fd82d0cb4c35a533ac7cdb1dd7df43d7c8b2009c

Im not sure why this error was being shown to start with, but I think I remember seeing it on an older system that I had. This fix gets around the issue at least allowing for user registration
