### ISSUE TITLE
Plus sign in email prevents registration

### ISSUE THREAD

**Issue by bstegmaier** [emoncms/emoncms#1648]
Registering a new account on emoncms.org is not possible with email addresses containing a plus character:
Given I registered with an email containing a plus character e.g. mail+emoncms@example.com
When I click the link in the registration email
Then I see an error "Email address format error".
<img width="355" alt="Screenshot 2021-01-03 at 11 48 58" src="https://user-images.githubusercontent.com/1767130/103476877-aeb02500-4db9-11eb-88f6-12d512cafbd8.png">

Workaround is to manually replace the plus character in the URL with its url encoded representation %2B

Plus signs in email addresses are valid according to rfc822/ rfc2822 and are often used for tagging purposes.

**Comment by bstegmaier** [comment]
You might need to urlencode the email here:
https://github.com/emoncms/emoncms/blob/c452583b095d4aba12edc8eac0e5b919c1770b84/Modules/user/user_model.php#L301

**Comment by TrystanLea** [comment]
Thanks @bstegmaier and sorry for the delay, I've added in urlencode as you suggest https://github.com/emoncms/emoncms/commit/4d9b41f8cacfa955cd68fbdc654446e1ab790544
