### ISSUE TITLE
CSV export produces empty file, with MysqlTimeStore.php storage engine

### ISSUE THREAD

**Issue by euqip** [emoncms/emoncms#165]
I tried to use the CSV export procedure, and encountered some problems, resulting in empty exported data file.

Here is a solution suggestion.  I did'nt check other engines than MysqlTimeStore, but I think it's repeatable with other storage engines.

About exportCSV and MysqlTimeSeries.php

To work like a real analog meter or smart meter, the meter result comes at the end of period.
In this example the time period is 15 minutes, all values are aligned at the end of time period
Because the  unix time stamp is not so easy the confert with a spreadsheet, the query makes the convertion.
The average value may be rounded with the sql query.

Beacaus CSV is different in Europe or US, the column separator and the decimal seperator
would be defined by the user, maybe in its profile.  The same applies to the date format to use when converting to human readable date and time.
It can be done through the translation process, but it's more related to the user's machine configuration.
I just hardcoded the values and assigned to variables.

The storage table structure uses a field called time, it may be a source of problems due to existing time instruction 
A name like tstamp is short and explains what it is, while it does not correspond to any instruction.

I do'nt understand the range selection above and under 180000 seconds!

Here a demonstration query on feed id = 3, and 15 minutes averages, like a smart meter.

SELECT from_unixtime(CEIL(time/900)*900,'%Y-%m-%d %h:%i:%s') AS fulltime,
 from_unixtime(min(time),'%Y-%m-%d %h:%i:%s') AS mintime,
  from_unixtime(max(time),'%Y-%m-%d %h:%i:%s') AS maxtime,
   count(time) as countSamples,
   round(avg(data)*100)/100 as AverageDataValue
   FROM feed_3 
   WHERE time BETWEEN 1390608000 AND 1395515501 
   GROUP BY 1 
   order by time desc

Code change proposal:

 public function csv_export($feedid,$start,$end,$outinterval)
    {
        $colsepar=";";
        $decsepar=",";
        $outinterval = intval($outinterval);
        $feedid = intval($feedid);
        $start = intval($start/1000);
        $end = intval($end/1000);
        
        if ($outinterval<1) $outinterval = 1;
        $dp = ceil(($end - $start) / $outinterval);
        $end = $start + ($dp * $outinterval);
        if ($dp<1) return false;

        if ($end == 0) $end = time();

        $feedname = "feed_".trim($feedid)."";

        // There is no need for the browser to cache the output
        header("Cache-Control: no-cache, no-store, must-revalidate");

        // Tell the browser to handle output as a csv file to be downloaded
        header('Content-Description: File Transfer');
        header("Content-type: application/octet-stream");
        $filename = $feedid.".csv";
        header("Content-Disposition: attachment; filename={$filename}");

        header("Expires: 0");
        header("Pragma: no-cache");

        // Write to output stream
        $exportfh = @fopen( 'php://output', 'w' );

        $data = array();
        $range = $end - $start;
        if ($range > 180000 && $dp > 0) // 50 hours
        {
            $sql= "SELECT time, data FROM $feedname WHERE time BETWEEN ? AND ? LIMIT 1";
            $td = $range / $dp;
            $stmt = $this->mysqli->prepare($sql);
            $t = $start; $tb = 0;
            $stmt->bind_param("ii", $t, $tb);
            $stmt->bind_result($dataTime, $dataValue);
            for ($i=0; $i<$dp; $i++)
            {
                $tb = $start + intval(($i+1)*$td);
                $stmt->execute();
                if ($stmt->fetch()) {
                    if ($dataValue!=NULL) { // Remove this to show white space gaps in graph
                        $time = $dataTime * 1000;
                        fwrite($exportfh, $dataTime.",".number_format($dataValue,2)."\n");
                    }
                }
                $t = $tb;
            }
        } else {
            if ($range > 5000 && $dp > 0)
            {
                $td = intval($range / $dp);
                //$sql = "SELECT FLOOR(time/$td) AS time, AVG(data) AS data".
                    " FROM $feedname WHERE time BETWEEN $start AND $end".
                    " GROUP BY 1";
                $sql = "SELECT CEIL(time/$td)*$td AS time, from_unixtime(time,'%d/%m/%Y') AS humandate,from_unixtime(time,'%H:%i:%s') AS humantime,  AVG(data) AS data".
                    " FROM $feedname WHERE time BETWEEN $start AND $end".
                    " GROUP BY 1  ORDER BY time DESC";
            } else {
                $td = 1;
                $sql = "SELECT time, from_unixtime(time,'%d/%m/%Y') AS humandate,from_unixtime(time,'%H:%i:%s') AS humantime, data FROM $feedname".
                    " WHERE time BETWEEN $start AND $end ORDER BY time DESC";
            }

            $result = $this->mysqli->query($sql);
            if($result) {
                fwrite($exportfh, _("UnixTimeStamp").$colsepar._("SampleDate").$colsepar._("SampleTime").$colsepar._("SampleValue")."\n");
                while($row = $result->fetch_array()) {
                    $dataValue = $row['data'];
                    $dataTime = $row['time'];
                    $humanDate = $row['humandate'];
                    $humanTime = $row['humantime'];
                    if ($dataValue!=NULL) { // Remove this to show white space gaps in graph
                        $time = $row['time'] * 1000 * $td;
                        fwrite($exportfh, $dataTime.$colsepar.$humanDate.$colsepar.$humanTime.$colsepar.str_replace(".",$decsepar,number_format($dataValue,2))."\n");
                    }
                }
            }
        }
        fclose($exportfh);
        exit;
    }

**Comment by Paul-Reed** [comment]
A number of changes have taken place in v9 which have changed the way in which CSV export functions. Could you check please if this is still a current issue?

**Comment by jesjimher** [comment]
Commit e4113d9 might have fixed this

**Comment by chaveiro** [comment]
Could not reproduce.
