### ISSUE TITLE
Rebooting RPi which is running emonCMS caused inputs posted to be randomly duplicated

### ISSUE THREAD

**Issue by liamf** [emoncms/emoncms#1651]
Hi there,

new install a few days old of emoncms on an RPi. Installed using a clean install of Raspbian and using the standard setup script/method. I am running V10.2.7 "low write" according to the banner.

I've setup some 7 monitoring nodes which will log temp/pressure/humidity to the Pi, using HTTP GET and fulljson to post data.
I have configured a few feeds. I configured the backup script someone kindly posted here to archive the feeds to a local data. All good.

Until I rebooted the Rpi to check if it came back up cleanly. It doesn't ... 

Rebooting causes most of the configured feeds to break. More accurately, it will cause all of the feeds to break for some of the nodes, while some nodes continue to work fine, because the processing steps get disconnected from the inputs being sent by the nodes.

This seems to be because of duplication of the Inputs, for some strange reason.
For some example of what I see on the UI after 2 reboots of the RPi:

**An example there the original configured inputs has been duplicated twice**
![image](https://user-images.githubusercontent.com/766859/104661374-508c1780-56c0-11eb-81ba-48de10ec08b5.png)

**An example there the original configured inputs have been duplicated once**
![image](https://user-images.githubusercontent.com/766859/104661501-8a5d1e00-56c0-11eb-851c-499ec950f4d8.png)

**An example where the original configured inputs are still fine**
![image](https://user-images.githubusercontent.com/766859/104661535-a06ade80-56c0-11eb-9306-8f5cc77ea9b0.png)

Did I configure something incorrectly?
Or is this a bug?
Is there a way to diagnose this?

It will be very bad if every time the RPi reboots ... all my feeds/dashboards/graphs break ...

**Comment by liamf** [comment]
Ah. My search skillz let me down. I see there is a (closed) defect for this which suggests it's hard to reproduce, although it;s not for me I have to say ... 

And all I have to do is delete the new inputs and the old ones will come back. Which does indeed seems to work.

**Comment by borpin** [comment]
@liamf - this is better asked on the community site.

https://community.openenergymonitor.org/latest

Could you close this please.

**Comment by Bra1nK** [comment]
It's also happened to me twice in the last couple of weeks after rebooting the Pi

**Comment by liamf** [comment]
As requested by Brian above: closing.
A workaround is to keep an eye on any spurious inputs after reboot and delete those, this causes the old/correct inputs to work properly again.

**Comment by pb66** [comment]
This issue is not resolved yet, but it is a duplication of #1198.
