### ISSUE TITLE
Possible error in mqtt array conversion

### ISSUE THREAD

**Issue by Twincarb** [emoncms/emoncms#1673]
The line below I would expect to see 'keypw' 3 times in the line, I am not sure where its used apart from here so am unable to confirm the logic.

https://github.com/emoncms/emoncms/blob/4efbd9e9c43c33573d68783770b8cacf3b7ce335/Lib/process_old_settings.php#L54

**Comment by TrystanLea** [comment]
Thanks @Twincarb , @ich123 would you be able to comment on this?

**Comment by TrystanLea** [comment]
Fixed in latest commit
