### ISSUE TITLE
GLOB_BRACE does not exist on Alpine linux

### ISSUE THREAD

**Issue by inverse** [emoncms/emoncms#1680]
See: https://github.com/inverse/hassio-addon-emoncms/issues/16#issuecomment-819750768

Issue exists here: https://github.com/emoncms/emoncms/blob/master/locale.php#L23

Potential fix could be to define it to `0` as per https://github.com/zendframework/zend-stdlib/pull/59, if so where should such definitions live?

More info: https://bugs.php.net/bug.php?id=72095

**Comment by TrystanLea** [comment]
Hello @inverse perhaps adding the suggested fix at the top of locale.php would be fine? I assume that would work?
