### ISSUE TITLE
No data received from IotaWatt code 301

### ISSUE THREAD

**Issue by biva** [emoncms/emoncms#1683]
Hello,
We try to collect data from IotaWatt. We have the following issue:
`EmonService: get input list failing, code: 301`

Apparently, it's related to the way the server talks with IotaWatt, IotaWatt being unable to receive communication on port 443. This is discussed in https://community.iotawatt.com/t/emonservice-get-input-list-failing-code-301/1979

> 301 is a permanent redirect. That usually happens when a service requires https (port 443) and doesn’t respond to http (port 80). I know you say you tried both, but IoTaWatt ignores https specification and sends Emoncms transactions to port 80.

What can I change on the server to make it working? It works without problem on emoncms.org but we struggle to make it working on our own server.

**Comment by borpin** [comment]
> We try to collect data from IotaWatt.

How exactly are you trying to collect the data? Where is the error generates? In the Emoncms log?

**Comment by biva** [comment]
Thanks @borpin for your support. 

We configure the IotaWatt on our emoncms server so that we collect the data from IotaWatt. The error generates on IotaWatt logs. IotaWatt creator, Bob Lemaire, suggests that:

> 301 is the server [emonCMS] telling IoTaWatt to use a different URL to talk to it. What is probably happening is that your server wants HTTPS scheme rather than HTTP. IoTaWatt doesn’t support HTTPS directly, so the Emoncms server needs to accept HTTP.

My Apache configuration is the following:
```
<VirtualHost *:80>
ServerName emoncms.server.com
DocumentRoot /var/www/html/emoncms

<Directory /var/www/html/emoncms>
Options +FollowSymlinks
AllowOverride All
DirectoryIndex index.php
Order allow,deny
allow from all

RewriteEngine on
RewriteCond %{SERVER_NAME} =emoncms.server.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,R=permanent]
```


Maybe the RewriteEngine is the problem to force the https connection?

and for information, the ssl Apache configuration file for emoncms is:

```
<IfModule mod_ssl.c>
<VirtualHost *:443>
ServerName emoncms.server.com
DocumentRoot /var/www/html/emoncms

<Directory /var/www/html/emoncms>
Options +FollowSymlinks
AllowOverride All
DirectoryIndex index.php
Order allow,deny
allow from all

SSLCertificateFile /etc/letsencrypt/live/emoncms.server.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/emoncms.server.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
```

**Comment by borpin** [comment]
> IoTaWatt doesn’t support HTTPS directly, so the Emoncms server needs to accept HTTP.

> RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,R=permanent]

Looks like the answer is in front of you. You direct everything to https which IoTaWatt doesn't support.

If it works on emoncms.org, then it must be possible with the right `.htaccess`. No idea what that would be though 😀

**Comment by TrystanLea** [comment]
emoncms.org supports both http and https, it does not automatically force all requests to use https, it just redirects attempts to access the home page to https. Hence this does works with IoTaWatt as it is able to use http.

@biva you will need to turn off forcing the connection to use https for this to work unfortunately.

**Comment by andreszamudiofindero** [comment]
Also you could configure  a HTTPS proxy server so the IW can send the data without problem, we did that.

**Comment by biva** [comment]
Thanks All! I disabled the apache config file to force https and it works. Do you know how I could force the homepage to use https?

@andreszamudiofindero , thanks for your support: would you be able to share more details on your config and the config files?

**Comment by andreszamudiofindero** [comment]
@biva hey, glad you solved your problem. It is actually described on the newest IotaWatt documentation.

[https://docs.iotawatt.com/en/02_06_03/HTTPSproxy.html](url)

With that setup you should be able to send data either to Emoncms or Influx without problem.
