### ISSUE TITLE
feed module : scalerange function cannot write zeros

### ISSUE THREAD

**Issue by emmademareywilliams** [emoncms/emoncms#1719]
https://github.com/emoncms/emoncms/blob/e31776090d66067e15d701f154969ce8596e5e86/Modules/feed/engine/PHPFina.php#L259

the actual code can write NAN to feeds but not zeros 

the feed/scalerange.json route is used in vis module : EditRealtime

https://github.com/emoncms/emoncms/blob/master/Modules/vis/visualisations/editrealtime.php

![image](https://user-images.githubusercontent.com/85568176/128142565-0cbce5da-90c3-4ce6-b0f7-82ec63aea823.png)

**Comment by TrystanLea** [comment]
Thanks for the pull request!
