### ISSUE TITLE
Problem displaying dashboard and menus

### ISSUE THREAD

**Issue by mirapolacek1** [emoncms/emoncms#1721]
After the update, I have a problem displaying the menu and dashboard in my account 35131. After logging in, I only see saved fields and updated data. I don't see anything else. Please help.
![Prtscr](https://user-images.githubusercontent.com/88624426/128637134-908ef165-d51d-41d8-b0c0-aa20e3b9bc56.jpg)

**Comment by TrystanLea** [comment]
Issue solved I think on the forum?
