### ISSUE TITLE
Any attempt to delete feed's old data results with PHP fata error.

### ISSUE THREAD

**Issue by warpme** [emoncms/emoncms#1729]
I'm trying to clear old data in my feeds, but every attempt to do so i'm receiving PHP Fata error. 

`[Mon Sep 06 19:03:15.113799 2021] [php7:error] [pid 2307753] [client 192.168.1.9:62632] PHP Fatal error:  Uncaught Error: Call to a member function hExists() on bool in /var/lib/emoncms/www/Modules/feed/feed_model.php:227\nStack trace:\n#0 /var/lib/emoncms/www/Modules/feed/feed_controller.php(274): Feed->clear()\n#1 /var/lib/emoncms/www/core.php(71): feed_controller()\n#2 /var/lib/emoncms/www/index.php(240): controller()\n#3 {main}\n  thrown in /var/lib/emoncms/www/Modules/feed/feed_model.php on line 227, referer: http://xxxx/emoncms/feed/view`

My system:
<details><summary>Server Information</summary>

# Server Information
## Emoncms
 
- **Version** :- 10.7.7
- **Git** :- 
     - **URL** :- origin
     - **Branch** :- - **Describe** :- - **Components** :- Emoncms Core v10.7.7 | App v2.3.0 | Dashboard v2.1.5

## Server
 
- **OS** :- Linux 5.10.16-arch1-4
- **Host** :- mythtv | mythtv | (31.178.191.245)
- **Date** :- 2021-09-06 19:09:30 CEST
- **Uptime** :- 19:09:30 up 11 days,  4:22,  2 users,  load average: 0.68, 0.90, 0.98

## Memory
 
- **RAM** :- Used: 48.82%
    - **Total** :- 3.74 GB
     - **Used** :- 1.83 GB
     - **Free** :- 1.91 GB
- **Swap** :- Used: 10.51%
    - **Total** :- 11.43 GB
     - **Used** :- 1.2 GB
     - **Free** :- 10.23 GB
Write Load Period
 
## Disk
- **/** :- Used: 41.67%
    - **Total** :- 23.5 GB
     - **Used** :- 9.79 GB
     - **Free** :- 12.49 GB
     - **Write Load** :- n/a
- **/dev** :- Used: 0.00%
    - **Total** :- 1.86 GB
     - **Used** :- 0 B
     - **Free** :- 1.86 GB
     - **Write Load** :- n/a
- **/run** :- Used: 0.06%
    - **Total** :- 1.87 GB
     - **Used** :- 1.06 MB
     - **Free** :- 1.87 GB
     - **Write Load** :- n/a
- **/media/mirror.vol** :- Used: 39.24%
    - **Total** :- 23.5 GB
     - **Used** :- 9.22 GB
     - **Free** :- 13.06 GB
     - **Write Load** :- n/a
- **/myth** :- Used: 99.52%
    - **Total** :- 3.62 TB
     - **Used** :- 3.6 TB
     - **Free** :- 17.89 GB
     - **Write Load** :- n/a
- **/myth/video** :- Used: 98.34%
    - **Total** :- 7.28 TB
     - **Used** :- 7.15 TB
     - **Free** :- 123.67 GB
     - **Write Load** :- n/a
- **/myth/tv1** :- Used: 99.47%
    - **Total** :- 3.63 TB
     - **Used** :- 3.61 TB
     - **Free** :- 19.63 GB
     - **Write Load** :- n/a

## HTTP
 
- **Server** :- Apache/2.4.46 (Unix) PHP/7.4.12 HTTP/1.1 CGI/1.1 80

## MySQL
 
- **Version** :- 5.5.5-10.5.8-MariaDB
- **Host** :- localhost (127.0.0.1)
- **Date** :- 2021-09-06 19:09:30 (UTC 02:00‌​)
- **Stats** :- Uptime: 966114  Threads: 55  Questions: 26283362  Slow queries: 167  Opens: 8768  Open tables: 347  Queries per second avg: 27.205

## PHP
 
- **Version** :- 7.4.12 (Zend Version 3.4.0)
- **Modules** :- apache2handler apc v5.1.18apcu v5.1.19Core ctype curl date dom v20031129fileinfo filter ftp gd gettext hash json libxml mbstring mcrypt v1.0.3mysqli mysqlnd vmysqlnd 7.4.12openssl pcre PDO pdo_mysql Phar posix Reflection session SimpleXML sockets SPL standard tokenizer xml xmlreader xmlwriter zip v1.15.6zlib
</details>

<details><summary>Client Information</summary>

# Client Information
## HTTP
 
- **Browser** :- Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15
- **Language** :- pl-pl

## Window
 
- **Size** :- 1188 x 682

## Screen
 
- **Resolution** :- 1440 x 900
</details>

**Comment by TrystanLea** [comment]
Hello @warpme thanks for spotting this, it looks like I was missing a check for redis, now fixed in the master branch https://github.com/emoncms/emoncms/commit/4952006c784002da821178e248425feec18ed4de 

If your pulling in changes from the latest master branch, note that you will also need to update the app, graph and dashboard modules as well. Thanks!
