### ISSUE TITLE
Log level change from the Admin UI 

### ISSUE THREAD

**Issue by chaveiro** [emoncms/emoncms#1731]
Hi @TrystanLea 
Where is this **$path_to_config** https://github.com/emoncms/emoncms/blob/f1c5ee0c58b722e128961cf0ceac6175a7c2d0e7/Modules/admin/emoncms_log_view.php#L34 variable coming from and what is missing to make the Log level change from the UI?
Was this an aborted feature ?

**Comment by chaveiro** [comment]
Hi, take a look at this screenshot, this is how it looks like with your old (and current code).
Is is supposed to look like that on chrome?
![image](https://user-images.githubusercontent.com/4527135/134552572-500f4477-b373-4e1b-936a-e51eb1e8cf70.png)

**Comment by TrystanLea** [comment]
Interesting, in firefox the scroll bar looks like:

![image](https://user-images.githubusercontent.com/503186/140502291-9de6e079-4da3-4033-9df3-3ba154af594a.png)

on chrome: 

![image](https://user-images.githubusercontent.com/503186/140502408-740bca60-93fa-41d6-aec5-affc89bc1c9f.png)

not quite as nice as the firefox version...
