### ISSUE TITLE
Menu l3 width

### ISSUE THREAD

**Issue by chaveiro** [emoncms/emoncms#1741]
Hi @TrystanLea 
I've put this to 280 + 50 px but you reset to original. The change i've made was to mitigate vertical scroll bar as below.
https://github.com/emoncms/emoncms/blob/5be844623fdc3b32e16a4c3a70c221c90718822b/Lib/menu/menu.js#L309

![image](https://user-images.githubusercontent.com/4527135/139542171-3fa91482-fd0a-4ca5-9645-6e8c64939c3d.png)

**Comment by TrystanLea** [comment]
ooo this looks like a chrome thing, I dont see any scrollbars in firefox, will look into it. 

It should look like this:

![image](https://user-images.githubusercontent.com/503186/140499884-3005b4b1-721d-476c-b7c8-80260f7be90b.png)

**Comment by TrystanLea** [comment]
Here's the fix: https://github.com/emoncms/emoncms/commit/c4ead0823ef5dcdca94dcd77209fff16600389b5

Needed: 

```
.menu-l2-inner::-webkit-scrollbar {
  display: none;
}

.menu-l3::-webkit-scrollbar {
  display: none;
}
```
