### ISSUE TITLE
Broken Virtual Feeds

### ISSUE THREAD

**Issue by g0lgs** [emoncms/emoncms#1759]
I am not sure how it happened, but one of my emonPi's was using the 'master' dist (based on the 24 Jul 20 SD Build) - and I noticed yesterday that the Virtual Feed I created to take the current daily kWh figure and calculate a current daily cost on my dashboard was suddenly showing a zero value, and when I tried to add a new virtual feed I got silly results too.

My other emonPi on the same base image but on 'stable' was fine.

Having reverted to 'stable' and performed an update it now appears to be back to normal.

**Comment by TrystanLea** [comment]
Hello @g0lgs interesting, the master branch has a new implementation of virtual feeds, the plan is to merge this into stable soon so it would be good to understand what is going wrong with your feeds.

What is the feed engine of the source daily kWh feed that you are using? and are you then just applying a simple multiplication?

**Comment by TrystanLea** [comment]
Can you give any details on the particular visualisation type that you are using as well, to show the cost information?

**Comment by g0lgs** [comment]
Hopefully these screen shots will clarify how I have things configured.

![image](https://user-images.githubusercontent.com/64634584/141076058-230bd9ea-0962-40ca-8e17-698fa79717df.png)
![image](https://user-images.githubusercontent.com/64634584/141074966-f57311b1-54b3-48dc-aa84-3dde95f7b596.png)
![image](https://user-images.githubusercontent.com/64634584/141074801-35169741-0d3d-48f8-a99b-3ad7b3f18f9f.png)
![image](https://user-images.githubusercontent.com/64634584/141075251-f8c87191-5af6-401d-bb16-e02944795434.png)

This is the element on the Dashboard:

![image](https://user-images.githubusercontent.com/64634584/141075383-d1d3b984-a47d-428a-ac25-dd7e0aceac7d.png)

**Comment by TrystanLea** [comment]
Thanks @g0lgs I think that's enough for me to go on, probably a small fix I need to make to that dashboard element to request the data properly in line with the new api. Thanks!

**Comment by g0lgs** [comment]
@TrystanLea Glad that seems to have helped.

One comment when it comes to editing the Dashboard is that (unless I'm missing something) it is almost impossible to tell, unless you are familiar with all the different 'Elements' which element type you are editing and so makes it harder to re-produce  a similar configuration for a Dashboard on more than one emonPi.

**Comment by Bigben83** [comment]
Hi @TrystanLea yes, i did a git pull on the master 2 days ago and now can't view any apps I have set up. 
this is the error I am getting.
![image](https://user-images.githubusercontent.com/6385918/141199770-669d165f-dd72-4833-8c67-5b32a89e6f74.png)
![image](https://user-images.githubusercontent.com/6385918/141200079-64b5b0b3-597f-4795-a370-7ecfcd67c61d.png)
![image](https://user-images.githubusercontent.com/6385918/141200242-5b3f4585-d35d-40e3-a419-72b39162aa6b.png)

I also seem to have issues signing in.
This instance is running on Linux and has been for about 4 years. Every month or so I do a git pull to get the improvements.

**Comment by TrystanLea** [comment]
@Bigben83 you will also need the latest apps, dashboard, graph and device module with this latest update. Id go through each module and check for updates, that should sort your error.

**Comment by Bigben83** [comment]
Thanks @TrystanLea yes i have done this and it still doesnt seem to be working correctly.

`/bin/bash /home/dev/public_html/emoncms/update_emoncms.sh

Update emoncms....
Already up to date.

Update emoncms/app....
Already up to date.
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
2.3.4-5-g5c776d2

Update emoncms/dashboard....
Already up to date.
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
2.1.5-8-g4764db0

Update emoncms/emailreport....
Already up to date.
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
fatal: No names found, cannot describe anything.

Update emoncms/graph....
Already up to date.
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
2.1.1-8-g2da3007`

Ill keep trying to hunt the issue down.

**Comment by TrystanLea** [comment]
Hello @g0lgs I've fixed the virtual feed issue in the latest master branch, working fine now.

@Bigben83 could you open a new issue if your problem is persisting as this is a different topic. Cheers.
