### ISSUE TITLE
Error when trying to view existing apps

### ISSUE THREAD

**Issue by Bigben83** [emoncms/emoncms#1766]
Hi @TrystanLea yes, i did a git pull on the master 2 days ago and now can't view any apps I have set up. 
this is the error I am getting.
![image](https://user-images.githubusercontent.com/6385918/141199770-669d165f-dd72-4833-8c67-5b32a89e6f74.png)
![image](https://user-images.githubusercontent.com/6385918/141200079-64b5b0b3-597f-4795-a370-7ecfcd67c61d.png)
![image](https://user-images.githubusercontent.com/6385918/141200242-5b3f4585-d35d-40e3-a419-72b39162aa6b.png)

I also seem to have issues signing in.
This instance is running on Linux and has been for about 4 years. Every month or so I do a git pull to get the improvements.

_Originally posted by @Bigben83 in https://github.com/emoncms/emoncms/issues/1759#issuecomment-965784780_

**Comment by Bigben83** [comment]
I also get an error when trying to delete an existing app.
![image](https://user-images.githubusercontent.com/6385918/144135625-41268761-9df8-44c5-bb46-2792ecf0e452.png)

**Comment by Bigben83** [comment]
also the input feeds arent showing when you try and setup a new app.
<img width="211" alt="2021-12-01 (2)" src="https://user-images.githubusercontent.com/6385918/144135980-6da23a48-4e98-4c47-9d98-e05f6df84f11.png">

**Comment by TrystanLea** [comment]
Hello @Bigben83 it looks like you are still running the emoncms stable branch for core? If you have updated the apps module to the latest master you also need to update core to the latest master. Hope that helps

**Comment by Bigben83** [comment]
Thank you @TrystanLea how silly could I be. all up and running again now MT.
