### ISSUE TITLE
scripts/phpmqtt_input.php tries to use Redis even if it isn't enabled

### ISSUE THREAD

**Issue by jamesfidell** [emoncms/emoncms#1772]
This script doesn't throw an error if Redis isn't enabled (though it does if Redis is enabled and it can't connect), just setting $redis to false.  In the main publish loop it then attempts to use $redis regardless of whether it is valid or not.

I believe the same issue exists in scripts/services/emoncms_mqtt/emoncms_mqtt.php

**Comment by TrystanLea** [comment]
thanks for the pull request
