### ISSUE TITLE
PHP 8.1 issue

### ISSUE THREAD

**Issue by thib66** [emoncms/emoncms#1776]
Hello,
the migration from PHP 8.0 to 8.1 generates somme errors when trying to logon : 
![image](https://user-images.githubusercontent.com/29287201/149581273-c0372a80-0960-46a3-bed6-95eb51ab412e.png)
![image](https://user-images.githubusercontent.com/29287201/149581593-70dbe8b6-0872-4fd8-95e8-9cd6af5c86f5.png)

In details : 
Deprecated: Constant FILTER_SANITIZE_STRING is deprecated in /www/emoncms/locale.php on line 130

Deprecated: stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /www/emoncms/core.php on line 113

Deprecated: stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /www/emoncms/core.php on line 144

Deprecated: stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /www/emoncms/core.php on line 144

Deprecated: stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /www/emoncms/core.php on line 113

Deprecated: parse_str(): Passing null to parameter #1 ($string) of type string is deprecated in /www/emoncms/Modules/user/user_controller.php on line 35

Deprecated: stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /www/emoncms/core.php on line 113

Deprecated: stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /www/emoncms/core.php on line 113

Deprecated: Constant FILTER_SANITIZE_STRING is deprecated in /www/emoncms/Modules/user/user_controller.php on line 38

Deprecated: Constant FILTER_SANITIZE_STRING is deprecated in /www/emoncms/locale.php on line 130

Deprecated: stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /www/emoncms/core.php on line 144

Deprecated: stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /www/emoncms/core.php on line 144

Deprecated: stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /www/emoncms/core.php on line 113
{"success":true,"message":"Connexion r\u00e9ussie","startingpage":"user\/view"}

**Comment by thib66** [comment]
A solution is proposed here : https://github.com/emoncms/emoncms/pull/1777.

Nevetheless, I am not sure that htmlspecialchars() is the correct function to replace the deprecated constant FILTER_SANITIZE_STRING.

@glynhudson @TrystanLea , as the substitution of FILTER_SANITIZE_STRING with another non deprecated PHP function has an impact of the global security of the application. I would like to have your opinion.

Do we use htmlspecialchars() or do we use another function ?
Thanks in advance for your answer.

**Comment by thib66** [comment]
There is also another issue when typing wrong credentials : 
![image](https://user-images.githubusercontent.com/29287201/150301267-a9cd13de-4826-48d0-a08d-2e1391080931.png)
A solution is proposed here : #1777.

**Comment by thib66** [comment]
New issue met in vis module : 
![image](https://user-images.githubusercontent.com/29287201/151857957-84c9834b-5f6d-49ad-b1e0-1dfeded114d1.png)
fix also proposed in #1777

**Comment by TrystanLea** [comment]
all fixed now I believe? closing for now
