### ISSUE TITLE
top menu disappears on mobile

### ISSUE THREAD

**Issue by alexandrecuer** [emoncms/emoncms#1781]
![Screenshot_20220205-182151_Firefox](https://user-images.githubusercontent.com/24553739/152652064-35b60804-107c-4b7a-a36a-fc6e0b6485ca.jpg)
Version 11.0.1
Needed to refresh to make it visible again

**Comment by chaveiro** [comment]
If it appears when you scroll up or to top all is fine. It's a feature to save screen space.
