### ISSUE TITLE
Update Feed Units and include new element of Device Class to match HA

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#1783]
@TrystanLea - could the Feed Units be updated so the is a more complete list and so that it matches that available in Home Assistant?

3 immediately strike me;

ppm
µg/m³
m³

**Comment by TrystanLea** [comment]
Sure, done: https://github.com/emoncms/emoncms/commit/cce439d9893f12a16dae6eee62ff65984660d9e6
