### ISSUE TITLE
Extra data points appear when reading from MySQL TimeSeries

### ISSUE THREAD

**Issue by MrTimbones** [emoncms/emoncms#1786]
I have a MYSQL TimeSeries feed that contains a data point on every half-hour:

![image](https://user-images.githubusercontent.com/75039652/156449962-cff10251-cbdc-494f-a49f-cc1c9e169a08.png)

If I were to ask Feed API to give me data points between 13:00 and 14:00 (skipping nulls), I would expect to get just three points...

![image](https://user-images.githubusercontent.com/75039652/156449480-df02f961-a507-4213-a650-ffdc9ee3e679.png)

Yet what I actually get is 2 extra points at `13:29` and `13:59` which happen to be _interval_ seconds before the actual datapoints. 
Changing the _interval_ moves those points by that same amount.

```
 [[ "02/03/2022 13:00:00", 301.1 ],
  [ "02/03/2022 13:29:00", 413.7 ],
  [ "02/03/2022 13:30:00", 413.7 ],
  [ "02/03/2022 13:59:00", 242.5 ],
  [ "02/03/2022 14:00:00", 242.5 ]]
```

Graphically, the results look like this (with interval set to 300 seconds):

![image](https://user-images.githubusercontent.com/75039652/156450869-cb75c6cd-25c3-4baa-9351-2cf528eab946.png)

I also see the same with another feed that has data every 15 minutes, yet some other MSQL feeds with more frequent/random data don't show this. Regular PHPFINA / PHPTimeSeries feeds seem to be ok.

Is this expected behaviour? Or have I misunderstood something?

I'm using EmonCMS 11.0.5-2-g11a72958 on a self-hosted VPS. I didn't notice this happening before I upgraded to version 11.

**Comment by TrystanLea** [comment]
Hey Tim, yes this is an expected artefact of the implementation, if you set the interval to 1800 it should return as expected.
