### ISSUE TITLE
Export download not functioning using Edge browser

### ISSUE THREAD

**Issue by MikeBookham** [emoncms/emoncms#1787]
**Downloading a backup after the Export function has completed**
I have noticed a couple of issues in the latest stable release (low-write 11.0.5) & also the previous stable release:
1. On both the Edge & Chrome browser there is no option to download using right-click (as indicated on the webpage).
2. On the Edge browser left clicking initiates a download request as seen in the download window of the browser, however no data is downloaded and it eventually fails with the error 'Couldn't download - network error'. Right clicking on the hyperlink and selecting open in a new tab will very occasionally complete a download. 

Using Chrome is a workaround, however I now need to have Chrome installed for just this single function.

**Comment by borpin** [comment]
This is probably because it is a non-SSL connection. Open the page in IE mode and it will probably work.
