### ISSUE TITLE
System Service status improvements

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#1802]
The system service interface is excellent as is the ability to control services.

However, the enabled/disabled state is not reflected in the status text.

Note difference in the 'Loaded' text.

When disabled
```
pi@emonpi:/var/www/emoncms $ systemctl status demandshaper.service
● demandshaper.service - Emoncms Demandshaper service
   Loaded: loaded (/lib/systemd/system/demandshaper.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: https://github.com/emoncms/demandshaper/blob/master/readme.md
```
when enabled
```
pi@emonpi:/var/www/emoncms $ systemctl status demandshaper.service
● demandshaper.service - Emoncms Demandshaper service
   Loaded: loaded (/lib/systemd/system/demandshaper.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: https://github.com/emoncms/demandshaper/blob/master/readme.md

```

When stopped, the 'stop' button disappears.

I suggest that
* When enabled only the disabled button is available and Visa versa
* When Started only the Stop button is available and visa versa.
* Add in a note stating that 'disable' prevents auto-restart at boot as users may not understand the difference between stopping and disabling.

**Comment by borpin** [comment]
Bump

**Comment by TrystanLea** [comment]
Improved a bit further: https://github.com/emoncms/emoncms/commit/4b46db06655bbd957eceb7cbd18202135b9a7cad

![image](https://user-images.githubusercontent.com/503186/230427618-30a3147f-19f8-49d2-9787-b877f598a337.png)
