### ISSUE TITLE
My Electric app showing kWh for cost

### ISSUE THREAD

**Issue by techfixpros** [emoncms/emoncms#1807]
RPi 3B+
Raspbian Buster
emonCMS 11.0.9

The My Electric app shows the same numeric value for both kWh and cost on the app dashboard. The displayed MQTT value, and the value in the My Electric 2 is correct. I have deleted all app dashboards, and re-created, and the issue persists.
The parameters selected in both My Electric and My Electric 2 are use: power1pluspower2, and use_kWh: power1pluspower2_kWh for both apps.
![image](https://user-images.githubusercontent.com/7028086/172275994-823cc515-4463-48c4-bfae-cb5e4485b66f.png)
![image](https://user-images.githubusercontent.com/7028086/172276027-f5fb253d-97e1-4a8f-a40f-25dc0f08de79.png)
![image](https://user-images.githubusercontent.com/7028086/172276055-9eb4fdb8-e012-4e4b-9c0b-86e9ec6745bf.png)
![image](https://user-images.githubusercontent.com/7028086/172276087-7bf91fcd-cd2f-4708-99bd-82322ee1f73a.png)
![image](https://user-images.githubusercontent.com/7028086/172276140-aab37baf-f86f-43de-a61e-615d5684398e.png)

**Comment by techfixpros** [comment]
The mobile android app v2.3.0 also displays correctly.
![Screenshot_20220608-105108_Emoncms.jpg](https://user-images.githubusercontent.com/7028086/172661517-e01adcb2-8796-4dad-97b0-ea2292c74229.jpg)

**Comment by cricalix** [comment]
Hah. I just filed this as https://github.com/emoncms/app/issues/174.
I'll hopefully get a chance to poke it tonight, and if I can fix it, I'll post a PR and we can hope it gets accepted.

**Comment by cricalix** [comment]
@techfixpros Fix is attached to that other issue. If you're comfortable editing code on the Pi, it should be an easy fix to apply locally.

**Comment by techfixpros** [comment]
Issue is resolved in main update.
