### ISSUE TITLE
Display kW/h per day/month/year

### ISSUE THREAD

**Issue by fohnbit** [emoncms/emoncms#1817]
Hello!

I upload the kW/h counter from my meter.
So I have for example:
134.56
134.89
134.99
...

How can I display the comsumption sum for a day, week, month and year?

I use "**kW/h to kW/h each day**" and display as bar chart .. but it seems the values are to low.

**Comment by TrystanLea** [comment]
Hello @fohnbit please see this documentation page if this is still of  interest https://docs.openenergymonitor.org/emoncms/daily-kwh.html
