### ISSUE TITLE
Virtual feeds always zero

### ISSUE THREAD

**Issue by greentangerine** [emoncms/emoncms#1831]
Seems recent changes have rendered virtual feeds as permanently zero (although if you look at the graph/data, you can see it).

![2023-01-09 (4)](https://user-images.githubusercontent.com/14904810/211345221-160059bf-9e2b-4608-a567-842cbfa13284.png)
![2023-01-09 (3)](https://user-images.githubusercontent.com/14904810/211345227-84a794a8-91a7-4844-b9a8-cd8ba8517e51.png)
![2023-01-09 (2)](https://user-images.githubusercontent.com/14904810/211345228-c63134a5-0c10-4e8c-bdaa-148abb1c1651.png)
![2023-01-09 (5)](https://user-images.githubusercontent.com/14904810/211345230-4a9e147e-3f9e-4dcf-892e-9f0c22d914ec.png)

**Comment by tatou100** [comment]
I'm also experiencing the same issue with 11.2.10.

**Comment by TrystanLea** [comment]
Thanks, this is now fixed in 11.2.11
