### ISSUE TITLE
Warning in log in EditRealtime.

### ISSUE THREAD

**Issue by yewtc** [emoncms/emoncms#1832]
`[Sun Jan 15 12:49:22.920801 2023] [php7:notice] [pid 28649] [client x.x.x.x43516] PHP Notice:  Undefined variable: vis_version in /var/www/emoncms/Modules/vis/visualisations/editrealtime.php on line 18, referer xxxx
`
The error log has the above error message after selecting "EditRealtime".

**Comment by alexandrecuer** [comment]
This is a duplicate of this, isn'it ?
https://github.com/emoncms/emoncms/issues/1821
