### ISSUE TITLE
Link to "New: Debian build script" is dead

### ISSUE THREAD

**Issue by bonjour81** [emoncms/emoncms#1846]
On the emoncms main pagehere https://github.com/emoncms/emoncms     , the link [New: Debian build script](https://github.com/openenergymonitor/EmonScripts/tree/master/install/readme.md) is dead

**Comment by borpin** [comment]
Fixed.

Any comments on using Debian appreciated as it is a generally unused distro. Personally I use Ubuntu as I know it works (20.04 *not* 22).

**Comment by bonjour81** [comment]
Thanks for correction. It seems not yet visible but I can follow the pull request to find the link.
I'll keep you in touch about install. It will be on a fresh debian install on a wyse3040 hardware.
(I currently use emoncms on docker but for mqtt, last updates etc, I will move on a dedicated device)

**Comment by borpin** [comment]
No it won't until it gets merged.
