### ISSUE TITLE
High ram usage in emoncms_mqtt service

### ISSUE THREAD

**Issue by dazz1in** [emoncms/emoncms#1855]
Using the latest RPi 32bit Lite OS and emoncms install scripts.  The pi becomes unresponse after a few hours due to being out memory.

using top emoncms_mqtt.php consumes all available memory.

See https://community.openenergymonitor.org/t/emoncms-mqtt-php-very-high-ram-use/23309 for more details

**Comment by TrystanLea** [comment]
This is now fixed since phpredis 6.0.1 :+1:
