### ISSUE TITLE
Problems accessing dashboards without being logged in.

### ISSUE THREAD

**Issue by jvm1000** [emoncms/emoncms#1857]
Hello, 
accessing the dashboard without being logged in does not work when using the dashboard alias. 
For example,
    when logged in, 

http://192.135.131.24/dashboard/view/acs works perfectly, 
http://192.135.131.24/dashboard/view?id=2 works perfectly 

However, when not logged in, 
 http://192.135.131.24/dashboard/view/acs does not work, 
 while accessing http://192.135.131.24/dashboard/view?id=2 without logging in still works perfectly. 

All dashboard with public an published activated

I hope my comment is helpful. 
Version low-write 11.3.0.

**Comment by chaveiro** [comment]
should be fixed at latest version
