### ISSUE TITLE
PHP Warning:  Undefined array key "hw" in /var/www/emoncms/Modules/admin/Views/admin_main_view.php on line 235

### ISSUE THREAD

**Issue by reedy** [emoncms/emoncms#1903]
https://github.com/emoncms/emoncms/blob/aee5e2f/Modules/admin/Views/admin_main_view.php#L235

**Comment by borpin** [comment]
This is probably related to your previous issues I guess.

**Comment by reedy** [comment]
It's not.

https://github.com/emoncms/emoncms/commit/6b4d93dc230c75da97d9c9c008c57a263f0d1c85 stopped it being set.

```
<!-- <?php echo row(_('SoC'), $rpi_info['hw']) ?> -->
```

^ HTML commenting it doesn't stop PHP executing it.
