### ISSUE TITLE
daily phpfina feeds off 1 day

### ISSUE THREAD

**Issue by gloorung** [emoncms/emoncms#199]
Daily stats using the phpfina engine are logged with yesterday's date as the timestamp. MySQL feeds are logged on the correct date. 

When looking at the update operator in PHPFina.php, I noticed on line 135 that the timestamp is updated using floor(timestamp/interval)*interval but the interval value for daily feeds corresponds to 86400s or 24h which makes that the timestamp is always 1 day in the past. 

I'm not familiar with how realtime data is best stored, but rounding to the nearest integer would in this case do the trick.

Gloorung

**Comment by chaveiro** [comment]
Fixed on https://github.com/emoncms/emoncms/pull/303
