### ISSUE TITLE
MyElectric locale language on smartphone

### ISSUE THREAD

**Issue by euqip** [emoncms/emoncms#203]
Because MyElectric seems to be used with a smartphone or tablet without necessarilly beginning with a session, it uses the apikey to identify user.
In order to make the MyElectric page translatable to user's language, I propose to adjust the myelectric_menu.php to the following:

<?php
$domain = "messages";
//bindtextdomain($domain, "Modules/admin/locale");
bindtextdomain($domain, dirname(**FILE**)."/locale");
//bind_textdomain_codeset($domain, 'UTF-8');
global $session, $user;
if ($session['write']) $apikey = "?apikey=".$user->get_apikey_write($session['userid']); else $apikey = "";
$menu_left[] = array('name'=>dgettext($domain,"My Electric"), 'path'=>"myelectric".$apikey , 'session'=>"write", 'order' => -2 );
?>

Otherwize, the interface will always be in default language.

Hope it will help.

**Comment by glynhudson** [comment]
Sorry for the ridiculously long delay on this, in the meantime the file concerned had morphed into https://github.com/emoncms/app/blob/9.0/app_menu.php. Adding locale is a good idea. Could you make this into a pull request? I'll get it merged ASAP. Thanks a lot

**Comment by euqip** [comment]
My emoncms version is not yet at 9 and the code I have will probably not fit into the present situation.
I'll do it after having upgraded.

**Comment by euqip** [comment]
Hi glynhudson,
Could you please check the 2 pull requests done to enable multilingual App module.  JS files have been jslinted and html files have been cleaned has much as possible from css instructions, to includ a specific class 'i18n'.
Translation files are JS files located in app/locale.  I made a reference, an english one and a french one.  For more languages just duplicate the reference (app_ref.js) with a correct name (app_xx.js), and translate the content. 
Rem : Dashboards will not display if your language file is not present.  I will try to find a simple solution. Language selection is made in URI.

Hope it will help.

Why do EMONCMS still use jquery 1.11 and an old bootstrap 2 dated from 2012?
Bootstrap 3 with awesome fonts is reponsive and easy to implement.
