### ISSUE TITLE
Build script proposition 

### ISSUE THREAD

**Issue by inverse** [emoncms/emoncms#212]
I propose that we introduce a build step into the application, perhaps using gulp.

This would enable pre-processing, linting, minimizing the css/js/images and pushing into an public assets directory. 

We could also use bower to obtain a lot of assets we are already using.

    {
      "name": "emoncms",
      "homepage": "https://github.com/emoncms/emoncms",
      "dependencies": {
        "listjs": "~1.1.1",
        "bootstrap-datetimepicker": "~0.0.11",
        "flot": "~0.8.3",
        "jquery": "~2.1.1",
        "bootstrap-css": "2"
      }
    }

Opinions?

**Comment by Paul-Reed** [comment]
Thanks for the suggestion, however it doesn't appear to have gained much support, but something that perhaps we could consider for future development.
