### ISSUE TITLE
Missing 15Minute interval

### ISSUE THREAD

**Issue by mircsicz** [emoncms/emoncms#218]
I'm transmitting data every 15Min's and would like to export it in that same raster too.

As this is the common resolution for getting quote's from electric energy companies I judge this as highly important...

**Comment by chaveiro** [comment]
Can be closed as implemented.
https://github.com/chaveiro/emoncms/commit/d8014796e0a7950407ae4e84de86e759e0d86b14

**Comment by mircsicz** [comment]
Awesome

Von meinem 4,7" iOS Gerät gesendet
