### ISSUE TITLE
Nodes only numbered between 1 and 30

### ISSUE THREAD

**Issue by xpix** [emoncms/emoncms#219]
Hello, it is possible to have Node numbers > 31. If i try to call:

http://emoncms.org/api/post.json?apikey=***&node=130&json={data1:2425,data2:3020,v:2851}

I got an HTTP:200 but i don't see this in my Input list, if i change to node=13, thats listed. The jeelib has only Nodes from 1-31, the author of jeelib say "use subnodes as additional info in ur payload" ... i did it, but i cant use my subnode ("physical node" concat ""subnode = 130) ... can we allow Nodenumbers from 1 ... 65000 in input feed?

**Comment by chaveiro** [comment]
V9.1+ allow to use any string for nodes names, maximal different supported nodes  can be configured on configuration.php
