### ISSUE TITLE
In Export, selecting interval shorter than data fails

### ISSUE THREAD

**Issue by LorenAmelang** [emoncms/emoncms#220]
The clue below the parameter choices says:
Feed intervals: if the selected interval is shorter than the feed interval the feed interval will be used instead

That appears to be not true. If I select a shorter interval I get a new web page with a single word "false". 

The estimated file size is calculated from the chosen interval rather than the feed interval, which I guess means the feed interval really isn't being used. 

The "false" page also happens if the Timezone field is blank. It would be nice to have a clue for how to enter the timezone...

**Comment by Paul-Reed** [comment]
Now fixed in v9
