### ISSUE TITLE
Use of decimal separator in CSV export

### ISSUE THREAD

**Issue by njberland** [emoncms/emoncms#222]
I export data as a CSV file. For values above 1000 the code insert a comma decimal separator. This of course creates some problems when parsing the values.
I believe it is better to not use any decimal separator as most CSV files should be read by computers and not humans.

**Comment by Paul-Reed** [comment]
It's been almost 12 months since posting and many changes have been in the code which deals with  the exporting of data. If this is still an issue, please let us know and we'll try and resolve it. I suspect that it has been sorted already due to the absence of other reports.
