### ISSUE TITLE
Division by zero in <b>/var/www/emoncms/Modules/feed/engine/PHPFina.php error

### ISSUE THREAD

**Issue by Teslafly** [emoncms/emoncms#229]
I am Getting this error:

<br /> <b>Warning</b>: Division by zero in <b>/var/www/emoncms/Modules/feed/engine/PHPFina.php</b> on line <b>96</b><br /> <br /> <b>Warning</b>: Division by zero in <b>/var/www/emoncms/Modules/feed/engine/PHPFina.php</b> on line <b>110</b><br /> ok

When I try to send a json string to "Emoncms version: 8.3.5" using a node red flow on a rasberry pi. Any idea what could be causing this? I haven't changed anything on the node red side and evetything was working fine until I updated emoncms.

Here is the json string that generated the error:
http://127.0.0.1/emoncms/input/post.json?node=21&json=[13,683,184,110,108,120,172]&apikey=(api key redicated)

EDIT:
Despite the error, values seem to be showing up properly.

**Comment by Paul-Reed** [comment]
Have tried, but can't replicate this issue in v9.
Please repost if you are still having issues.
Thanks
