### ISSUE TITLE
Suggestion for the new "Inputs" view

### ISSUE THREAD

**Issue by pb66** [emoncms/emoncms#230]
Hi Trystan, I like what you've done to the inputs view, much better having the processlist accessible from same screen.

I know you have other items up your sleeve from discussions we've had on emonHub issues, just wondered if I could make a couple of suggestions regards the layout..

Would it be possible to allocate each node a name? and for the current collapsible view to default to closed so that when you first navigate to the input view you find just a list of nodes like this

![emoncms_inputs1](https://cloud.githubusercontent.com/assets/5606042/3787977/2a47aabe-1a48-11e4-9d11-292fcd4cced7.png)

with the customary buttons on the far right for editing the nodes name and deleting the whole node (the spanner probably wouldn't be needed)

But then when you open the collapsible view and see the inputs as we currently do....

![emoncms_inputs2](https://cloud.githubusercontent.com/assets/5606042/3787982/7698cb14-1a48-11e4-99f8-8c09cb700859.png)

...and when we click the spanner to see the processlist could it open there in the input list rather than the top of the page? I've just photoshopped the current processlist into an input list, I'm sure it could be much clearer and tidier than this mock up. 

![emoncms_inputs3](https://cloud.githubusercontent.com/assets/5606042/3787994/56605366-1a49-11e4-86fd-04d18d1719f6.png)

A second click of the inputs spanner could close it again or if a different inputs spanner is clicked this processlist closes and the "clicked" input's processlist opens.

Just thought it could be quite neat for the processlist to be in another collapsible panel within the input.

Paul

**Comment by chaveiro** [comment]
Processlist config on v8.6+ is now modal.
