### ISSUE TITLE
Suggestion for new process action

### ISSUE THREAD

**Issue by aleszuin** [emoncms/emoncms#233]
Hello, 
after purchasing the bundle of Open Energy Monitor  i'm learning emoncms;

Meanwhile, I want to congratulate because I find it very useful and easy to configure. 

In my experience I have found a lack of use so that I explain problem and solution i found: 

There should be a different solution give me to know, or possibly 
 please take the introduction of the change in the official trunk of the project. 

I am not aware if the processing can be activated from the feed rather than inputs; 
each chain input may alter the value so it becomes no longer available; 
you can't enable parallel processing of the same input; 

I solved this way: 

need 3 parallel process:
input  + -> process1 (input altered, such as "allow negative") 
          + ---> process 2 
          + ----> process 3 

is not possible,  so: 

input + -> process1 -> restore input -> process 2 -> restore input ----> process 3 

and this is my modification to the file "process_model.php" 

(...) 
         $ list [35] = array (_ ("Last Feed value"),ProcessArg::FEEDID,"last_feed_value",1,DataType::REALTIME,"Misc",array(Engine::PHPFIWA,Engine::PHPFINA,Engine::PHPTIMESERIES)); 

(...) 
     // ------------------------------------------------ -------------------------------- 
     // Simulate paralell processing of same input: give input back so chain can restart 
     // ------------------------------------------------ -------------------------------- 
     public function last_feed_value ($ feedid, $ time, $ value) 
     {
         $ last = $ this> feed-> get_timevalue ($ feedid); 
         $ last = $ value2 ['value']; 
         return $ value2; 
     } 

i use new action "Last feed value"  to restore the input ( saved on feed  as first action )

Thank you and congratulations again 

Alessandro from Italy

**Comment by chaveiro** [comment]
Can be Closed as implemented.
See https://github.com/emoncms/emoncms/pull/280#issuecomment-71182208
