### ISSUE TITLE
E: Unable to locate package emoncms

### ISSUE THREAD

**Issue by jmatsushita** [emoncms/emoncms#242]
Following these instructions http://emoncms.org/site/docs/debianinstall doesn't work.

I'm using vagrant and a debian wheezy (7.6.0)

```
$ more /etc/apt/sources.list.d/emon_repo_s3_amazonaws_com.list
deb http://emon-repo.s3.amazonaws.com wheezy unstable
```

I did run ```apt-get update```

But still I get the error:

```
$ sudo apt-get install emoncms
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package emoncms
```

**Comment by Gizzo** [comment]
Still not working.

**Comment by 473856** [comment]
same here, not working. Not to mention that also the git installation description did not work for me under Ubuntu 14.04 Server.

**Comment by Paul-Reed** [comment]
The Debian package installation method has been discontinued, and the guide is now amended to indicate this. Trystan has referenced it for possible future development though.
