### ISSUE TITLE
Dashboard submenu alias use

### ISSUE THREAD

**Issue by euqip** [emoncms/emoncms#246]
Hi Trystan, 

I encountered an other problem with dashboards
When building the dashboard submenu, the Alias is used instead of the dash id to select and open a dashboard.
This works perfectly if Alias is unique and does not contain any special character.

When introducing a space char in the Alias string the selection is stuck.
When using german or french or swedish alias , there are accents in the strings and it does not comply with an HTTP request.

proposed solution

within the dashboard_model.php, build_menu function

original code:
                // Set URL using alias and id
            if ($dashboard['alias']) {
                $aliasurl = "/".$dashboard['alias'];
            } else {
                $aliasurl = '&id='.$dashboard['id'];
            }

proposed code:
                // Set URL using id only 
            $aliasurl = '&id='.$dashboard['id'];

The alias may be used to better decorate the URL, but accents and spaces have to be removed or replaced first.

**Comment by emrysr** [comment]
handled by the dashboard module:
GET:
https://github.com/emoncms/dashboard/blob/master/dashboard_controller.php#L40

SET:
https://github.com/emoncms/dashboard/blob/master/dashboard_controller.php#L58

**Comment by emrysr** [comment]
added this issue to the dashboard module's issue list

https://github.com/emoncms/dashboard/issues/160

**Comment by emrysr** [comment]
https://github.com/emoncms/dashboard/pull/161/files#diff-860159e6f535ada67f0d4b948c6f9814R246

**Comment by TrystanLea** [comment]
@euqip I wonder if you would be able to test @emrysr's pull request?
