### ISSUE TITLE
Fatal error: Call to a member function fetch_object() on a non-object

### ISSUE THREAD

**Issue by jmatsushita** [emoncms/emoncms#249]
Bug reproduction:
 - Install emoncms with [linux instructions](https://github.com/emoncms/emoncms/blob/master/docs/LinuxInstall.md)
 - Create a dashboard (click on + icon)
 - Click on Main star icon.
 - Reload browser page

The page displays the following error:
```Fatal error: Call to a member function fetch_object() on a non-object in /var/www/emoncms/Modules/energy/energy_model.php on line 43```

Workaround:
```
mysql -u root -p
use emoncms;
select * from dashboard;
```
Find the dashboard you just created (should be id 1 if you just installed)
```
delete from dashboard where id=1
```

Cheers,

Jun

**Comment by chaveiro** [comment]
Is this still an issue?
