### ISSUE TITLE
PHP "display_errors" settings

### ISSUE THREAD

**Issue by markvr** [emoncms/emoncms#250]
When troubleshooting a dashboard not displaying, I looked at the JSON coming from Emoncms, and it had a PHP E_NOTICE error in it first, before the JSON.  This obviously broke the Javascript JSON parser.

I was especially confused because I have all my php.ini settings to log but not display errors, as per best practice, and couldn't work out why this E_NOTICE was leaking to the browser.

Eventually I found the lines in settings.php and process_settings.php that were overriding my php.ini settings: 
 if (isset($display_errors) && ($display_errors)) {
        error_reporting(E_ALL);
        ini_set('display_errors', 'on');
    }

Can I suggest removing these and relying on the php.ini settings?  IMO it is counter-intuitive to override them in code, and makes it hard to run PHP following best practice if code is changing system defined settings back to an insecure configuration.

It also of course causes my original problem of breaking the JSON feeds sometimes!

Once you know they are there it is easy to change, but until you know that.....!!

**Comment by chaveiro** [comment]
I'm not sure why this setting was made config from emoncms but just set  $display_errors = false; in your settings.php
