### ISSUE TITLE
Bad day of data in kWh bar plot

### ISSUE THREAD

**Issue by casestudies** [emoncms/emoncms#252]
On Oct. 25, the kWh reading was negative. The realtime plot of the power data was normal for the time period.
![badplot](https://cloud.githubusercontent.com/assets/864901/4843196/17b94bf0-602f-11e4-9fdc-517f743f8962.PNG)

Running emoncms from emoncms.org. v.8.3.5. I'm wondering what may have caused this behavior and how to fix it, if possible.

Noticed another user had the same thing happen, but was referencing another issue with the zoom plot not showing data. See #251

**Comment by chaveiro** [comment]
Fixed for Day light saving time changes here: https://github.com/emoncms/emoncms/pull/303
