### ISSUE TITLE
Bulk import with historic data using power_kwhd and histogram processing evaluates to zero

### ISSUE THREAD

**Issue by threldor** [emoncms/emoncms#253]
When importing historic data using the processing of power_kwh, power_kwhd and histogram always evaluate to zero.

Looking at the process_model.php we do a check for the flushing of the redis server by comparing $last_time against time(). This is fairly reasonable for real time data, however this means that all historic data older than 2 hours will always evaluate to 0 for these. We pass to these functions the $time_now, the time stamp of the historic/realtime datapoint, and if this is used rather than time() it will allow the correct calculation of these when importing historic data.

This comparison also needs to account for the case when ($time_now - $last_time) evaluates to a negative number. I think there is an issue about this also regarding time change during daylight saving causing massive negative values in kwhd feeds.

All this is assuming that whilst importing bulk historic data that there is no real time data being collected. Doing that would be a recipe for disaster.

**Comment by TrystanLea** [comment]
This issue is now fixed, testing with the following bulk input test script:
https://github.com/emoncms/usefulscripts/commit/8ee49e3f81a636ac3adfc0fe2cfccec289988ff1

![testresult](https://user-images.githubusercontent.com/503186/42520760-0175ea62-845f-11e8-8505-1abee65a89ec.png)
