### ISSUE TITLE
Trouble in CSV export function with Timestore feed

### ISSUE THREAD

**Issue by jonathandreyer** [emoncms/emoncms#259]
Hello,

I have a problem with export to csv. I have a error:
Notice: Undefined variable: npoints in /var/www/emoncms/Modules/feed/engine/Timestore.php on line 273 false

I don't really know php but I have made some research and I don't found the place where the variable $npoints is set.

I have post this problem on the forum on openenergymonitor.org.

Jonathan Dreyer

**Comment by Paul-Reed** [comment]
Timestore is now redundant, and if you haven't already done so, please consider [updating your feed to phpfina](http://openenergymonitor.org/emon/node/10380)
