### ISSUE TITLE
"Remember me" not working.  Login details required despite having checked "Remember me" 

### ISSUE THREAD

**Issue by dazzag24** [emoncms/emoncms#261]
"Remember me" isn't working for me. I use the emoncms.org site and access it from several devices.

Windows PC - Google Chrome 41.0.2236.0 dev-m
Linux - Google Chrome 39
Android Phone - Chome 39.0.2171.93

All of them refuse to remember the login details which means that I am repeatedly having to enter my details. This makes the use of the dashboard view pretty pointless as I can't simply load it somewhere and let it run indefinitely.

Please fix. This is a major usability issue.

Thanks

ps Let me know if you want to see content of cookies or any other debug info.

**Comment by Frankster-NL** [comment]
I have the exact same issue. Have it since the beginning (v5 I believe) with all browsers on all platforms.

**Comment by Paul-Reed** [comment]
The 'remember me' function was reworked in v9.0 RC. If you are still having problems in the current version - v9.2 please repost. Thanks.

**Comment by arthurlutz** [comment]
am having this on a v9.2

**Comment by Paul-Reed** [comment]
Seems to work OK here on laptop, phone & tablet. Are you clearing cookies when closing your browser? can you try a different device.

**Comment by arthurlutz** [comment]
@Paul-Reed how long is the session supposed to be remembered ? 

My emoncms is hosted in a subdirectory of my domain and there are other web applications on there, it is possible that the various sessions conflict ?

**Comment by arthurlutz** [comment]
![screenshot from 2016-03-07 15-10-43](https://cloud.githubusercontent.com/assets/108437/13571695/e94af476-e476-11e5-9f8f-89e6e1fca982.png)

after logging in

![screenshot from 2016-03-07 15-10-43](https://cloud.githubusercontent.com/assets/108437/13571716/fdea9d78-e476-11e5-8158-c028a55bb6be.png)

**Comment by chaveiro** [comment]
Install last version 9.31 that had some fixes on this.
