### ISSUE TITLE
Auto remove old data

### ISSUE THREAD

**Issue by bettinz** [emoncms/emoncms#265]
Hello,
If I use PHPFIWA or PHPFINA I can't delete old data. The best thing is to set an interval like "delete data old than 90 days ". This allow me to manage a small interval without a lot of disk space. For some feeds in fact, i need kwh/d of 5 years (for example), but I don't need every value for 5 years (the graph in Full screen doesn't delete the interval with phpfiwa or phpfina).
Thank you

**Comment by arjenhiemstra** [comment]
Would be a great feature!

**Comment by TrystanLea** [comment]
I agree this would be great. To make this work we need to create a new feed from the old feed starting at the truncate point.

**Comment by bettinz** [comment]
Another idea is to add a "on the fly" engine. I mean, if I want to show a realtime value (like energy production), but I don't want to save this value on a feed, just show the value. This can help local installation on raspi, but maybe it's a better idea to open a new issue :)

**Comment by chaveiro** [comment]
Remove of old data is now supported but dont neet to save data by using virtual feed or Memory feed for this as of 9.0+

**Comment by robertsLando** [comment]
Any news about this feature?
