### ISSUE TITLE
wrong month in stacked visualization 

### ISSUE THREAD

**Issue by airix1** [emoncms/emoncms#279]
When selecting a bar graph in stacked, the wrong month is shown.  When the cursor is over Jan, it gives the right numbers, but shows the wrong month (see attached).  When selecting Jan, it displays the daily bar graph for days of Dec.
![graph](https://cloud.githubusercontent.com/assets/2799127/5609077/12eae5aa-945c-11e4-9eea-4a9bcb94e0f3.jpg)

Also, is would there be a way to add a third feed to stacked?
Thanks.

**Comment by chaveiro** [comment]
Fixed on extended branch.
