### ISSUE TITLE
Revamp Node Module

### ISSUE THREAD

**Issue by chaveiro** [emoncms/emoncms#281]
What's wrong:
- Replication of input module features. Ex. copy of processor list.
- Pour usage of reusable code. Need to mantain 2 versions of the same code.
- Writes long json strings to node table on bd on every post data. Bad performance.
- [Fixed] Global changes on theme.css breaking modal styling of other modules

Sugestions:
- Make this module only available as an API pre-processor for input engine.
- Remove node table need. Use input table as usual.
- Create new input process to 'work' the raw data as needed.

I can do the revamp. Or leave it to original author.
Say what you think.

**Comment by TrystanLea** [comment]
Hello Chaveiro, I think we should remove the node module all together as its original intended use for decoding node data has been moved to emonhub. Il look into doing this and providing notes for how to transfer to emonhub for anyone still using the nodes interface.
