### ISSUE TITLE
Bufferedwrite fails to update some feeds

### ISSUE THREAD

**Issue by inggaro** [emoncms/emoncms#288]
Hi all,
I'm try to move from the full version of emoncms (8.3.6) to the bufferedwrite branch (8.4.0 - buf 02).

It works but not all the feeds are updated; some remains "inactive". It's so strange because the inputs are correctly updated, and even if I create a new feed for them the new feed is inactive. The old feeds still work correctly if I switch back to the full branch of emoncms. 

![feeds](https://cloud.githubusercontent.com/assets/7466494/6126761/208af9f4-b124-11e4-9bec-533072e6854e.jpg)

Any ideas?

Thanks a lot

Garo

**Comment by TrystanLea** [comment]
Hello inggaro, what does your process list look like, could the issue be down to differences in the available process list functions in the buffered write branch perhaps?

**Comment by inggaro** [comment]
Thanks a lot for the answer! Are you just asking for my active process list? I mean something like "ps aux | less"?

Thanks again

**Comment by Jerome-github** [comment]
I think Trystan meant the list of available data process. The process you use to turn Inputs into Feeds.
The dropdown menu when you configure your Feeds.

**Comment by inggaro** [comment]
Sorry I didn't undestand :)

Ok so this is a picture of my inputs with processes.
![emon2](https://cloud.githubusercontent.com/assets/7466494/6229676/74c3d604-b6b9-11e4-9768-7ca274cb05fe.jpg)

They're all the same: all "log to feed" and args are somethink like "null: t_ext". But, for example, T_ext works and T_1 don't.

Even if I create a new process, it doesn't work.

Thanks again!

**Comment by Jerome-github** [comment]
I'm not sure, but maybe he was asking for a screenshot of the dropdown menu with the available processing functions.

If you create a new process, you get to choose processing functions (sum, multiply, log to feed, etc.) from this dropdown.

I may be wrong.

**Comment by inggaro** [comment]
Ok thank you. Here we are:
![emon_menu_1](https://cloud.githubusercontent.com/assets/7466494/6230381/99b5e654-b6bf-11e4-972d-68db6a58935b.jpg)
![emon_menu_2](https://cloud.githubusercontent.com/assets/7466494/6230384/9daf5b96-b6bf-11e4-950a-a626b6e29665.jpg)

I can create new or add to the existing feed, in PHPTIMESERIES or PHPFINA formats.

**Comment by TrystanLea** [comment]
Thanks Inggaro, and for helping Jerome. Can you try deleting the histogram process, that's probably it as histograms are not available on the buffered write version

**Comment by inggaro** [comment]
Tried, but still not working. However, I think the problem it's near, because I just find out that using buffered version I can't configure "power" input processes (now only log and kwhd). I can edit when using non buffered version!

**Comment by TrystanLea** [comment]
Can you delete the power input and reconfigure it with the log input process?

**Comment by inggaro** [comment]
Wonderful!! It's working!!! Thanks a lot.

It seems I cannot recreate kwhd process however... is it changed/removed?

**Comment by inggaro** [comment]
Sorry I think I find out... Is it "Wh Accumulator"?

**Comment by TrystanLea** [comment]
great, yes that's it!

**Comment by inggaro** [comment]
Thanks again!!
