### ISSUE TITLE
Request to allow user names of 3 chars - i.e. ben

### ISSUE THREAD

**Issue by sumnerboy12** [emoncms/emoncms#297]
Currently I can't have a username of ben since the min user name length is 4 chars.

**Comment by TrystanLea** [comment]
Great, yes I will make this change!

**Comment by Jerome-github** [comment]
Hi.

I didn't check, but I was wondering. Is there a test preventing the creation of a user named "myelectric", or "node", or "vis", or such ?

What about future such reserved names, if they were added after the user creation ?

Couldn't there be URL clash between a user's dashboard and a page with the same name ?

**Comment by TrystanLea** [comment]
Hello Jerome! there is no check at the moment but its the modules that are given priority. If a user creates an account with a module name they will at present be unable to view dashboards on using their username as it will go to the actual module controller first and ignore the dashboard public dashboard code.

**Comment by sumnerboy12** [comment]
Thanks Trystan!

**Comment by chaveiro** [comment]
Implemented on 9.2+
