### ISSUE TITLE
Embedding visualization doesn't work unless you are actually logged in to emoncms

### ISSUE THREAD

**Issue by mharizanov** [emoncms/emoncms#298]
Hi guys,

Embedding visualization doesn't work unless you are actually logged in to emoncms,

navigating to
http://emoncms.org/dashboard/view/heating?embed=1&apikey=**my_RO_APIKEY**

results in empty screen

**Comment by TrystanLea** [comment]
Thanks Mharizanov, not sure why thats stopped working but can confirm Im seeing the same. I will look into it

**Comment by MeroFilosofo** [comment]
Same problem here.
Empty visualization.

Thanks for your suport.

**Comment by jostor** [comment]
I am also having the same problem. Any news on when it will be fixed?

**Comment by chaveiro** [comment]
Feeds need to be public or you got a warning of invalid authentication. (as of 9.x)

**Comment by chaveiro** [comment]
A quick note, dashboard needs to be public also, a alias should be created and url must be acessed by username:
http://emoncms.org/username/alias?embed=1
