### ISSUE TITLE
Locally testing EmonCms

### ISSUE THREAD

**Issue by psychok7** [emoncms/emoncms#300]
So i successfully installed EmonCMS locally on my machine following your tutorial. I do not yet have the "gadgets" to fetch real data, so i tried fiddling with the MySQL DB and adding some values manually. It seems to me i was able to add `inputs` and `feeds` this way, but when i try to go to the `my electric` nothing shows up and i have tried all combinations there.
I probably missed something but i cant seem to figure this out. Here are some screenshots.

![screen](https://cloud.githubusercontent.com/assets/282284/6559655/3a9c58de-c67c-11e4-8586-848f5c5e5135.png)

![screen2](https://cloud.githubusercontent.com/assets/282284/6559657/3e77fb16-c67c-11e4-837b-387dd7d2e10f.png)

![screen3](https://cloud.githubusercontent.com/assets/282284/6559659/431166a8-c67c-11e4-8538-a1f900e23316.png)

Any ideas what im doing wrong?

**Comment by Paul-Reed** [comment]
This is a hypothetical question as emoncms is not intended to be populated in this manner.  
If when you have the hardware to gather real data you still have problems, please resubmit.

**Comment by Jerome-github** [comment]
To use EmonCMS without the "gadgets", you may use the input or feed API rather than play directly with the database. See API documentation in EmonCMS itself.

(Beware that API doc might not be totally up-to-date and I don't think feed API is really supported.)
