### ISSUE TITLE
'My Solar' not working with https

### ISSUE THREAD

**Issue by Paul-Reed** [emoncms/emoncms#302]
Just tried revised 'newgetdatamethod app' but the page is being blocked because a endpoint is directed back via http instead of https. The first version of 'My Solar' worked OK.  The screenshot below probably makes more sense than me!!
![https](https://cloud.githubusercontent.com/assets/973580/6648356/b09bcd42-c9d0-11e4-85ff-8bb05f9a7c3c.jpg)

**Comment by chaveiro** [comment]
That is a potential security issue being blocked by the browser.
Implementation must be revised.

**Comment by Paul-Reed** [comment]
A clean git emoncms install tonight revealed the same issue exists with both v1 & v2 of 'my solar', and both versions are browser blocked over https because of security concerns.  
All of the errors seem to point to jquery-1.9.0.min.js which is a depreciated script.  
  
Paul

**Comment by TrystanLea** [comment]
Hello Paul, are you connecting initially with https as the error suggests? does the error disappear if you connect via http only

**Comment by Paul-Reed** [comment]
There is no http access due to a rewrite rule in apache, but if I comment out the rule (to enable http access again), and load a fresh install of emoncms via http, which has been moved to the 'newgetdatamethod' branch, and add the new 'app' folder, the My Solar page still does not load - see error screenshot attached.  
All other emoncms pages can be accessed OK and appear to be working fine, but any of the 'App' pages are blank, except for the header, menu and footer.  (I've emailed you a link)
![rsz_551086d843b49](https://cloud.githubusercontent.com/assets/973580/6791243/78508702-d1a5-11e4-806c-2752cbc46e72.jpg)

**Comment by Paul-Reed** [comment]
Issue resolved, Thanks.
