### ISSUE TITLE
Embeded Histograph error message when just created in a dashboard

### ISSUE THREAD

**Issue by euqip** [emoncms/emoncms#307]
Durring creation of an histograph visualisation in a dashboard, feedid and other variables are undefined.

To avoid presence of an error message in dashboard, I would suggest to change code:

from:
<?php
    global $path, $embed;
    if (!$feedid) $feedid = 0;
    if (!$barwidth) $barwidth = 50;
    if (!$start) $start = 0;
    if (!$end) $end = 0;
?>

to: (a ternary test to check if defined, and give a value)

<?php
    global $path, $embed;
    $feedid   = isset($feedid)?$feedid:0;
    $barwidth = isset($barwidth)?$barwidth:50;
    $start    = isset($start)?$start:0;
    $end      = isset($end)?$end:0;
?>

This kind of error message may appear in other visualisation too.

Hope it will help
Thanks for pretty work

**Comment by chaveiro** [comment]
Should be fixed aftre 9.0+.
