### ISSUE TITLE
version number

### ISSUE THREAD

**Issue by simsasaile** [emoncms/emoncms#323]
I checked out the new v8.5 branch, but the emoncms-website still tells me that it is version 8.4
Not really important, but it confused me quite a lot :) and I thought I did something wrong.

Probably only the the value `$emoncms_version = "8.4.0";` in index.php has to be corrected.

**Comment by TrystanLea** [comment]
Thanks! Fixed it

**Comment by simsasaile** [comment]
Thank you!
