### ISSUE TITLE
after fresh install, I cannot "add Feed". Selector is empty. Errormessage below.

### ISSUE THREAD

**Issue by mcmuller** [emoncms/emoncms#324]
No process description available for process ' + feed' with id '29'.
Add a description to Module\input\Views\process_info.js array.

...I've setup a Schedule, Feeds for 3 Phases and wanted to "add Feed" to sum up my overall L1+L2+L3 before runnig into this.

**Comment by chaveiro** [comment]
Thanks for spotting this.

**Comment by mcmuller** [comment]
OK, Feed selector for "Feed+" etc. shows up now. Missing Description is a cosmetic flaw for me. 
Muito Obrigado, chaveiro!
