### ISSUE TITLE
undefined constant LOG4PHP_INSTALLED warning for emoncms-low-write-v8.5

### ISSUE THREAD

**Issue by miniwark** [emoncms/emoncms#327]
Using the taged download from https://github.com/emoncms/emoncms/tree/low-write-v8.5

I have a minor PHP warning in Admin view :

    OG4PHP INSTALLED:
    Notice: Use of undefined constant LOG4PHP_INSTALLED - assumed 'LOG4PHP_INSTALLED' in /var/www/emoncms/Modules/admin/admin_main_view.php on line 27

**Comment by TrystanLea** [comment]
This bug should also be fixed on the latest low-write, let me know if your still having trouble and I will re-open this issue
