### ISSUE TITLE
I have same error

### ISSUE THREAD

**Issue by kumarmohan7** [emoncms/emoncms#330]
Can't connect to database, please verify credentials/configuration in settings.php
Error message: Can't connect to MySQL server on 'smk-iot.16mb.com' (111 "Connection refused")

**Comment by chaveiro** [comment]
If user and pass are ok, you may need to allow access by ip address in mysql :
GRANT ALL ON yourdatabasename.* TO user@'%' IDENTIFIED BY 'yourPassword';
Ask for support on your hosting company if not allowed to execute the command.

**Comment by kumarmohan7** [comment]
Than you for reply

Please give mysql database files and steps

**Comment by kumarmohan7** [comment]
Fatal error: Call to a member function fetch_array() on a non-object in /home/u645649278/public_html/emoncms-8.5/Modules/user/user_model.php on line 507

Please give mysql database files and settings
