### ISSUE TITLE
Post multiple values in JSON format

### ISSUE THREAD

**Issue by vosmont** [emoncms/emoncms#337]
Hello,
is it possible to send multiples values in JSON format, with a timestamp ?

Perhaps something like that :
http://emoncms.org/input/post.json?json={{power:200,offset:-10},{temperature:25,offset: -5}}&time=1433504598

**Comment by vosmont** [comment]
It seems that
http://emoncms.org/input/post.json?json={power:200,temperature:25}&time=1433506452
at least should work, but when I set a time different from current time, the values are not stored.

**Comment by vosmont** [comment]
In fact, the value is stored only if it is after the last recorded value.
You cannot thus insert values post factum.

So my need is to be able to set an offset on the sent values.

**Comment by arthurlutz** [comment]
I think I've bumped into the same bug as you @vosmont see #368 and #371, have you found a fix ?
