### ISSUE TITLE
Dials&Cylinder only work in edit mode (Extended Version)

### ISSUE THREAD

**Issue by boelle** [emoncms/emoncms#340]
Hi

i made an install based on this guide: https://github.com/emoncms/emoncms/blob/master/docs/LinuxInstall.md

i only skipped a few steps

/etc/php5/conf.d/suhosin.ini i could not find so skipped that

and the same for emoncms.log

I have tried on the forums but so far no luck...

all feeds are set to public, so is the dashboard... but the dials and cylinder symbol only show when i edit the dashboard

**Comment by chaveiro** [comment]
can be closed was an incomplete install
