### ISSUE TITLE
mcrypt warning after debian upgrad

### ISSUE THREAD

**Issue by PascalTurbo** [emoncms/emoncms#349]
Hi There,

I've upgraded debian from Wheezy to Jessie which obviously comes with a newer version of mcrypt. Now I got these warnings on the event settings page:
    Warning: mcrypt_decrypt(): Key of size 3 not supported by this algorithm. Only keys of sizes 16, 24 or 32 supported in /var/www/emoncms/Modules/event/event_settings_view.php on line 90

Any idea how to fix this?

Bests
Pascal

**Comment by pb66** [comment]
see #351

**Comment by JSidrach** [comment]
Fixed in the latest release.
(This Issue can be closed @TrystanLea)

**Comment by PascalTurbo** [comment]
1. Which release? The latest release is 8.5.2
2. I checked out the current 9.0 branch - and the error is always there.

**Comment by chaveiro** [comment]
latest is 9.2.
