### ISSUE TITLE
List Format Value

### ISSUE THREAD

**Issue by kiwinewt** [emoncms/emoncms#350]
Out of curiousity, why in emoncms/Lib/tablejs/custom-table-fields.js function list_format_value is there different values? Can this be made customizable in the admin/user profile page please?

I use emonCMS for temperature monitoring and think it is worthwhile seeing the 2 decimal places as it gives a better understanding and overview of temperatures that may not fluctuate by much but do fluctuate, even at 15.XX degrees, for example.

**Comment by chaveiro** [comment]
Its to limit number of characters on the UI.
Say you have 4 digit places before text wrap. 
A 1000.01 value it will round up to 1000  but a 1.01 value is kept.
