### ISSUE TITLE
User salt too short

### ISSUE THREAD

**Issue by kiwinewt** [emoncms/emoncms#351]
For proper use of mcrypt_decrypt (as used by the Event module), you need a salt of 16, 32, 64 characters length.

I propose to increase the salt to 16 characters, from my testing the current salt will still work for password decryption until the user next changes their password, therefore updating the salt.

This will need an update for the users table - the salt column from 3 to 16 (or higher)
This will need lines 170, 296 and 328 in Modules/user/user_model.php updating to $salt = substr($string, 0, 16);

**Comment by JSidrach** [comment]
Fixed in the latest release.
(This Issue can be closed @TrystanLea)
