### ISSUE TITLE
Suggested improvements for upgrade documentation

### ISSUE THREAD

**Issue by nmgeek** [emoncms/emoncms#355]
For the file at https://github.com/emoncms/emoncms/blob/v8.5/docs/Upgrading.md

1. My version of mysqldump needed the additional argument, --database emoncms.
I seem to have v5.5 of mysql.

2. The instructions for upgrading the database point at the URL, http://localhost/emoncms/admin/view, but since previous instructions tell you to install the new one under emoncms_new I think the URL should be http://localhost/emoncms_new/admin/view

3.  After you rename emoncms_new to emoncms I believe the feed (client) systems will start hitting the api of the new version.  There is potential for something to go wrong at this point so you should test some more before assuming the upgrade is done.  (This wasn't entirely obvious to me so I was surprised that the feeds stopped working at this point.  In my case it was because the new version requires a new timestore and apparently it needed to be initialized by upgrading my data from the old timestore format.)

4. It would be nice if you added a step at the end reminding the reader to remove the

    $updatelogin = true;

line.

**Comment by Paul-Reed** [comment]
Thanks for the post. Just reviewed, and the guide which you refer to has now been archived.
