### ISSUE TITLE
DateTimeZone::__construct(): Unknown or bad timezone (7)

### ISSUE THREAD

**Issue by nmgeek** [emoncms/emoncms#356]
Below is the full text of the error from the apache error log.  I got this error after upgrading from v7 to v8.5.  When I went to my user's profile I found the timezone was set to an integer value but the selection choices were all time zone names (as text).  I selected my time zone then the profile page showed my timezone as text and the error shown below stopped repeating in the apache error log.

I would think the database upgrade script would make the necessary change in the db so you wouldn't have to do it manually.  If you have to do it manually then it should be part of the upgrade instructions.

PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone (7)' in /var/www/emoncms/Modules/input/process_model.php:669\nStack trace:\n#0 /var/www/emoncms/Modules/input/process_model.php(669): DateTimeZone->__construct('7')\n#1 /var/www/emoncms/Modules/input/process_model.php(352): Process->getstartday(1437247683)\n#2 /var/www/emoncms/Modules/input/process_model.php(127): Process->input_ontime('14', 1437247683, 0)\n#3 /var/www/emoncms/Modules/input/input_controller.php(284): Process->input(1437247683, 0, '1:9,2:60,1:13,7...')\n#4 /var/www/emoncms/core.php(66): input_controller()\n#5 /var/www/emoncms/index.php(109): controller('input')\n#6 {main}\n  thrown in /var/www/emoncms/Modules/input/process_model.php on line 669

**Comment by chaveiro** [comment]
After updating the db in admin panel, you have to set the correct timezone in the account panel for all users.
