### ISSUE TITLE
bargraph label should use 24 hour time format

### ISSUE THREAD

**Issue by yekorzh** [emoncms/emoncms#359]
Hi,

I'm using bargraph to display hourly power consumption. When I point mouse cursor over the bar, it displays text showing total power during that period, date and time. It looks like time is in 12-hour format and doesn't show am or pm, making it very confusing. I suggest changing the time format to 24 hour to match values on x-axis.

![image](https://cloud.githubusercontent.com/assets/13219135/8850241/e0c863a6-3189-11e5-9ae8-a6b8d12d9b1a.png)

**Comment by pb66** [comment]
Can you double check that? I have seen a issue on the forum that may suggest the "chart" time might be 12hrs out.

**Comment by yekorzh** [comment]
Here is another highlighted bar from the same chart on the same date. Notice that the time is the same. 
![image](https://cloud.githubusercontent.com/assets/13219135/8862798/b98a9316-31d6-11e5-8926-e51654eb800d.png)

Regarding 12 hour issue, I think in my case all the data corresponds to correct time on the x-axis, what I see however is that when I open the dashboard chart doest show most recent 12 hours of data , but when I  click ">"  graph scrolls to the right an data appears.

**Comment by glynhudson** [comment]
Thanks ;-)
