### ISSUE TITLE
Feed update giving error when event is assigned to the feed

### ISSUE THREAD

**Issue by Rishabh-K** [emoncms/emoncms#365]
Hello I am new to emoncms.
I have setup emoncms on xampp windows.
Created a feed named "feed1" 
I created a event on this feed
![capture1](https://cloud.githubusercontent.com/assets/8733107/9106878/f5f3add2-3c40-11e5-9d04-9e83842cb841.PNG)

I am using url (to pass data to thiis feed):
http://localhost/emoncms/feed/update.json?id=6&apikey=xxxxxxxxxxxxxxxxx&value=70.0

But the window is showing an error:
Fatal error: Call to a member function get() on null in C:\xampp\htdocs\emoncms\Modules\event\event_model.php on line 239

This error is showing only when an event is associated to this feed.

This error vanishes when no event is associated with this feed.

Second thing the event works fine i.e. conversion of false to true when condition is valid but the transformation of false to true is visible after page is manually refreshed.

![capture2](https://cloud.githubusercontent.com/assets/8733107/9107067/3871f23a-3c42-11e5-8b23-517632e80b5f.PNG)

Third thing is the event fires but the action assigned to it i.e. setFeed does not fires.

Also the event setting page shows some errors:

![capture3](https://cloud.githubusercontent.com/assets/8733107/9107330/15425d84-3c44-11e5-95be-8ef1101ac765.PNG)

![capture4](https://cloud.githubusercontent.com/assets/8733107/9107334/1c1ff972-3c44-11e5-8bc9-a8d88727e8af.PNG)

**Comment by elyobelyob** [comment]
There is currently an issue with event. Someone has changed the db schema
and it broke the system.

Hopefully someone can take ownership of fixing, I've not got time. I did
post some info yesterday to another discussion r.e. this.

**Comment by Paul-Reed** [comment]
A number of event module incompatibilities has occurred as emoncms has evolved to the current version. A replacement event module is currently under development, and will hopefully be published shortly.
