### ISSUE TITLE
update_feed_data broken

### ISSUE THREAD

**Issue by arthurlutz** [emoncms/emoncms#371]
While trying to solve  https://github.com/emoncms/emoncms/issues/368 I tried add to my "Log to feed" an "update feed @time" and this gives me the following error when doing the HTTP post to .json : 

```
<b>Fatal error</b>:  Call to a member function fetch_array() on boolean in <b>/var/www/emoncms/Modules/input/process_model.php</b> on line <b>207</b><br>
```

A quick read of the code it seems to look for a $feedname in the database, which doesn't exist, isn't the data stored on the file system and not in the database anymore ? Is this old code ?

**Comment by Paul-Reed** [comment]
Arthur, does this relate to the current release?
Because in v9.2, process_model.php lives under /Modules/process/ and not /Modules/input/
..or is this a path issue which you are raising?
