### ISSUE TITLE
Installation issue: Call to a member function fetch_object() on a non-object in dashboard_model.php on line 69

### ISSUE THREAD

**Issue by christian77** [emoncms/emoncms#388]
Hello,

I tried to install emoncms with these installalation instructions (v8.5):
https://github.com/emoncms/emoncms/blob/master/docs/LinuxInstall.md
https://github.com/emoncms/emoncms/blob/master/docs/SharedLinuxHostingInstall.md

When I call the front page the first time I get the following error messages:

```
Fatal error: Call to a member function fetch_object() on a non-object in /var/www/vhosts/xxx/yyy/Modules/dashboard/dashboard_model.php on line 69 
```
I tried also before the master branch without success.

Do you have any ideas or tips how to solve it?

Many thanks in advance,

Christian

**Comment by chaveiro** [comment]
Is this still an issue on 9.2+ ?
