### ISSUE TITLE
Incorrect value in Dashboard- Bar And Dial Widgets

### ISSUE THREAD

**Issue by Rishabh-K** [emoncms/emoncms#395]
Hi,

I am using the widgets Bar an Dial in my dashboard.
Basically I am passing temperature data to these widgets through feed.
Initially I was using the dashboard as it is. But at some point the animation in it was too slow when the feed was updated.
So to solve the animation problem changed the value of variable <b>dialrate</b> from 0.02 to 1.72 in render.js
This made animation fast.

But my problem is if the feed value is 10.0 the Widget Bar sometimes shows value 9.99 and the Dial shows value 10.1.

Why I am facing this problem.

**Comment by chaveiro** [comment]
What emoncms version? What browser?

**Comment by chaveiro** [comment]
Not able to reproduce.
