### ISSUE TITLE
My Electric Fail: issue on new setup

### ISSUE THREAD

**Issue by BrettThePark** [emoncms/emoncms#396]
I am trying to use My Electric for the first time. When clicking the My Electric link I am receiving the following javascript error:

```
TypeError: undefined is not an object (evaluating 'app.config.myelectric.currency')
init
loadapp.js:51
showapp.js:58
(anonymous function)app:105
```

**Comment by Paul-Reed** [comment]
This should now be fixed. See https://github.com/emoncms/app/commit/d9a815678d0edd3949276db2427348fb365159d5
