### ISSUE TITLE
problems with daylight saving time

### ISSUE THREAD

**Issue by joyrider3774** [emoncms/emoncms#397]
- KWH feeds are displaying negative values, i recalculated these using the scripts in the proces but as soon as you started posting data again using the input api the feeds go negative again. i found a workaround for this but i'm guessing it's not a complete workaround since bargraphs with delta = 1 based on the kwh feeds don't display any data for the day after daylight saving time. My workaround was to recalculate the kwh feed based on the power feed, then send data, just to see the kwh graph / feed has gone negative again, edit one of the nodes from the dip to the last correct value in the spike to counteract the negative value (since it's accumulating). then recalculate the feed again. this works if you look at the feed directly hower bargraph feeds based the kwh feeds using delta = 1 display nothing on the current day as in this screenshot
![kwh2](https://cloud.githubusercontent.com/assets/10714776/10741331/7ac92b10-7c27-11e5-9a15-4ce8e5ab505f.jpg)

- there is a setting in windows that affects the x-axis display of bargraph visualizations, if you set "dont automatically change time to daylight saving time, everything is displayed correctly however if you set it enabled which is the prefered and default setting you'll see two times the same day like in these screenshots:
![timezonesetting](https://cloud.githubusercontent.com/assets/10714776/10741254/13ec5610-7c27-11e5-9fd4-19c941d33ba4.jpg)
![kwhd](https://cloud.githubusercontent.com/assets/10714776/10741258/1aaa0d80-7c27-11e5-9060-8a79246fafde.jpg)
(not the above screenshot is from a kwhd graph which seems to display the data, but has the x-axis bug related to the windows settings in the other screenshot)

- more info on my findings can be found in the forum here http://openenergymonitor.org/emon/node/11473
i noticed other people are having daylight saving time problems in other threads like the last post here : http://openenergymonitor.org/emon/node/6049

**Comment by chaveiro** [comment]
Fixed on latest versions 9.1+.
