### ISSUE TITLE
Only one value for timeseries feed

### ISSUE THREAD

**Issue by arthurlutz** [emoncms/emoncms#403]
Hi, 

I'm having a problem when trying to graph a value by day on emoncms 8.5.2  2015.07.20

![screenshot from 2015-11-09 16 07 45](https://cloud.githubusercontent.com/assets/108437/11037125/77515a72-86fc-11e5-97cb-a120e876f0fa.png)

Here is the feeds view : 

![screenshot from 2015-11-09 16 08 05](https://cloud.githubusercontent.com/assets/108437/11037130/800b8976-86fc-11e5-810b-24b094b3b9a5.png)

and the transforms from the input 

![screenshot from 2015-11-09 16 08 36](https://cloud.githubusercontent.com/assets/108437/11037146/8f9c260c-86fc-11e5-90db-970b225bf291.png)

The "transformation" is inspired by Fred's comment that can be found here  http://hallard.me/teleinfo-emoncms/#comment-10290

```
1 -> Log to Feed – Compteur (Utile pour la phase de dessous)
2 -> Total pulse count to pulse increment – (Diff N- N-1)
3 -> Log to Feed – Elec. Wh
4 -> Accumulator – Elec. Wh Acc
5 -> X 0.001 ( vers kWh)
6 -> kWh to kWh/d (Consommation Journalière en kWh/d)
7 -> kWh to Power (Puissance instantanée)
```

I'm getting the same problem with my teleinfo electricity counter. Values seem ok but no graph for the daily kWh/d.

**Comment by arthurlutz** [comment]
am getting the same problem with v9

**Comment by chaveiro** [comment]
May be related to this https://github.com/emoncms/emoncms/pull/414.
Can you test with the fix?

**Comment by arthurlutz** [comment]
@chaveiro #414 solves my issue. Thanks.
