### ISSUE TITLE
Have a "convert an analog value to binary" transform with a limit value

### ISSUE THREAD

**Issue by arthurlutz** [emoncms/emoncms#404]
It would be nice to be able to have a transform from an INPUT to be able to say : 

* if value below 30 output 0
* if value above 150 output 1

This is useful for various on/off readings that can be done via a piezo light detector. Sure, that can be done on the emitting side usually, but I find it usefull to have the analog value directly in emoncms.

**Comment by chaveiro** [comment]
You can do that already with conditional processors: 'If >, skip next' and 'GOTO'

**Comment by arthurlutz** [comment]
@chaveiro I don't have that, is that a new feature in 0.9 ?

**Comment by chaveiro** [comment]
9.x, yes
