### ISSUE TITLE
Idea: auto create device based on new input

### ISSUE THREAD

**Issue by bradjc** [emoncms/emoncms#422]
Using devices and device templates is a nice way to specify all of the fields a device will publish to and all of the processors that should exist when a device is created, rather than having to do this for each new device. My idea is to extend this functionality to allow a device to specify its template when it publishes data, and upon receiving data from a new node, emoncms would be able to lookup if there is a template for it, and if so instantiate that template before recording the incoming data.

Essentially, it would expand the `input` API have a devicetype key:

    http://emoncms.org/input/post.json?node=1&json={power:200}&devicetype=mymeter

where `mymeter` would match the `mymeter.json` device template. This would allow a device to essentially configure itself without having to make a series of device API calls to set things up in advance.

I'm interested in making a pull request for this, but wanted to get some feedback first to check that this is something the project would be interested in and that there isn't a reason to not add it.

**Comment by chaveiro** [comment]
The ideia behind  device module is that a device has a relation of 1 to 1 to a node.
The device module also brings an optional devicekey so you get a security key per device.
A manual setup phase is required to specify the node name, device key, location and initialize from the chosen device template a set of default inputs and feeds for that template.
Your proposal would work if you use apikey only. 
A device could not initialize itself filling all other details unless you configured it on the device first.
This setup phase is done in just a few clicks, once per device so no much overhead on doing it anyway.
Alternatively there is the device/create.json and device/inittemplate.json API that allow you to do that from the device on a setup phase anyway.
