### ISSUE TITLE
Dashboards Missing

### ISSUE THREAD

**Issue by Paul-Reed** [emoncms/emoncms#433]
If you find that you have recently installed emoncms, or updated your existing installation via git, and noticed that your dashboards have disappeared - [please see this forum post!](http://openenergymonitor.org/emon/node/11798)

**Comment by Saoclyph** [comment]
Try updating the database scheme in the admin view, it did the trick for me.
I updated from 8.3.

**Comment by Paul-Reed** [comment]
Thanks Saoclyph, however updating the database will not re-install the dashboard module.
It has been removed from the emoncms git core, and needs to be installed as a separate module.

**Comment by Saoclyph** [comment]
Ha sorry, I misread "Dashboard missing" with "Dashboard **Widget** missing". I thought wifixcort from the forum thread had posted an issue here.
I had the same issue as him, widget not appearing in the dashboards after updating emoncms core and adding the dashboard module.
I did update the database scheme after updating emoncms core, but I forgot to do it after adding the dashboard module. Updating it later solved the missing dashboard widget.
