### ISSUE TITLE
$display_errors = true;

### ISSUE THREAD

**Issue by Paul-Reed** [emoncms/emoncms#443]
It's been raised in the forum a number of times, but in settings, should $display_errors be disabled by default, and user re-enabled for troubleshooting?  
On a number of occasions, errors due to malformed data have resulted in error messages being returned to emonhub, and effectively bounced back and forth between emoncms & emonhub, stopping emoncms from functioning.  
I understand that pb66 has made changes to emonhub to try and handle the error messages, but I'm wondering if this would be better disabled, to remove the possibility of this occurring.

**Comment by pb66** [comment]
Hi Paul
Unless the responses given by emoncms are revised the default setting must "false" for the bulk_input or any other code requiring a confirmation of receipt to work.

Besides errors there are also occasions when the data is received by emoncms but it gives a warning AND an "ok" in one response this is interpreted as not an "ok" only response.

Currently we can only look for a response matching "ok", I've tried any response containing "ok" and that will get thrown by a "to**ok** too long" response for example and using spaces in the match doesn't work either so I cannot accomadate this in emonhub.

It would be good if there was more than a "ok" or not range of responses but I don't want to complicate things here right now the default "false" setting will revert things to the former successful operation.

I would be interested to know what malformed data has caused a warning from emoncms, if emonhub deems the data unsuitable for emoncms it should not add it to the buffer as it cannot cherry pick packets to send to the bulk_input, it will send a batch, that batch will be "ok" or not, so one bad packet refused will stop posting dead. either the packet must be discarded by emonhub before it's added to the buffer or emoncms's bulk_input must accept the whole batch and discard the defective packet at processing. 

I have seen several reports of empty data packets being forwarded by the "emonpi" variant but that is predominantly via mqtt and the queue for the http interfacer gets flushed every 30secs regardless of whether the data is posted or valid so it is less of an issue there.

Paul
