### ISSUE TITLE
emoncms enable multiuser

### ISSUE THREAD

**Issue by kumarmohan7** [emoncms/emoncms#446]
Hi;

Please enable multiuser , enable user register 

how to control relay through emoncms...?

**Comment by Paul-Reed** [comment]
Multiuser is a user option activated by changing the setting in settings.php or are you saying that it doesn't work?

**Comment by kumarmohan7** [comment]
ok sir thank you

how to control relay through emoncms...?

**Comment by Paul-Reed** [comment]
You can't directly via emoncms, but most users are using additional software, such as node-red or mqttwarn to control a remote relay via MQTT.
Both of them are bundled in the emoncms image file, and node-red comes already installed in the latest Raspbian Jessie OS. The MQTT relay is available from the [OEM shop](http://shop.openenergymonitor.com/three-channel-wifi-mqtt-relay-thermostat/) (when they are in stock!).
