### ISSUE TITLE
phpMQTT update

### ISSUE THREAD

**Issue by bduncan** [emoncms/emoncms#453]
Hi,

It looks like there is an update to https://github.com/bluerhinos/phpMQTT/ which allows it to automatically connect. This should fix things getting stuck if mosquitto gets restarted. Please could it be pulled in?

Thanks,
Bruce

**Comment by glynhudson** [comment]
Thanks, done: https://github.com/emoncms/emoncms/commit/f397eee703589a91e21a305e636b11e993c73018
