### ISSUE TITLE
Multigraph and time compare vis toggle needs refactoring to flot lib

### ISSUE THREAD

**Issue by chaveiro** [emoncms/emoncms#461]
More info: https://github.com/emoncms/emoncms/pull/459

**Comment by software-monkey** [comment]
I've simplified flot.togglelegend and got it working better. I'm putting some finishing touches on it and flushing out some features for it. I will submit a pull request in a few days

**Comment by software-monkey** [comment]
https://github.com/emoncms/emoncms/pull/465
