### ISSUE TITLE
Modular design

### ISSUE THREAD

**Issue by ildemartinez** [emoncms/emoncms#47]
I am trying to refactor all pieces of code into modules to be able to deal with better template system and decouple the dependences.

Here are my advances:

![check_modules](https://f.cloud.github.com/assets/1641352/368148/4cba88d0-a2b9-11e2-845d-2ef559fd3e43.png)

Admin page has Check modules to retrieve module information. In code each module is a class that implemts an interface.

![modules](https://f.cloud.github.com/assets/1641352/368163/95fd3c54-a2b9-11e2-8874-ad36045a4b5a.png)

Now, for example, the footer of the emoncms is a module so it doesnt have to be on template decoupling dependences.

In theme file only have to do:

![code](https://f.cloud.github.com/assets/1641352/368192/2d4b3ee4-a2ba-11e2-8a04-2e63a051a0e3.png)

and will check all installed modules with html render capabilities and put there its content.

¿What do you think about?

Any idea of interested modules?

All the best
ilde

**Comment by TrystanLea** [comment]
This issue is being left here as inspiration for further emoncms design changes in future, its not currently a focus of emoncms development but if we come back to it @ildemartinez suggestions could be useful
