### ISSUE TITLE
Feeds updating but not Inputs after latest update (2016.02.13)

### ISSUE THREAD

**Issue by glynhudson** [emoncms/emoncms#474]
Just updated to latest master branch ( 2016.02.13), all seems to work ok my feeds are updating nicely, however my feeds are not. I'm using the mqtt_input script. When an input is posted using HTTP it shows as updating therefore the issue must be with the mqtt_input script. Possibly the change in user ID location?  Inputs were updating fine using mqtt_input prior to this update

![inputs_not_updating](https://cloud.githubusercontent.com/assets/758844/13027407/0f3b99d4-d247-11e5-9da4-73ab36255a1b.png)

**Comment by chaveiro** [comment]
Hi check now.
(I cant test)

**Comment by glynhudson** [comment]
Thanks, this fixed it a8851f02fe04d25d63393c43f1226358d503118c
