### ISSUE TITLE
Need bargraph features, start-end bar offset

### ISSUE THREAD

**Issue by unreg** [emoncms/emoncms#478]
I set interval to 43200 (12hr), bar on each day start 0:00.
Needs features to set offset, e.g. 28800 (8hr) - 8:00 - 20:00, 20:00 - 8:00, ...

**Comment by TrystanLea** [comment]
@unreg, this should be possible I think by setting the start time of your request. I assume the feed being used is an accumulating kWh feed, the result of a power_to_kwh processor?
