### ISSUE TITLE
No process description available for 'Total pulse count to pulse increment'

### ISSUE THREAD

**Issue by JonMurphy** [emoncms/emoncms#482]
No process description available for process 'Total pulse count to pulse increment' with id '20'.
Add a description to Module\module_name\module_name_processlist.php in process_list() function, $list[] array at the 'desc' key.

low-write 9.31  |  2016.02.13

**Comment by JonMurphy** [comment]
same as #511

**Comment by Paul-Reed** [comment]
I'll close this one Jon, and keep the problem confined to one issue, if that's OK.

Paul

**Comment by JonMurphy** [comment]
sounds good to me!
