### ISSUE TITLE
Bulk input data needs a method to set keys

### ISSUE THREAD

**Issue by bradjc** [emoncms/emoncms#485]
Inspired by this thread: https://openenergymonitor.org/emon/node/2249 and my own needs, it would be incredibly useful to be able to set the key name in a bulk POST message. Something like:

```
https://e.com/input/bulk.json?data=[[0,1,{"power":10, "voltage": 240}],[10,1,{"power":11, "voltage": 240.2}]]
```

In the short term, however, is there a method for making this work right now? I tried the following two requests:

```
https://e.com/input/post.json?node=1&json={power:200}
https://e.com/input/bulk.json?data=[[0,1,100]]
```

And the second response shows up as a new key (named "1") and does not use the existing first key. Is the prescribed method for bulk POST support to just know what the keys 1-N mean?

**Comment by TrystanLea** [comment]
Good news! This has been implemented by @fredrike
https://github.com/emoncms/emoncms/commit/cdeaf6b89a8afca7f0b1a587a0fad09591dc6714
