### ISSUE TITLE
in Sub Domain Realtime graph not comming

### ISSUE THREAD

**Issue by kumarmohan7** [emoncms/emoncms#493]
Hi ;

emoncms sub domain real time graph is not coming error is"URL Not acceptable"

with sub domain address

http://iot.smartiot.co.in/kumarmohan7

![with_out_problam](https://cloud.githubusercontent.com/assets/7358397/13858126/3039156e-eca3-11e5-9ff6-bcb86b6eac18.png)

with out sub domain address

http://smartiot.co.in/iot/kumarmohan7

![problam](https://cloud.githubusercontent.com/assets/7358397/13858030/b5c52804-eca2-11e5-838d-8af8a138dd0a.png)

Please Help 
how to salve this problem....?

Thank You.

**Comment by kumarmohan7** [comment]
Hi ;

emoncms sub domain real time graph is not coming error is"URL Not acceptable"

with sub domain address

http://iot.smartiot.co.in/kumarmohan7

![problam](https://cloud.githubusercontent.com/assets/7358397/13858201/9b56ba86-eca3-11e5-8e15-13a8d6aa2a2d.png)


with out sub domain address

http://smartiot.co.in/iot/kumarmohan7

![with_out_problam](https://cloud.githubusercontent.com/assets/7358397/13858216/a8a0e946-eca3-11e5-91c4-7830f8dbb251.png)


Please Help 
how to salve this problem....?

Thank You.

**Comment by chaveiro** [comment]
if you edit the dashboard does this graph appears?
