### ISSUE TITLE
Dashboard quick links not displaying on mobile portrait view

### ISSUE THREAD

**Issue by glynhudson** [emoncms/emoncms#497]
I've just noticed when viewing Emoncms on my phone in portrait view I cannot see the quick links to my dashboards on the top RHS:

![screenshot_20160321-104441](https://cloud.githubusercontent.com/assets/758844/14065355/2cfa10b0-f41e-11e5-9625-3d30cbb505ec.png)

After rotating my phone to landscape view the dashboard links appear: 

![screenshot_20160321-104448](https://cloud.githubusercontent.com/assets/758844/14065357/2fb52d8a-f41e-11e5-8ba3-019791ba843b.png)

Is this a design decision in Emoncms 9 to hide dashboard links when viewed on a small screen? Or a bug? It's not a big issue, but there is plenty of space on the top bar in portrait mode for at least a couple of the dashboard  star icons. How could I try and fix this?

**Comment by Paul-Reed** [comment]
Glyn, you seem to be missing the dashboard icon.
It was a beta debated design decision to restrict the dashboard 'quick links' to bigger displays, to keep the workspace from looking cluttered, but you should still see the Dashboard icon to the left of the App icon as shown below. The dashboard icon dropdown should list all of your saved dashboards for easy access.
Have you tried deleting and re-installing the app module.

![portrait](https://cloud.githubusercontent.com/assets/973580/14067169/30ca96fa-f456-11e5-8b20-4a0d767425f1.png)

In landscape view, you should be able to see your quick links, but also still see the Dashboard icon.

![landscape](https://cloud.githubusercontent.com/assets/973580/14067211/47de00a6-f457-11e5-9343-62fff878e371.png)

**Comment by elyobelyob** [comment]
I raised this a while back myself.
Can you explain the process of reinstalling the app module, and which
version of emoncms this applies to?
Am running core 9.3 myself. Thanks.

**Comment by Paul-Reed** [comment]
To re-install the dashboard module;
`cd /var/www/emoncms/Modules`
`rm -rf dashboard`
`git clone https://github.com/emoncms/dashboard.git`
Because your dashboard configs are safely stored in MYSQL, reinstalling the dashboard module will not affect them - they won't be deleted!  
Paul

**Comment by glynhudson** [comment]
Hi Paul,

This is interesting, I agree, with the design decision hiding the dashboard shortcuts on low screen widths is a good idea. However it seems on all my RaspberryPi / emonPi installs the Dashboard nav button is not visible. Re-installing the dashboard and app modules made no difference. On my local machine the Dashboard nav button IS visible! I've established the issue is nothing to do with the different settings.php files, testing the emonpi.settings.php file on my local machine made no difference to the Dashboard nav button. 

Can you think of anything else I can test to identify this issue? Do you have a RasPi install you could check?

Both my installs on on the same master branch and up-to-date

**Comment by Paul-Reed** [comment]
I've emailed you a link to my site so that you can check if you wish.
Mine is also Master branch & up to date.

**Comment by glynhudson** [comment]
Ah go it! It seems the Dashboard nav button disappears if all dashboards are published.

I've pushed a change which make the Dashboard button always visible if any dashboards exist even if they are all published. I've also renamed it to 'Dashboards' . 

Are you happy with this mode of operation? I think it's an improvement since at least mobile users will always be able to access their dashboards. 

https://github.com/emoncms/dashboard/commit/d62d0755d12ce223e50ac32b930d0f16b03cbcbe

**Comment by Paul-Reed** [comment]
Wasn't aware of that!
I wonder what the rationale was in including that check?

**Comment by glynhudson** [comment]
I suppose if all dashboards are published therefore there are shortcut start icons for all the dashboards and the drop down menu is not required, which is fine until viewed on a small screen when everything is hidden!

**Comment by elyobelyob** [comment]
That's a huge improvement on my phone, thanks. It would also be useful if
they retained the same order as the normal menus. In fact, I don't think
they can be ordered at the moment anyway? The first icon just clones, I was
hoping I could drag/drop those into a specific order.

Anyway, thanks for that small, but huge improvement.

**Comment by elyobelyob** [comment]
Oh, I'd also remove the *'s in landscape mode on mobile. Without any naming
next to them, they were always a bit of guess work. This drop down does
away with the need for them.

I'd offer to help, but away at the moment. And front end stuff isn't really
my thing.

Thanks

**Comment by Paul-Reed** [comment]
I'd keep the '*' in mobile landscape view, it's useful if you only have one quick link dashboard.

**Comment by elyobelyob** [comment]
If you have one, there's no need for the drop down. Anywhere beyond three
and the drop down is required.
Also, can the drop down on desktop also be on the immediate left. Keep it
uniform.
Who's the guru on this stuff, is it you Paul? As mentioned, it's great. And
happy to see it so easily to update on my own system.

**Comment by Paul-Reed** [comment]
Am I the guru?
I wish!
It was chaveiro who wrote v9
If you have one, there's no need for the drop down. Anywhere beyond three
and the drop down is required.
Also, can the drop down on desktop also be on the immediate left. Keep it
uniform.
Who's the guru on this stuff, is it you Paul? As mentioned, it's great. And
happy to see it so easily to update on my own system.

On Tuesday, 29 March 2016, Paul Reed <notifications@github.com> wrote:

> I'd keep the '*' in mobile landscape view, it's useful if you only have
> one quick link dashboard.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/emoncms/emoncms/issues/497#issuecomment-202776561>
>

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/emoncms/emoncms/issues/497#issuecomment-202833379>
