### ISSUE TITLE
Basic help on emoncms 

### ISSUE THREAD

**Issue by emoncms-P** [emoncms/emoncms#499]
Emoncms is a API Cloud ? if yes why ?
I'd also need a descritpion about how Emoncms works with ( Apache , PHP and MySQL and the time server). 
Another little question: can Emoncms work with other versions of Apache/PHP/MySQL, if no then why ?

Thanks for your help

**Comment by Paul-Reed** [comment]
This is not really an issue.
There is a lot of information detailed in the oem website and forum about system requirements and how emoncms works, and if you have something specific,  you can ask in the forum for help.
