### ISSUE TITLE
$runmenu usage?

### ISSUE THREAD

**Issue by XaroRSA** [emoncms/emoncms#505]
In the theme.php file, there is a line a code as below: 

```
        <?php
        if ( !isset($runmenu) ) $runmenu = '';
            echo $mainmenu;
        ?>
```

The $runmenu variable is never used anywhere else in the application, or by any module? What is the intended point of this variable?

**Comment by chaveiro** [comment]
None that i'm aware. Any older module Trystan ?

**Comment by TrystanLea** [comment]
Pretty sure its not used anymore, I've removed it in the latest commit
https://github.com/emoncms/emoncms/commit/1e4da15f98d8dc53c3423ac944f32c114a76b378
