### ISSUE TITLE
No process description available for process 'Total pulse count to pulse increment' 

### ISSUE THREAD

**Issue by ukmoose** [emoncms/emoncms#511]
No process description available for process 'Total pulse count to pulse increment' with id '20'.
Add a description to Module\module_name\module_name_processlist.php in process_list() function, $list[] array at the 'desc' key.

**Comment by jlm** [comment]
Bit me too.

**Comment by glynhudson** [comment]
Good idea, any chance of a PR? I'm away on a break for the next couple of weeks with minimal Internet. If not, I'll take a look when I get back.

**Comment by glynhudson** [comment]
I'm not sure what this input process does, any ideas @chaveiro @TrystanLea ? 

![emoncms input view](https://cloud.githubusercontent.com/assets/758844/19749549/be476a7a-9be1-11e6-9855-3695695f6256.png)

**Comment by TrystanLea** [comment]
Added description https://github.com/emoncms/emoncms/commit/52ec995676da519353f08d4f6b77dd9926d9eb93
