### ISSUE TITLE
Chart urls are stored as full path rather than relative paths in dashboard table

### ISSUE THREAD

**Issue by Bra1nK** [emoncms/emoncms#53]
Whenever I add a new graph to a dashboard the full path e.g src="http://raspberrypi/emoncms/vis/bargraph?embed=1&amp;feedid=35"
rather than the relative path :
src="/emoncms/vis/bargraph?embed=1&amp;feedid=35" is stored in the content field of the dashboard table so I have to go into the database and edit it manually in order to see the graph when viewing via a different base url.

**Comment by chaveiro** [comment]
Fixed since 9.x.
