### ISSUE TITLE
async: false on all ajax functions

### ISSUE THREAD

**Issue by XaroRSA** [emoncms/emoncms#533]
Browser responses with : 
"Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience".
Is there a reason why the async property is changed from default true to false?

**Comment by chaveiro** [comment]
That's a warning.
The goal is to use async everywhere and slowly i had converted most of the widgets to it.
It helped a lot in responsiveness also.
There are places where it cant be done easy because of precedence concerns, or it just does not justify the effort.

**Comment by XaroRSA** [comment]
Yes a warning indeed, thus the need to clarify why this warning is presented.
Do you have a example in the emoncms where this would cause a problem?

**Comment by TrystanLea** [comment]
I dont think it causes any problems, its just not recommended best practice. It does however simplify the code somewhat to use synchronous requests.. which is why I often do it that way
