### ISSUE TITLE
Charts: make fill parameter boolean

### ISSUE THREAD

**Issue by Jerome-github** [emoncms/emoncms#54]
Hi.

The "fill" parameter (fill the area under the plot) is misleading: it is not obvious that 1 means True and anything else means False. The best way would be to use a True/False dropwdown for that.

Apparently (seeing the comments in the code), there is a boolean type for the parameters but it is not used. Is it functional ?

Thinking of it, a wider select-from-list parameter type might be a good idea but it may be more complicated to implement, so not a priority if no chart needs it for the moment.

**Comment by chaveiro** [comment]
Should be fixed on 9+. If not, point code line for that please.
