### ISSUE TITLE
Issue logging input to feed: "Error could not save process list Undefined"

### ISSUE THREAD

**Issue by glynhudson** [emoncms/emoncms#541]
Trying to log an input from an MQTT test input to Emoncms (local) V9.7.1 results in "Error could not save process list Undefined" when I try and save the process list setup after logging to a feed. Logging an emonPi feed (also coming from MQTT) works fine.

I think the issue is `contextid=0` and object id is 0, see console output. Any idea what could be causing this? Test input seems to be updating correctly. 

![screenshot 2016-06-23 at 13 56 53](https://cloud.githubusercontent.com/assets/758844/16303795/752e4132-394a-11e6-9f8f-13c694da07cc.png)

![screenshot 2016-06-23 at 13 56 20](https://cloud.githubusercontent.com/assets/758844/16303796/75522e8a-394a-11e6-9af2-f26caa82aa34.png)

**Comment by mastrogippo** [comment]
As reported on the user forum, I have the same issue. To replicate:
Post messages from the MQTT client as "emon/EVSE/power1" with an int power value.
Add this in the configuration file under [nodes]
```
[[42]]
nodename = EVSE
[[[rx]]]
names = power1
datacodes = h
scales = 1
units = W
```

The new node appears in the Inputs tab and receives the correct number
Try to add a "Log to feed" and click save:
Get this error: "ERROR: could not save processlist. undefined."
The feed appears in the Feeds page, but the value is always NaN and doesn't update.

**Comment by Trickx** [comment]
Is there any progres on this issue?
Is there a known workaround?
How may I support?
I would like to publish my smartmeter data via MQTT to emoncms instead of using the rest API.

**Comment by glynhudson** [comment]
Sorry for the delay trying go debug this. We have been struggling to re-create this issue reliably.

We have isolated the issue to the fact that the input is not being created in the MYQL database (which it should), but is being created in redis.  We believe the issue could be due to the MQTT input script on properly creating the input in MSQL, to try and fix this we have inserted a small delay in the the mqtt_input script https://github.com/emoncms/emoncms/commit/ba893be2fb9a2711ac6e42c844fe1e6f54b96562.

Please test is this fixes the issue for you. You will need to switch to the emoncms master branch:

```
$ rpi-rw
$ cd /var/wwe/emoncms
$ git checkout master
$ git pull 
$ sudo service mqtt_input restart
$ rpi-ro
```

**Comment by JonMurphy** [comment]
so far so good!

FYI - 2nd line should be: `cd /var/www/emoncms`

**Comment by glynhudson** [comment]
Thanks, been corrected.  I'll cautiously close this issue to be reopened of issue returns.

**Comment by glynhudson** [comment]
Issue has not been fixed, continued discussion: 

https://community.openenergymonitor.org/t/adding-a-node-with-mqtt-problem/1396/13

**Comment by glynhudson** [comment]
Interesting: I've just experienced the process list error when trying to log an input to a feed on local emoncms on my laptop (rather than emonPi). There is no mqtt or redis, the script is not running and neither mosquitto or redis-server are installed. This means that maybe the error is not being caused by the mqtt script (as thought) but rather the input process list?....

![screenshot 2017-01-15 at 22 38 22](https://cloud.githubusercontent.com/assets/758844/21966468/faecaaa4-db73-11e6-92ce-f6bf29eef389.png)

**Comment by JonMurphy** [comment]
I am curious if the Input was receiving data on a regular interval e.g., every minute??  Or an Input that was inactive (e.g., Updated was n/a and Value was NaN)?

**Comment by davidski** [comment]
I just experienced this issue on a freshly imaged low-write 9.8.6 | 2017.05.10 emonBase. I was injecting the default weather (current temp, 30 minute intervals, PHPFINA engine) via MQTT. Attempts to add a process to record to a feed would error out with the standard "Unknown process" message though the feed would be created. A MQTT restart followed by a redis flushall allowed me to successfully add the recording process.

Happy to assist in squashing this persistent bug!

**Comment by glynhudson** [comment]
Fixed by https://github.com/emoncms/emoncms/commit/c21302ace74533cd12a605a651a0440e26b6af28
