### ISSUE TITLE
Support russian ru_RU language?

### ISSUE THREAD

**Issue by tehnoinstyle** [emoncms/emoncms#558]
Hi, have a nice day.

I have EmonCMS, set to Synology NAS.
Tell me please, how can I add support for the Russian language?

Thankyou.

**Comment by Paul-Reed** [comment]
I would probably start by looking back through previous translation updates, such as https://github.com/emoncms/emoncms/pull/381 which would give you an indication of what is required. If you run into difficulties, the support forum is probably the better place to get help as it reaches a wider audience.

Paul
