### ISSUE TITLE
Errors on windows on administration page due to linux specific code

### ISSUE THREAD

**Issue by joyrider3774** [emoncms/emoncms#560]
Hi,

Yesterday i updated my local emoncms installation to the latest version in a long time and i noticed the administration page uses linux specific code that display's errors in windows (well at least in wamp).

For example trying to read from /proc/meminfo.

Shouldn't the code detect somehow if the host it's running on is windows or linux and act accordingly ? like read only from  /proc/meminfo on linux and not on windows or if somehow possible access this data on some other way on windows.

a few examples but i think they are all related and i had more of them

```
Warning: file_get_contents(/proc/meminfo): failed to open stream: No such file or directory in C:\wamp\www\emoncmsnew\Modules\admin\admin_main_view.php on line 16
Call Stack
#	Time	Memory	Function	Location
1	0.0020	171200	{main}( )	...\index.php:0
2	0.0258	415904	controller( )	...\index.php:156
3	0.0269	437464	admin_controller( )	...\core.php:64
4	0.0269	438056	view( )	...\admin_controller.php:26
5	0.0281	519336	include( 'C:\wamp\www\emoncmsnew\Modules\admin\admin_main_view.php' )	...\core.php:74
6	0.0281	520248	system_information( )	...\admin_main_view.php:6
7	0.0984	523320	file_get_contents ( )	...\admin_main_view.php:16
```

```
Notice: Undefined index: MemTotal in C:\wamp\www\emoncmsnew\Modules\admin\admin_main_view.php on line 278
Call Stack
#	Time	Memory	Function	Location
1	0.0020	171200	{main}( )	...\index.php:0
2	0.0258	415904	controller( )	...\index.php:156
3	0.0269	437464	admin_controller( )	...\core.php:64
4	0.0269	438056	view( )	...\admin_controller.php:26
5	0.0281	519336	include( 'C:\wamp\www\emoncmsnew\Modules\admin\admin_main_view.php' )	...\core.php:74
```

```
otice: Undefined index: MemFree in C:\wamp\www\emoncmsnew\Modules\admin\admin_main_view.php on line 278
Call Stack
#	Time	Memory	Function	Location
1	0.0020	171200	{main}( )	...\index.php:0
2	0.0258	415904	controller( )	...\index.php:156
3	0.0269	437464	admin_controller( )	...\core.php:64
4	0.0269	438056	view( )	...\admin_controller.php:26
5	0.0281	519336	include( 'C:\wamp\www\emoncmsnew\Modules\admin\admin_main_view.php' )	...\core.php:74
```

```
Notice: Undefined index: MemTotal in C:\wamp\www\emoncmsnew\Modules\admin\admin_main_view.php on line 279
Call Stack
#	Time	Memory	Function	Location
1	0.0020	171200	{main}( )	...\index.php:0
2	0.0258	415904	controller( )	...\index.php:156
3	0.0269	437464	admin_controller( )	...\core.php:64
4	0.0269	438056	view( )	...\admin_controller.php:26
5	0.0281	519336	include( 'C:\wamp\www\emoncmsnew\Modules\admin\admin_main_view.php' )	...\core.php:74
```

```
 Warning: Division by zero in C:\wamp\www\emoncmsnew\Modules\admin\admin_main_view.php on line 279
Call Stack
#	Time	Memory	Function	Location
1	0.0020	171200	{main}( )	...\index.php:0
2	0.0258	415904	controller( )	...\index.php:156
3	0.0269	437464	admin_controller( )	...\core.php:64
4	0.0269	438056	view( )	...\admin_controller.php:26
5	0.0281	519336	include( 'C:\wamp\www\emoncmsnew\Modules\admin\admin_main_view.php' )	...\core.php:74
```

```
Notice: Undefined index: SwapTotal in C:\wamp\www\emoncmsnew\Modules\admin\admin_main_view.php on line 283
Call Stack
#	Time	Memory	Function	Location
1	0.0020	171200	{main}( )	...\index.php:0
2	0.0258	415904	controller( )	...\index.php:156
3	0.0269	437464	admin_controller( )	...\core.php:64
4	0.0269	438056	view( )	...\admin_controller.php:26
5	0.0281	519336	include( 'C:\wamp\www\emoncmsnew\Modules\admin\admin_main_view.php' )	...\core.php:74
```

**Comment by glynhudson** [comment]
Good point, however as you can probably tell most of the user base and developers run Emoncms on Linux, you may well run into other issues. This feature was added by @AndyTaylorTweet, do you have have any ideas how we could detect if Emoncms is running on windows and disable these Linux specific requests e.g. memory use?

**Comment by AndyTaylorTweet** [comment]
I'll write a PR to clean that up in a few mins...

**Comment by joyrider3774** [comment]
looking at the administration page there are 2 other values that might help to see if it's linux or windows.
on my windows 10 box i get this :
Server:
OS:	Windows INTELNUC
Host: 	NT (NT)

those might help to distingush between systems

**Comment by Paul-Reed** [comment]
@AndyTaylorTweet - Can't see your PR, have you sent it?

**Comment by AndyTaylorTweet** [comment]
Paul - Not sure what went on there - I'll do another PR for you - ETA 10 mins

**Comment by Paul-Reed** [comment]
Thanks Andy, it's there now.
...and thanks for the quick support to this issue.

Paul

**Comment by AndyTaylorTweet** [comment]
No problem - I was clearly being very focussed on linux on the pi when I wrote those amendments, I forget there are people who run this software on other platforms :)

**Comment by Paul-Reed** [comment]
@joyrider3774 Master branch now updated with Andy's fix. Can you confirm that this resolves your issue pls.
I don't have a Windows install to test, but presents no issues for Linux installations.

Paul

**Comment by joyrider3774** [comment]
@Paul-Reed no more errors on administration page with latest pull... Thanks @AndyTaylorTweet

**Comment by glynhudson** [comment]
Wow, that was fast! Thanks guys 👍
