### ISSUE TITLE
'Hints' not displayed in vis_render.js

### ISSUE THREAD

**Issue by Paul-Reed** [emoncms/emoncms#570]
'Hints' are included in the code within emoncms/Modules/vis/widget/vis_render.js for vis functions, yet they fail to display in ui.

Paul

**Comment by chaveiro** [comment]
Fixed with https://github.com/emoncms/emoncms/commit/7917b16a3329fcc2c287d75de0e290a3ee77ac96

**Comment by Paul-Reed** [comment]
Still same here.

For example select vis 'barchart', I can't see the text "Line colour in hex. Blank is use default." which is included in optionshint.

Paul

**Comment by glynhudson** [comment]
Can you post a screenshot to illustrate this issue?

**Comment by Paul-Reed** [comment]
As Chaveiro comments above, this was fixed by https://github.com/emoncms/emoncms/commit/7917b16a3329fcc2c287d75de0e290a3ee77ac96 
I'm assuming the error persisted for me due to caching, but all good now.
