### ISSUE TITLE
emoncms.com always says ok, even when the request is no

### ISSUE THREAD

**Issue by Frogmore42** [emoncms/emoncms#572]
When I send an obviously wrong request, I still get an ok, this does not seem like a good thing.
http://emoncms.org/input/post.json2?node=3&json={power:200thisistotalgarbage

**Comment by pb66** [comment]
From the ["Struggles with the EmonCMS API"](https://community.openenergymonitor.org/t/struggles-with-the-emoncms-api/3080/1) forum thread
> Silent failures: I really struggled with bulk upload and API, mostly because of some silent failures -- places where the server returned "OK", but didn't accept my upload4. The fact that this egregious data-loss bug is labelled an "enhancement request" is the main thing that convinced me to walk away from this project.

**Comment by TrystanLea** [comment]
I have created an issue for this on the emoncms.org repo https://github.com/emoncms/emoncmsorg/issues/12
