### ISSUE TITLE
Broken delta type bar graphs in master

### ISSUE THREAD

**Issue by mattjgalloway** [emoncms/emoncms#573]
There's an issue in master right now where bar graphs in the delta mode show today as a massive negative value, like so:

<img width="639" alt="screen shot 2016-10-13 at 20 39 32" src="https://cloud.githubusercontent.com/assets/753010/19364275/67fa922a-9185-11e6-91b9-8bb5c78be8e7.png">

This I believe is due to 69ce584 (I bisected) and it's because previously the data array looked something like this:

```
[
  [1476140400000,438.26626586914],
  [1476226800000,455.49545288086],
  [1476313200000,461.67785644531],
  [1476399600000,null],
  [1476486000000,null]
]
```

And now it looks like this:

```
[
  [1476140400000,438.26626586914],
  [1476226800000,455.49545288086],
  [1476313200000,461.67785644531],
  [1476399600000,0],
  [1476486000000,0]
]
```

Notice the `0` instead of `null`. Null is interpreted by the graph as a gap of sorts, and is ignored. Whereas 0 is interpreted as a proper value of 0.

@chaveiro - any thoughts here? I believe you've been doing all the work around making things typed. FWIW I think that's great work, as the typing was just masking this problem. I'd rather we fix this at the graph level.

As a side note - I've no idea why we're getting *two* extra values at the end. One, fine. That's the midnight at the end of today. But the next one is confusing.

**Comment by mattjgalloway** [comment]
It looks like this is actually affecting a lot of graphs, such as the apps (thanks @pb66):

![9ca3d23ffbe7bfb9cdfdf4f5991c0bfc5bb76076_1_690x323](https://cloud.githubusercontent.com/assets/753010/19365534/12bd9a68-918b-11e6-8f50-8185a683329a.png)

And here for a PHPFINA backed feed's graph:

![19f0db7920ed61a11edb9b12a0c4a5f94c626834_1_690x349](https://cloud.githubusercontent.com/assets/753010/19365533/12bb8692-918b-11e6-9701-c73ca0fa15bb.png)

I suggest we revert these cast diffs. @chaveiro?

**Comment by pb66** [comment]
@mattjgalloway  - The casting is an attempted fix for the numeric datatypes not being carried through to the api's returned data see #540, the casting has been altered and moved around a fair bit for a fair while now.

**Comment by mattjgalloway** [comment]
@pb66 - yeh, the casting is perfect IMO. Except I think that `null` should perhaps bypass the casting. Although that does make me wonder a bit. Perhaps just the value being missing from the data array would be nicer. Both have pros and cons. Both would break existing implementations in subtle ways, unfortunately.

**Comment by pb66** [comment]
[link to forum thread for completeness](https://community.openenergymonitor.org/t/latest-dev-version-display-bug-with-calculated-kwh-bar-graphs/1877?u=pb66)

**Comment by chaveiro** [comment]
Help me out here, what engine is giving the problem and what API is returning the 0 data instead of the null ?

**Comment by mattjgalloway** [comment]
@chaveiro - PHPFINA for sure. Not sure about others. I haven't tested myself other engines.

It's the `data.json` API - as in, the one that is used to gather the data for the bar graph visualisation shown in my first comment.

**Comment by mattjgalloway** [comment]
Can I recommend we have a function that takes a time+value tuple and sanitises it? The fact that the commit causing this specific problem in this issue has casts all over smells a bit to me. Maybe a function something like this:

```
function dataPointFromTimeAndValue($time, $value) {
  $sanitisedValue = null;
  if ($value !== null) $sanitisedValue = (float)$value;
  return array('time'=>(int)$time, 'value'=>$sanitisedValue);
}
```

Still not ideal, but moves all this logic to one place.

But I don't have full context on the data model layer yet, so I might be out - ignore me if that's not a good idea!

**Comment by chaveiro** [comment]
Ok should be ok, please test and let me know...
