### ISSUE TITLE
Language selecion is not working

### ISSUE THREAD

**Issue by RDCH106** [emoncms/emoncms#595]
The language used is the browser default language.

Impossible to select another one.

**Comment by glynhudson** [comment]
Are you referring to emoncms.org or local emoncms? Language should be working on our emonPi pre-build SD card image. If it's a local install then language will need to be installed: https://github.com/openenergymonitor/emonpi/blob/master/docs/SD-card-build.md#18-language-support

**Comment by RDCH106** [comment]
No, I am refering to the main project. The PHP project that you install in a server.

**Look my example**

I have selected English as language to use in EmonCMS:

![image](https://cloud.githubusercontent.com/assets/1483414/20003099/c9f16b24-a284-11e6-9918-c8617f5ccf6b.png)

But nevertheless, I only read in Spanish because my browser is in Spanish:

![image](https://cloud.githubusercontent.com/assets/1483414/20003133/0acecdee-a285-11e6-878d-f377bf6317ca.png)

![image](https://cloud.githubusercontent.com/assets/1483414/20003105/d1586d4a-a284-11e6-84ad-0a2f5bc587db.png)

I have tested the problem in Chrome and Firefox  running a server with PHP Version 5.6.19.

A few months ago [I fixed the problem](https://github.com/emoncms/emoncms/pull/484) but now It doesn't work.

I will try to fix it.

**Comment by glynhudson** [comment]
Is this still an issue? 

Language selection is working ok on the emonSD pre-built SD card for RaspberryPi. Have you installed gettext: 

```
sudo apt-get install gettext
sudo dpkg-reconfigure locales
```
Then install your language and restart apache.

More info: https://github.com/emoncms/emoncms/blob/master/docs/gettext.md

e.g Spanish 

![screenshot-emonpi-2016-11-15-22-44-13](https://cloud.githubusercontent.com/assets/758844/20327457/1215d4a4-ab85-11e6-87f1-33d043ce925f.png)

**Comment by glynhudson** [comment]
Ah sorry, have I misunderstood. Is the issue that you *want* emoncms to display in English but since your browser is set to Spanish Emoncms auto displays Spanish?

**Comment by RDCH106** [comment]
@glynhudson Yes, that's the problem
I'll check it out when I have time.

**Comment by chaveiro** [comment]
That is strange because i can set any language in my profile and it persists it when i login independent of the browser language.

**Comment by BayanN** [comment]
I am also facing the same problem. The language does not change after I select it from the 'my Account' page. I have also tried changing the language of the browser (chrome) but the language of the web site still doesn't  change.

**Comment by glynhudson** [comment]
@BayanN this is a separate issue to what is being discussed here. See my comment above regarding installing gettext and locales to enable language support. The issue being discussed here is that Emoncms is apparently incorrectly picking up the browser language.

**Comment by vazeri** [comment]
A way to go around this is to do what glyn said run :

> sudo apt-get install gettext
> sudo dpkg-reconfigure locales

This however changes the entire OS language

I have yet to review it completely but I believe the problem is actually in the locale.php config file line 88 Even after picking your UTF8 language, the locale.php simply establishes English as the default language in line 88 for emonCMS a quick way to go around this is just to edit this line from en_US to es_ES (after configuring locales) and you will now see everything in spanish
