### ISSUE TITLE
Doc's update

### ISSUE THREAD

**Issue by Paul-Reed** [emoncms/emoncms#632]
Wondering whether https://github.com/emoncms/emoncms/blob/master/docs/RaspberryPi/read-only.md should now be removed from the repo.
It seemed a good idea at the time, but the work which has been put into developing & maintaining the emonpi imagefiles has made this sort of redundant.

Paul

**Comment by glynhudson** [comment]
It's still useful, I reference it from my emonSD SD card build https://github.com/openenergymonitor/emonpi/blob/master/docs/SD-card-build.md
