### ISSUE TITLE
No process description available for process 'Total pulse count to pulse increment'

### ISSUE THREAD

**Issue by Ib2cool** [emoncms/emoncms#639]
No process description available for process 'Total pulse count to pulse increment' with id '20'.
Add a description to Module\module_name\module_name_processlist.php in process_list() function, $list[] array at the 'desc' key.

**Comment by TrystanLea** [comment]
description added here: https://github.com/emoncms/emoncms/commit/52ec995676da519353f08d4f6b77dd9926d9eb93
