### ISSUE TITLE
PHP Notice:  Undefined variable: power

### ISSUE THREAD

**Issue by JonMurphy** [emoncms/emoncms#644]
When I restart the mqtt input service, on my emonPi, I get this error:
> Feb 25 17:13:07 emonpi mqtt_input[1678]: PHP Notice:  Undefined variable: power in /var/www/emoncms/Modules/process/process_processlist.php on line 574

https://github.com/emoncms/emoncms/blob/stable/Modules/process/process_processlist.php#L574

from looking at the code it seems like the $power variable is not defined at Line 563.  When the 
> if ($redis->exists("process:kwhtopower:$feedid")) {

fails, then the $power is currently not defined.

I would add this as a PR but I don't know if $power should be **null** or **zero** of something else...

**EDIT**:  maybe set to $value??

Jon

**Comment by TrystanLea** [comment]
Thanks @JonMurphy, fixed here: https://github.com/emoncms/emoncms/commit/352ba2a073d70609b8f66b8e04364d33d923ad79
