### ISSUE TITLE
Hint: lighttpd rewrite rules

### ISSUE THREAD

**Issue by erazor83** [emoncms/emoncms#649]
Hi there.

I found some rules on the web to get emoncms running with lighttpd. Unfortunately the query string was missing.

So the fixed and currently rules look like this:

    url.rewrite-if-not-file = (
    	"^/emoncms/([^?])\?(.)$" => "/emoncms/index.php?q=$1&$2",
    	"^/emoncms/([^?]*)$" => "/emoncms/index.php?q=$1",
    	"^/emoncms/([^\?]*)(\?(.+))?$" => "/emoncms/index.php?q=$1&$3" 
    )

Hope that helps someone.

**Comment by glynhudson** [comment]
Thanks for sharing :+1:
