### ISSUE TITLE
Emails only work on user ID 1

### ISSUE THREAD

**Issue by spike3312** [emoncms/emoncms#653]
Hi,

I have a server setup with emoncms 9.8.0 which i use along with a friend to store data from various sources, I'm user 1 and when a input value is below 50 it emails me to say so. This works great, however on my friends account ID 2 they want something similar and setup and email for something but the emails never arrive and as far as i can see there is no errors on my server.

Any help would be appreciated.

Thanks.
Matt.

**Comment by glynhudson** [comment]
Hi Matt,

Great to hear you using Emoncms, please use our community forum for support 

https://community.openenergymonitor.org/c/emoncms
