### ISSUE TITLE
Virtual feeds not visable in LED

### ISSUE THREAD

**Issue by dafyrddhirst** [emoncms/emoncms#656]
You cant assign a virtual feed to a vis ie the LED. it is not available on the drop down list.

**Comment by thib66** [comment]
Hello,
@dafyrddhirst @glynhudson ,
I am unable to reproduce the issue with the last version of emoncms. Here is a screenshot showing the virtual feeds in the pulldown list : 
![image](https://user-images.githubusercontent.com/29287201/30228785-852f2c8a-94df-11e7-8620-8349265da1ea.png)
Have you ever tested virtual feeds with the last version?
Regards,
Aymeric
