### ISSUE TITLE
emoncms installation (disk space keeps getting full by itself) if logger is not installed

### ISSUE THREAD

**Issue by vazeri** [emoncms/emoncms#662]
Using 9.8.0 on ubuntu 16.04, installed everything but logger, everything but the logger window seemed fine. everything else worked and i could see, use and configure what i expected, however in the ADMIN PAGE, the Disk mount bar was slowly filling itself, i assumed it was a graphical bug, but no it actually filled itself and the server completely in around 10 days, it filled 8GB by itself, i thought it was my own data from my emontx, but it made no sense

So i upgraded my disk space to 30GB and did a clean install (skipping logger again) on a new instance just to start fresh, and I found something funny if i go to the ADMIN PAGE and **press F5, it instantly fills the disk space with 100MB every time you update the page**, here's a little screenshot demo

![image](https://cloud.githubusercontent.com/assets/9852450/25215988/161e9706-2566-11e7-8f18-8e16cd12594f.png)

now we press F5 and.....

![image](https://cloud.githubusercontent.com/assets/9852450/25216003/220b4db6-2566-11e7-9b7b-963c05e04c14.png)

press it 5 times in a row and...

![image](https://cloud.githubusercontent.com/assets/9852450/25216006/27f7c380-2566-11e7-9d69-dac8efbdc6cc.png)

As you can see it keeps going up, what was i missing? logger
 
![image](https://cloud.githubusercontent.com/assets/9852450/25216023/358d74ea-2566-11e7-878e-ef8e63973b48.png)

the fix is to actually install logger and to run both commands as a super user

touch /var/log/emoncms.log
chmod 666 /var/log/emoncms.log

however this STILL leaves the default installation with the filling up disk space bug, that stops after installing logger, however the occupied space cannot be deleted (or at least i dont know how without wiping the instance)

**Comment by TrystanLea** [comment]
Emoncms now uses in built logger
