### ISSUE TITLE
editrealtime does not work

### ISSUE THREAD

**Issue by matclab** [emoncms/emoncms#666]
Emoncms :  low-write 9.8.3 | 2017.04.18

Trying to edit realtime data does not work, neither deleting data in window, nor editing a single point.

The feed is of type phpfina. 

Any help about diagnosing the problem ?

**Comment by amanfrinati** [comment]
Hi matclab,

did you try to check Javascript Console of Chrome? Or the Network tab? Try to check this tabs when you edit realtime data

**Comment by glynhudson** [comment]
Sorry, I'm unable to replicate this issue
