### ISSUE TITLE
Bargraph tooltip blocks buttons

### ISSUE THREAD

**Issue by Paul-Reed** [emoncms/emoncms#673]
I don't personally use the bargraph, but just noticed that when a bar is selected, it's value & date appear in the graph frame top-left, on top of the D, W, M, & Y buttons, meaning that they cannot be selected.
If the graph size is really wide, then there would be sufficient space, but on smaller/medium graphs this presents a problem.
A possible solution may be to ensure that the label disappears on 'mouseout'.
Currently the label appears on 'mouseover' of the respective bar, but is then retained no matter where the mouse is moved.

![label](https://cloud.githubusercontent.com/assets/973580/26012921/1940d9ae-374e-11e7-825a-f73d535f5da1.png)

**Comment by firefox7518** [comment]
Yes, I noticed this as well. 
From my point of view they should be outside the graph or a button on the right top corner should show them when needed and then they are fully visible not just opaque.

I solved this for my instances manually by moving them up. Of course this way i will loose a little bit of graph area but it was more annoying not be able to use the buttons sometimes or the graph.
![image](https://cloud.githubusercontent.com/assets/12048408/26180866/67d0f794-3b6c-11e7-8e8a-966c0bddd189.png)

**Comment by glynhudson** [comment]
I think this issue better located on the dashboard repo: https://github.com/emoncms/dashboard/issues

**Comment by emrysr** [comment]
This is actually an issue fixed in the vis module of emoncms... 
I've closed the issue on emoncms/dashboard repo (https://github.com/emoncms/dashboard/issues/163)

**Comment by TrystanLea** [comment]
I wonder if it would be possible to place the info below the buttons, and right-aligned but only when there is not enough room to fit it inline, what do you think @emrysr

**Comment by emrysr** [comment]
@TrystanLea - The buttons are only right aligned in the larger view -(screenshot below) 

It will take a bit of work to create the responsive css required to handle dropping the tooltip for the different iframe widths. eg.

![image](https://user-images.githubusercontent.com/1466013/43067733-27337e8a-8e60-11e8-85a6-d4a08e9e70a4.png)

I think the bottom position suits all the variations without jumping about in the different sizes.
