### ISSUE TITLE
unsaved input processing list edits easily lost if Process List buttons used

### ISSUE THREAD

**Issue by pb66** [emoncms/emoncms#686]
When the modal edit process list screen is active, I think the links to the data viewer via the blue Process List buttons should be disabled or maybe even just a pop-up to warn the user if there are un-saved edits. 

Currently it is waaaaaaay too easy to accidentally click a blue button whilst writing a long process list and lose the lot.

**Comment by TrystanLea** [comment]
Thanks @pb66 I've disabled the link when the contents is set to modified https://github.com/emoncms/emoncms/commit/a20e8ab8ffd0d31d4ff5b09b9309f4f3f667601b
