### ISSUE TITLE
Error in var/log/emoncms

### ISSUE THREAD

**Issue by 298christian** [emoncms/emoncms#702]
Hi,I have connected the Rasp to thermal solar control unit by serial port.
In the folder /var/log/emoncms.log I read this error msg.

ERROR|input_controller.php|Request contains no data via csv, json or data tag

I check the Api and It is correct(read &write)
I followed this instruction for installation.
https://github.com/emoncms/emoncms/blob/34da266762122e1fa51b32e27123ba33017ce2fa/docs/RaspberryPi/readme.md
Anyone has some ideas about checks or actions that I can to do.
Thank you in advance

**Comment by glynhudson** [comment]
Please post on the community forums, it's the best place for support. Github issues is designed for bug tracking and reporting: https://community.openenergymonitor.org
