### ISSUE TITLE
Virtual feeds and Scheduler Timezone errors

### ISSUE THREAD

**Issue by TrystanLea** [emoncms/emoncms#705]
See:

https://community.openenergymonitor.org/t/feeds-stopped-working-after-firmware-and-emoncms-upgrade/4696/14

`Fatal error: Uncaught exception ‘Exception’ with message ‘DateTimeZone::__construct(): Unknown or bad timezone ()’ in /var/www/emoncms/Modules/schedule/schedule_model.php:194 Stack trace: #0 /var/www/emoncms/Modules/schedule/schedule_model.php(194): DateTimeZone->__construct(’’) #1 /var/www/emoncms/Modules/schedule/schedule_model.php(147): Schedule->match_engine(NULL, NULL, ‘1501941600’, false) #2 /var/www/emoncms/Modules/schedule/schedule_processlist.php(54): Schedule->match(‘2’, ‘1501941600’) #3 [internal function]: Schedule_ProcessList->if_not_schedule_zero(‘2’, ‘1501941600’, 2926.8198762981, Array, Object(Process)) #4 /var/www/emoncms/Modules/process/process_model.php(60): call_user_func_array(Array, Array) #5 /var/www/emoncms/Modules/process/process_model.php(103): Process->__call(‘schedule__if_no…’, Array) #6 /var/www/emoncms/Modules/process/process_model.php(103): Process->schedule__if_not_schedule_zero(‘2’, ‘1501941600’, 2926.8198762981, Array) #7 /var/www/emoncms/Modules/feed/engine/VirtualFeed.php(84): Process in /var/www/emoncms/Modules/schedule/schedule_model.php on line 194`

**Comment by chaveiro** [comment]
Fix here: https://github.com/emoncms/emoncms/pull/694/commits/9ff1682e198fada8f74c9cbe449022bd090d27ee
