### ISSUE TITLE
Cassandra Integration...

### ISSUE THREAD

**Issue by Paul-Reed** [emoncms/emoncms#706]
@mabi The below is a summary of some issues around Cassandra integration;

In `default.settings.php`, the Cassandra engine has not been added to the array - see https://github.com/emoncms/emoncms/blob/master/default.settings.php#L38-L44

In `default.emonpi.settings.php`, the Cassandra data directory path has not been added to the array - see https://github.com/emoncms/emoncms/blob/master/default.emonpi.settings.php#L58-L67

As the path `/home/pi/data/cassandra/` will not exist in either the emonpi image, or existing installations, what provisions have been made to ensure that the datadir has been added?

The installation guides will need updating to ensure that the datadir is created - see L101 of https://github.com/emoncms/emoncms/blob/master/docs/RaspberryPi/readme.md - Plus all of the other guides if necessary.

The `cassandra.md` read-me does not contain sufficient information to allow many users to use the cassandra engine, it would be great if it could be expanded to cover the full 'cassandra' installation process, and get users up and running.

Have you considered updating the `$config_file_version` flag in `default.settings.php`, `default.emonpi.settings.php` and `process_settings.php` to ensure that 'non-emonpi' users are prompted to update their settings file, otherwise users may continue to use their 'old' settings, and of course cassandra wouldn't work. See - https://github.com/emoncms/emoncms/blob/master/process_settings.php#L66

Paul

**Comment by mabi** [comment]
hello @Paul-Reed I will fix this issues ASAP.
The data directory path is not needed for Cassandra, the only setting is the keyspace (database in Cassandra parlance). I will add information to cassandra.md as you suggest.
