### ISSUE TITLE
Problems with daily/monthly averages

### ISSUE THREAD

**Issue by Fisico2k** [emoncms/emoncms#734]
Trying to plot averaged graphs, following the instructions of Emoncms guide, all feed values are put to null and no graph is plotted. Please where is the mistake?

**Comment by pb66** [comment]
Please go the [OEM forum](https://community.openenergymonitor.org/latest) for general support questions, you are more likely to get assistance there although you will need to provide significantly more info than you have here. Github issues more suited to handling bugfixes and development than providing user assistance.

**Comment by Fisico2k** [comment]
Ok, thank you
