### ISSUE TITLE
web application refactoring

### ISSUE THREAD

**Issue by ishakuta** [emoncms/emoncms#741]
not to criticise you guys, great project, I really like it,
but code structured like in 90s, UI from 00s, as to my liking, 
I'd love to contribute to migrate emoncms application to something better/easier/extensible like https://silex.symfony.com/ or https://lumen.laravel.com/
and maybe https://reactjs.org/ for UI (but that's really really optional in my proposal)

what do you think? I'm going to make changes for myself anyway, but wondering if you think it's worth contributing

Thanks!

**Comment by glynhudson** [comment]
Sorry, we're not currently interested in moving to a new framework. There are other areas that we are focusing on rather than refactoring.

Feel free to create a fork to experiment with refactor.
