### ISSUE TITLE
null input value handing inconsistencies

### ISSUE THREAD

**Issue by pb66** [emoncms/emoncms#749]
On emoncms.org both of these work correctly

https://emoncms.org/input/bulk.json?data=[[0,30,11,null,null,null,55]]
https://emoncms.org/input/post?node=30&csv=11,null,null,null,55

but on emoncms local 

https://myserver.com/input/bulk.json?data=[[0,31,11,null,null,null,55]]

works ok where as

https://myserver.com/input/post?node=30&csv=11,null,null,null,55

returns

    {"success": false, "message": "Format error: csv value is not numeric"}

whilst it is correct `null` is not numeric, it does not cause an error via the bulk api, nor does it cause an error with the same api on emoncms.org.

**Comment by TrystanLea** [comment]
Thanks @pb66, fixed now in latest master, I will make a release with this and a number of other items tomorrow
