### ISSUE TITLE
Feed CSV export interval

### ISSUE THREAD

**Issue by cagabi** [emoncms/emoncms#760]
According to the description in the modal:

_Selecting an interval shorter than the feed interval (or Auto) will use the feed interval instead._

But selecting "Auto"  sets the interval to 1s not to the feed interval.

Once we are there, it would be good to include all the possible intervals when setting up a PHPFINA log to feed process: (5s, 10s, *15s, 20s,* 30s, 60s, 2m, 5m, 10m, 15m, 30m, 1h, 1d) as interval options in the feed export in the drop down(missing 15s and 30s)

**Comment by emrysr** [comment]
Added the above intervals and set the 'auto' option to 10s

https://github.com/emoncms/emoncms/pull/858
