### ISSUE TITLE
Emails from MQTT inputs

### ISSUE THREAD

**Issue by spike3312** [emoncms/emoncms#764]
Hi,

I have spotted an issue where when you update an input via MQTT emails attached to the input process list are not sent but are sent when the input is updated via HTTP.

There is no errors in the log file.

I thought the update to 9.8.27 may have fixed this along with the other MQTT issues but it doesn't seem to have fixed it.

Matt.

**Comment by TrystanLea** [comment]
@emrysr, couple of pointers to help

phpmqtt_input: https://github.com/emoncms/emoncms/blob/master/scripts/phpmqtt_input.php
and
input_controller: https://github.com/emoncms/emoncms/blob/master/Modules/input/input_controller.php

should be loading the same requirements e.g input, feed and process model. 

The email library is loaded here in the event module:
https://github.com/emoncms/emoncms/blob/master/Modules/eventp/eventp_processlist.php#L79

There must be a difference in the context that is effecting this?
