### ISSUE TITLE
Email includes of values

### ISSUE THREAD

**Issue by spike3312** [emoncms/emoncms#765]
Hi,

There is an issue where you get the error:

ERROR: Could not save process list. Invalid characters in arg

When trying to include template tags such as "{value}" within an email process.

Matt.

**Comment by emrysr** [comment]
Both the feed model and input model don't allow the '{' or '}' characters in the supplied email template:

this is what is currently allowed:
- any character in the number unicode category
- any character in the letter unicode category
- the underscore character "_"
- any whitespace character "[SPACE]","[TAB]","[LINE BREAK]"
- the forward slash character "/"
- the dash character "-"
- the full stop character "." 

changing this:
`if (preg_replace('/[^\p{N}\p{L}_\s\/.-]/u','',$arg)!=$arg) `
to this:
`if (preg_replace('/[^{}\p{N}\p{L}_\s\/.-]/u','',$arg)!=$arg) `

that should allow the text in the example email template:
`Example body text: At {time} your {type} from {node} with key {key} named {name} had value {value}.`

https://github.com/emoncms/emoncms/blob/master/Modules/feed/feed_model.php#L1031
https://github.com/emoncms/emoncms/blob/master/Modules/input/input_model.php#L548

I've not implemented this yet as further testing is required before this regex pattern can be modified
