### ISSUE TITLE
Input API responses inconsistent

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#766]
As a result of trying various different formats of the Input API, I have discovered the responses are inconsistent.  Some are simply 'OK' some return a JSON including 'success' or 'failed'.

Could the Input API return consistent responses that can be used by an external application (such as the Node-red node).

I note that #515 asked for the version of the API to be available. This could be included in the response JSON.  By using the call 
````
/emoncms/input/post?
````
the current response is
````
{"success": false, "message": "Request contains no data via csv, json or data tag"}
````
Adding a JSON element of the Emoncms version should be straightforward.

More research; @pb66 [commented](https://github.com/emoncms/emoncms/issues/618#issuecomment-311805258) on #618 that this ok is used by other things.  As the responses are currently inconsistent (some of the post? calls return ok, some an object), perhaps we should be consistently inconsistent!

Use OK for the legacy API of post.json? and a JSON response for the newer /input/post? route.

Final thought, I have been updating the Node-red node and I have included a 'legacy' mode that uses the post.json API.  I do look for the 'success' response, but could easily look for the ok if legacy and 'success'  otherwise.

**Comment by TrystanLea** [comment]
Noting as feature request to be kept open as a reference for future development, when time/resources allow.
