### ISSUE TITLE
Migrating to MQTT input

### ISSUE THREAD

**Issue by elyobelyob** [emoncms/emoncms#771]
Hi,

My http bandwidth from home to my emoncms on AWS is proving pricey, and I'm sure that MQTT input would be an improvement for me. (Already hitting 1.1m http hits in 9 days).

Any instructions on how to achieve this migration? 

I am also (still) using oem_gateway to collect info from sensors.

I am thinking of building a bridge script within my local network to convert oem_gateway to MQTT.

Thanks

Nick

**Comment by elyobelyob** [comment]
Updated to Powered by OpenEnergyMonitor.org | 9.8.27 | 2017.12.21

**Comment by elyobelyob** [comment]
Need to lower my http and use mqtt .. please.

**Comment by JonMurphy** [comment]
you may get more answers posting this on:
