### ISSUE TITLE
Bug (or inconsistency) in Raw Data Element Graph

### ISSUE THREAD

**Issue by nfettinger** [emoncms/emoncms#774]
Using EMONCMS version 9.8.15.
Server: data.openevse.com

Inconsistent data is being delivered or drawn in the graph. It is a Rawdata Element, several are used on the page, but only one is misbehaving.

The feed driving the graph is Realtime PHPFINA, and viewing the feed directly yields accurate and unchanging data. Viewing the graph yields changing data, on every click and refresh, as you can see in the elements below. The graphs are from the same data, the "day" button was clicked to "redraw" the data.
![image](https://user-images.githubusercontent.com/20598445/34884408-460dc9c0-f782-11e7-8509-d2fa5be4a933.png)
![image](https://user-images.githubusercontent.com/20598445/34884427-52684916-f782-11e7-9d19-46d4e53cb647.png)
![image](https://user-images.githubusercontent.com/20598445/34884438-5a5e852c-f782-11e7-87f5-7ba1da41b83f.png)
![image](https://user-images.githubusercontent.com/20598445/34884458-69d51e80-f782-11e7-8feb-dc7819f4a99e.png)

Here is the direct feed view of the data:
![image](https://user-images.githubusercontent.com/20598445/34884480-78d7f7f4-f782-11e7-9189-de6a81d12aed.png)

**Comment by glynhudson** [comment]
I think the issue is the data is being logged to feed at a faster time interval than the data is being posted. The data from OpenEVSE is posted every 30s. The feed logging interval should not be less than this.
