### ISSUE TITLE
Log file permissions and ownership

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#806]
I'm running EmonCMS on DietPi.  As part of the standard DietPi build, the log file is mounted to RAM and rotated each hour.

I have been finding that the ```emoncms.log``` file permissions are being changed and I think this rotation is the reason.

The solution is, I think, to change the ownership of the file.  For me the install had left the file as root:root but changing this to root:www-data seems to resolve the issue.

If the install guide was changed to reflect this, would it cause any other issues?  This change should remove the need to do the chmod, as changing the ownership instead would mean the files could be written to by www-data using the default permissions (again I think).

Although this is a DietPi setup, I wonder if employing logrotate in a 'standard' install could meet with the same problem.

**Comment by glynhudson** [comment]
I don't think logrotate can change file permissions, it certainly does not do this on the standard emonSD image. This sounds like a DietPi install issue. No problem having a step in the install guide to ensure permissions are correct.
