### ISSUE TITLE
Language/locale issue when creating input processing with decimal number

### ISSUE THREAD

**Issue by Jerome-github** [emoncms/emoncms#83]
When French language is selected, I can't create the following input processor: 

x 0.01

My guess is this is a locale issue: in french, the decimal separator is the comma, not the dot. Except I can't enter a dot because the GUI prevents me from doing so. If I enter a dot, the whole processing chain is screwed.

I can provide more details on how it fails, but I think it should be reproducible.

**Comment by chaveiro** [comment]
Is this still an issue with 9.2+?

**Comment by Jerome-github** [comment]
Fixed in 9.2 (https://github.com/emoncms/emoncms/issues/154#issuecomment-164286839).
