### ISSUE TITLE
Tag 9.9.0 may cause confusion

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#834]
There is a version tag 9.9.0 in the repository.  As the latest version is 9.8.29, there is a risk that down the line, this will cause confusion.  Is there anyway to remove or rename it?

**Comment by Paul-Reed** [comment]
@glynhudson  ...it's dated 1st Feb 2017

**Comment by pb66** [comment]
9.9.0 was a typo and it is (in all but name) 9.8.0

![image](https://user-images.githubusercontent.com/5606042/39469920-b13393aa-4d32-11e8-8239-7389bfbaac2b.png)

It will cause confusion as there are not always dates attached and we will most probably want to use 9.9.0 in the future unless we "skip it" but that would be very confusing for users.

![image](https://user-images.githubusercontent.com/5606042/39469877-6441213e-4d32-11e8-8560-a1044c33eea2.png)

Apparently it is possible to rename a tag via the command-line but it's not straight forward, see https://stackoverflow.com/questions/1028649/how-do-you-rename-a-git-tag for example.

**Comment by glynhudson** [comment]
Oh dear, sorry about this. I did try and rename / remove a tag in the past and it did not seem straightforward. I very much doubt it will cause too much confusion. The releases page is correct:

https://github.com/emoncms/emoncms/releases
