### ISSUE TITLE
Docker image loaded fresh gives php error

### ISSUE THREAD

**Issue by nickbrookes76** [emoncms/emoncms#835]
I've tried many many times to implement the docker image, and each time i try to define a virtual feed i end up with the error "Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 94 bytes) in /var/www/html/Modules/process/process_model.php on line 168"
This is returned when i try to input a value to the feed via curl.  Otherwise i just get a spinning icon on the view feeds page. The error also appears eventually on the feeds page after a long wait.
Not sure what is going on, but i can't get past this.  happy to help with problem diagnosis.

**Comment by emrysr** [comment]
Hi @nickbrookes76, I'm trying to re-create the above error...

Steps I've taken:-

1. from the docker-compose directory I ran compose up
1. opened http://localhost:8080
1. registered a user and logged in
1. updated the database [setup->admin->update & check](http://localhost:8080/admin/view)
1. created new virtual feed (id = 1)
1. inserted data via the api this in the terminal:
`curl --data "apikey=xxx" http://localhost:8080/feed/insert.json?id=1&time=UNIXTIME&value=100.0`

and got this response:
```
[1] 14819
[2] 14820
[2]+  Done                    time=UNIXTIME
```

Have I understood your problem correctly? Should I now be seeing the error message you mentioned above?



NOTES

Line **168** in the above error points to the get_module_class() function within the container:

152     private function get_module_class($module_name){
153         /*
154             magic function ____call (above) MUST BE USED with this.
155             Load additional processlist module files.
156             Looks in the folder Modules/modulename/ for a file modulename_processlist.php 
157             (module_name all lowercase but class Modulename_ProcessList 
157 in php file that is with upper case first letter)
158         */
159         $module_file = "Modules/".$module_name."/".$module_name."_processlist.php";
160         $module_class=null;
161         if(file_exists($module_file)){
162             require_once($module_file);
163             $module_class_name = ucfirst(strtolower($module_name)."_ProcessList");
164             $module_class = new $module_class_name($this); // passes this class as reference
165             $module_class_functions = get_class_methods($module_class);
166             foreach($module_class_functions as $key => $function_name){
167                 if (substr($function_name, 0, 2) == "__" || $function_name == "process_list") continue;
**168**                 $this->modules_functions[strtolower($module_name)][strtolower($function_name)] = &$module_class;
169             }
170         }
171         return $module_class;
172     }
173 
174 }



this is not the same code as the master branch of emoncms - it's in L180
https://github.com/emoncms/emoncms/blob/master/Modules/process/process_model.php#L180
