### ISSUE TITLE
Problem with dashboard saving to database

### ISSUE THREAD

**Issue by absalom86** [emoncms/emoncms#84]
Hi,

When I try to use Icelandic letters in the dashboard ( paragraphs or headings ), then save it, I end up with a garbled mess of letters.

For example ðþö becomes Ã¦Ã¾Ã¶ once saved and reloaded.

Is this a problem with the database itself not accepting certain letters, or is there some script that goes over letters and changes out unknown ones ?

Thanks in advance.

**Comment by chaveiro** [comment]
Is this still an issue with latest 9.x ?
