### ISSUE TITLE
MQTT Publish uses completely different library

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#840]
I have just realised that the MQTT publish method uses a completely different library to the subscribe.  I think these should use the same mechanism.

https://github.com/emoncms/emoncms/blob/b3345054b138858a25424019019cc810bbe87a39/Modules/process/process_processlist.php#L50-L50

https://community.openenergymonitor.org/t/another-emonpi-stopped-logging-thread/7267/21?u=borpin

**Comment by TrystanLea** [comment]
Thanks @borpin, this has now been fixed thanks to @emrysr https://github.com/emoncms/emoncms/pull/853

**Comment by borpin** [comment]
Can the library be deleted if not required please.
