### ISSUE TITLE
Sensor data not arriving in emoncms

### ISSUE THREAD

**Issue by MathiasRenner** [emoncms/emoncms#851]
In my emoncms, the data from sensors is obviously not arriving:

![image](https://user-images.githubusercontent.com/2377464/40891011-10793aac-677f-11e8-85b8-a56290fedaa0.png)
In page "feeds", it says " for all entries "inactive". I did not disable them.
The logs in the webinterface do not show relevant errors.
Any ideas?

**Comment by JonMurphy** [comment]
Mathias - please post this issue on the Open Energy Monitor community https://community.openenergymonitor.org

You may want to add more details including any recent software changes and the current software version (at the bottom of the **Inputs** web page).
