### ISSUE TITLE
PHP use of each() is deprecated

### ISSUE THREAD

**Issue by pb66** [emoncms/emoncms#860]
See https://community.openenergymonitor.org/t/error-on-dashboard/7584/4?u=pb66 for more info.

possibly needs [this bit at line 355](https://github.com/emoncms/emoncms/blob/9.8.30/Modules/admin/admin_main_view.php#L355) changing from
```
while ( list($key, $val) = each($system['php_modules']) ) 
```
to something like
```
foreach( $system['php_modules'] as $key => $val )

**Comment by emrysr** [comment]
thanks paul, 
pull request submitted : https://github.com/emoncms/emoncms/pull/866

**Comment by TrystanLea** [comment]
Merged thanks @emrysr
