### ISSUE TITLE
bulk import test data script

### ISSUE THREAD

**Issue by emrysr** [emoncms/emoncms#875]
It would be useful for testing purposes to be able to run a script that would populate the database with an example feed with historical data.

Imports requires a timestamp along with the value. A script would be required to bulk insert the example data into a specific time frame.

**Comment by TrystanLea** [comment]
This could be achieved by including perhaps a year long 60s PHPFina feed. See example.dat and example.meta here: https://github.com/TrystanLea/solarmodel

These could either be copied directly to the phpfina data location e.g /var/lib/phpfina or/and read sequentially and pushed through the input api.
