### ISSUE TITLE
New First User Creation Error

### ISSUE THREAD

**Issue by kumarmohan7** [emoncms/emoncms#898]
Hi,

I create New 1st user creation i got error "[object Object]",

How to solve this error,
Please help to solve this error,

I am now using Shared Host

I attached settings.php & Error Screenshot.
[settings.php](https://github.com/emoncms/emoncms/files/2138492/settings.txt)
![emoncms](https://user-images.githubusercontent.com/7358397/41932774-92dd4a56-799f-11e8-8a47-1dd70bc15ac1.jpg)

**Comment by TrystanLea** [comment]
Hello @kumarmohan7 , could you check your Apache logs? /var/log/apache2/error.log?

**Comment by TrystanLea** [comment]
closing this issue as it is associated with your latest issue which looks like the underlying cause https://github.com/emoncms/emoncms/issues/912
