### ISSUE TITLE
EmonSD incompatible with Zero or 3B+

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#909]
The EmonSD image needs to be updated.  I know there was a recent update to Raspbian so any beta image should probably be moved to the latest release.

At the same time the [Build Guide](https://github.com/emoncms/emoncms/tree/master/docs/RaspberryPi) should probably be checked for validity.

**Comment by glynhudson** [comment]
We have a beta image which is working on Stretch (tested on 3B+): https://github.com/openenergymonitor/emonpi/wiki/emonSD-pre-built-SD-card-Download-&-Change-Log#emonsd-13jun18-beta

There are currently some issues with WiFi that need further testing. I'm currently away from the office for another couple of weeks. Getting this up and running will be a priority when I'm back.

**Comment by borpin** [comment]
I wonder if the recent update to Raspbian might help as a new base image.

**Comment by IvanCaregnato** [comment]
no way to make it work on my old raspberry 2B, so I've used the previous emonSD oct'17 image

**Comment by TrystanLea** [comment]
Latest image compatible with 3B+ but perhaps not Pi Zero?
