### ISSUE TITLE
MySQL Database Store "NULL" DATA

### ISSUE THREAD

**Issue by kumarmohan7** [emoncms/emoncms#912]
In my host MySQL Database Store "NULL" data only,
if create account or create feed all data write in database in "NULL"
How to solve this issues...
![database_error](https://user-images.githubusercontent.com/7358397/42413839-8b306b44-8246-11e8-8173-ac128401b819.jpg)

please help to solve this issue...

**Comment by TrystanLea** [comment]
Hello @kumarmohan7 Im afraid I havent seen this issue before, could you ask you hosting provider if they have any recommendations? it looks like a hosting specific issue.
