### ISSUE TITLE
Time axis tick alignment (hrs, days) with non-UTC timezone

### ISSUE THREAD

**Issue by chuck-h** [emoncms/emoncms#913]
I ran into this problem with misaligned ticks and it seemed to require a fix in the jquery.flot.time library code.

I posted it as an issue on flot, with a patch https://github.com/chuck-h/emoncms/commit/fadf28ad6728c477d9faacb337132fdb2256af11, but maybe there is a solution within emoncms. There are a lot of corner cases in timezone stuff and I haven't even tried to test them.

https://github.com/flot/flot/issues/1582

![flot_ticks](https://user-images.githubusercontent.com/2141014/42429298-0c062280-82ed-11e8-9190-f085efa03c3f.png)

**Comment by TrystanLea** [comment]
Hello @chuck-h what modifications did you make to create the result you see?

**Comment by chuck-h** [comment]
@TrystanLea , I posted the changes at https://github.com/chuck-h/emoncms/commit/fadf28ad6728c477d9faacb337132fdb2256af11, can you see them?

**Comment by chuck-h** [comment]
@TrystanLea, Yes, timezone is set to Los Angeles in emoncms and in my browsing computer's OS (Ubuntu 16.04); I'm using chrome browser which AFIK adopts the OS timezone setting. FWIW I just tried setting emoncms timezone to UTC and reloading a graph page and it had no effect on tick position.

**Comment by TrystanLea** [comment]
Can anyone else replicate this issue? Its not something I can replicate unfortunately
