### ISSUE TITLE
rename phpmqtt_input.php

### ISSUE THREAD

**Issue by emrysr** [emoncms/emoncms#915]
As the phpmqtt_input service now also outputs to mqtt..

@pb66 recommended we change it in pr https://github.com/emoncms/emoncms/pull/905

Rename:

- **phpmqtt_input.php** script to **emoncms_mqtt.php**
- **mqtt_input** service to **emoncms_mqtt**

The documentation would also need to be updated regarding the service installation

If there are any suggestions of names please comment.

**Comment by borpin** [comment]
My concern is how to do it so it does not break existing installations.

**Comment by borpin** [comment]
This was done as part of the 9.9.6 release
