### ISSUE TITLE
Preparation of device-support branch for release, alongside new device module

### ISSUE THREAD

**Issue by TrystanLea** [emoncms/emoncms#917]
Following from the long running thread on improving device module integration in emoncms https://community.openenergymonitor.org/t/development-devices-inputs-and-feeds-in-emoncms/4281/130 It would be great to bring these changes into emoncms core including the new inputs and feeds interface style.

Recent additions to the feeds list interface including Units and the not yet merged feed-trim/clear features need to be re-added into the device-support branch input and feed list views.

Ideally it would be great to soft launch this feature with a simple toggle to switch between old and new interfaces so that users can test.

Device support branch of emoncms core:
https://github.com/emoncms/emoncms/tree/device-support

Device module:
https://github.com/emoncms/device

The device support branch also specifies that the graph module is required, it may be time to merge this into core, alternatively a fall back needs to be in place:
http://github.com/emoncms/graph

- The device-support branch input UI allows for the creation of devices from the inputs interface. 
- Devices are automatically created and are linked to input node name.
- Devices are automatically initialised if 'describe' is set in the request to the input API.

**Comment by emrysr** [comment]
added pull request to the device-support branch to allow uses to opt in to these new features: https://github.com/emoncms/emoncms/pull/932
