### ISSUE TITLE
logrotate.conf file contains invalid default value

### ISSUE THREAD

**Issue by Jerberus** [emoncms/emoncms#928]
Was receiving errors when trying to run logrotate of 
```
switching euid to 0 and egid to -1
error: error switching euid to 0 and egid to -1: Invalid argument
```
after adding group name "su root root" line of logrotate.conf, I was able to run logrotate successfully from cron.daily.  In the release, this should be "su root root" 
(unless this is a Debian-only issue).

**Comment by TrystanLea** [comment]
Thanks for the pull request!
