### ISSUE TITLE
Dashboard Button not working

### ISSUE THREAD

**Issue by kumarmohan7** [emoncms/emoncms#939]
i try to use button in dashboard i got some error “field could not be updated”
how to update feed value in when i press button in dashboard…

**Comment by Paul-Reed** [comment]
The is the emoncms core repo.
Please post any dashboard related issues in the [dashboard repo](https://github.com/emoncms/dashboard)

Also, have you asked in the [emoncms forum](https://community.openenergymonitor.org/), which is well supported by a number of experienced users, and may be the best option to get a quick reply.
