### ISSUE TITLE
Virtual Feeds to Apps

### ISSUE THREAD

**Issue by danbates2** [emoncms/emoncms#940]
Opening discussion here of the possibility to enhance the myelectric app by making virtual feeds available.
Virtual feeds presently are real-time input processors, and thus don't store data. Myelectric realtime power doesn't need data storage, so a virtual feed theoretically isn't a problem for power.. for historical data though..
Perhaps an option could be selected during virtual feeds creation, to store data to be used by, for example, myelectric graphs.
The other approach would be for myelectric to run the 'virtual processors' on historical input processor feed data to arrive at the same information.

**Comment by chaveiro** [comment]
For the matter of consuming feeds, Virtual feeds are like any other feed, even with historical data, assuming that the process list of the virtual feed source other 'real' feeds.

**Comment by danbates2** [comment]
Understood. I notice the processing time required to look at historical virtual data is quite long.
I'm actual desire more simply a realtime virutal value to be able to be fed to myelectric app.

**Comment by relft** [comment]
have you solved? how are you using virtual feed on app, for example mysolar?

**Comment by danbates2** [comment]
Not solved.
there was a way to test this. I'll check now for you.

To change the feed type in mysolar for example open
emoncms/Modules/app/apps/OpenEnergyMonitor/mysolarpv.php
see lines 166 onwards.
Change engine id from 5 to 7 for virtual feeds. It wasn't working well for me before.

Engines and their id number are listed in settings.php, or defined for real enum.php line 19 onwards.

**Comment by relft** [comment]
Hi, first thanks
I don't really understand if it is supported and working...

El dg., 7 de juny 2020, 23:51, Daniel Bates <notifications@github.com> va
escriure:

**Comment by danbates2** [comment]
Unfortunately it is not supported.

**Comment by relft** [comment]
And changes thst you supported onprevious messages are working or not?
Thanks

El dl., 8 de juny 2020, 23:15, Daniel Bates <notifications@github.com> va
escriure:

**Comment by danbates2** [comment]
Not working. Perhaps in the future.

**Comment by TrystanLea** [comment]
Cheers. This has now been fixed, part of the work done here a couple of years ago: https://github.com/emoncms/emoncms/commit/f19d07226b64804f401336de8bf5eb3b27905c5e
