### ISSUE TITLE
Loading apps page.

### ISSUE THREAD

**Issue by danbates2** [emoncms/emoncms#951]
When I first arrive at page 'Apps' from the top navigation bar, it is unclear which page is being loaded, also I can't seem to prioritise which app is loaded first. A simple highlight in the left 'apps navigation bar' would show what app is being loaded and is being worked on/configured.
When pressing 'Apps' from the top navigation bar, also I think it'd be a good idea to have no app load, unless a particular app has been 'starred' like in dashboards.

**Comment by TrystanLea** [comment]
Thanks Dan, Something like? 
![highlight](https://user-images.githubusercontent.com/503186/44076949-f187d498-9f99-11e8-841a-4b4a50ce2454.png)

**Comment by danbates2** [comment]
Exactly :)
👍

**Comment by danbates2** [comment]
An excellent shade for my screen here.. and just looked at on mobile and it's clear there too.

**Comment by danbates2** [comment]
close issue?
