### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by thib66** [emoncms/emoncms#956]
In the page **_emoncms/input/api_** the following link is broken : 
![image](https://user-images.githubusercontent.com/29287201/43823629-fed9355a-9aef-11e8-8337-079c22a8687c.png)
![image](https://user-images.githubusercontent.com/29287201/43823643-06673bbe-9af0-11e8-9122-87dcbf97a828.png)

**Comment by glynhudson** [comment]
https://github.com/emoncms/emoncms/blob/master/docs/input_encrypted.md

**Comment by thib66** [comment]
👍  Thanks
