### ISSUE TITLE
Tree-like input processing (fork)

### ISSUE THREAD

**Issue by ahuillet** [emoncms/emoncms#96]
Hello,

as I am a relative beginner to emoncms I want to first describe what I am trying to achieve.
I have built a pulse counter for my gas meter that transmits the information to emoncms. This pulse counter is a positive value that indicates the number of pulses (10 liters of gas) that were consumed. (This is needed because wireless transmission can be unreliable)

I want to use this to generate:
- gas index (reproduce the value on my meter)
- power (to see when I'm burning gas in the day)
- kWh per day (to see when we're consuming too much)
- kWh per day - histogram

Each of those is individually easy to obtain from the pulse input, but I haven't managed to get all for values.
I have a single input (gas_pulse). This is my current input process :

- pulse_difference
- multiply by 0.01
- accumulate into "gaz_index" feed
- multiply by 10.83 (kWh per thousand liters of gas)
- kWh_to_power into "gaz power" - doesn't work as is because it requires a *difference* of kWh, not the index, but that's not the real issue here
- power_to_kWh/d into "gaz kwh per day"

My problem is with the last two lines - ideally I would like the input process to *fork* after the first multiply, and have three branches:

- one accumulator for index
- one derivator for power
- one kWh/d branch

Is there any way to do this with emoncms as it stands?

Thank you

**Comment by chaveiro** [comment]
On my last pull request i've added a new process called "reset to original" 
I will put the original value of the input on the next process.
This way you could start over the calculations on the same process list after the reset to original and fork it from there after to log to new feeds as needed.
I'm using it for multi-rate feeds for the same input.
