### ISSUE TITLE
REDIS systemd configuration

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#967]
A query was raised on the community re REDIS not restarting.  The solution identified was to add in a greater sleep figure into a script which to my mind is not ideal.

I suspect the issue is that the latest version of REDIS has a significantly different stock systemd control file that adds in a number of specific folder requirements when compared to older installs.

https://community.openenergymonitor.org/t/redis-does-not-startup-after-a-reboot/7858/8

There has also been discussion on the undesirability of modifying stock systemd files (overwritten on update being the main one).  I also researched this and determined there is a way to introduce a specific a control file without editing the stock file. https://community.openenergymonitor.org/t/mosquitto-startup-issues/7386

I suggest a systemd control file is created that suits the requirements of Emoncms especially where it is installed in a RO filesystem environment.

**Comment by TrystanLea** [comment]
Hello @borpin do you know if this issue is still relevant?
