### ISSUE TITLE
Server info incorrectly reported when using the copy to clipboard button

### ISSUE THREAD

**Issue by pb66** [emoncms/emoncms#978]
See https://community.openenergymonitor.org/t/rpi-3b-getting-hot-redis-high-cpu-usage/8263?u=pb66

Whilst the admin page says "0 feed points pending write" in the Emoncms/buffer section

![image](https://user-images.githubusercontent.com/5606042/44298091-c6fc7380-a2d4-11e8-94da-62cba641341b.png)

the information copied by the "copy to clipboard" button reports "loading"

![image](https://user-images.githubusercontent.com/5606042/44298114-16db3a80-a2d5-11e8-988a-da248f0a289e.png)

I suspect one or the other is telling porkies

**Comment by TrystanLea** [comment]
Note: Still present in latest master 17 jan 19

**Comment by TrystanLea** [comment]
This was fixed in a more recent version I believe
