### ISSUE TITLE
Graphs: left/right scales and tag locations.

### ISSUE THREAD

**Issue by danbates2** [emoncms/emoncms#979]
Graphs with different left/right scales display the node and key tags like this:

![screen shot 2018-08-19 at 06 02 14](https://user-images.githubusercontent.com/5250782/44305411-e350ec80-a376-11e8-8147-d8f65e7c59cc.png)

Instead, to clearly distinguish what belongs to left and right, they could look like this? : 

![screen shot 2018-08-19 at 06 02 14](https://user-images.githubusercontent.com/5250782/44305410-e350ec80-a376-11e8-804f-f7fde5823457.jpg)

**Comment by emrysr** [comment]
this is an issue in the graph module repository:
https://github.com/emoncms/graph/issues/9

pull request with coloured left/right legend labels:
https://github.com/emoncms/graph/pull/47
