### ISSUE TITLE
crontab inclusion of service-runner causing high CPU usage

### ISSUE THREAD

**Issue by danbates2** [emoncms/emoncms#981]
https://community.openenergymonitor.org/t/rpi-3b-getting-hot-redis-high-cpu-usage-emonsd-13jun18-dev-specific/8263/

**Comment by danbates2** [comment]
disabling the crontab fixes the CPU use issue, but service-runner remains broken.
as an alternative log-follower maybe this: [](http://logio.org/)

**Comment by glynhudson** [comment]
Fixed by https://github.com/openenergymonitor/emonpi/commit/4b37af0f29ece5e2dddb1b02387bfbfa5f8ac78a
